### ISSUE TITLE
Ignoring Flow `import type` statements when using `import/max-dependencies`

### ISSUE THREAD

**Issue by Dromin** [import-js/eslint-plugin-import#1136]
Currently, Flow `import type` statements are included in the dependency count when using the `import/max-dependencies` rule. This makes the rule far less useful for identifying code smells in projects using Flow, especially if you tend to put type defintions in separate files for the rest of the code (which then need separate imports). 

I think it would be useful to have an option to ignore `import type` statements when counting depencencies. Thoughts?

**Comment by ljharb** [comment]
I think they should not be ignored - types are deps too - but perhaps we could add an option that allows you to set a separate count for flow types?

**Comment by Dromin** [comment]
Yeah, that would be better. (And I assume you could use it to ignore type imports if you wanted by setting the max count for those really high.)
