### ISSUE TITLE
import/order + ts leads to runaway resource usage

### ISSUE THREAD

**Issue by luxaritas** [import-js/eslint-plugin-import#1152]
For context, I'm running:
* node 8.11.3
* npm 6..0
* eslint 4.19.1
* typescript-eslint-parser 17.0.1
* typescript 3.0.1
* eslint-plugin-import 2.13.0

Test config:
```javascript
module.exports = {
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "sourceType": "module"
    },
    plugins: [
      'import'
    ],
    'rules': {
        'import/order': 'error',
    }
};
```

Test code:
```typescript
// test.ts
import {x} from './second.ts'; // Content doesn't matter, I just used `export var x:number = 5;`
import * as _ from 'lodash';
```
Result: CPU goes from 125-150% (via `top`), and memory keeps going up (though it can fluctuate a bit on its way) until the process is eventually killed.

Also interesting to note: When adding `'object-curly-spacing': ['error', 'never'],` to the config and changing the first import to `import { x } from './second.ts';`, the lint doesn't stall/crash - however it does change the content of `test.ts` to:
```typescript
import {ximport { x } from './second.ts';
import * as _ from 'lodash';
import { x } from './second.ts';
import * as _ from 'lodash';
import { x } from './second.ts';
import * as _ from 'lodash';
```

I have verified that everything works fine with `babel-eslint`. Can't tell whether the issue originates with eslint-plugin-import or typescript-eslint-parser, but I figured I'd start here since it's furthest "downchain" in the eslint process - let me know if I should instead file something there.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript
