### ISSUE TITLE
Feature request: disabling exportMap cache

### ISSUE THREAD

**Issue by chichiwang** [import-js/eslint-plugin-import#1500]
I am aware this is an rare/edge case scenario but I have a need for busting/disabling the [ExportMap exportCache](https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L18).

The scenario: I have a Node script that leverages [CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) to read lint results from 2 different branches of a repository to diff the results. In cases where files have been moved or renamed: despite passing in new path patterns for linting, the [ExportMap exportCache](https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L18) still retains the old filenames/pathing and throws an exception when it tries to access non-existent files on the filesystem.

I searched through issues and this may be related to #1444 where @ljharb stated the opinion that it was on VSCode to fix. However, this is not easily remedied in my case on the script side. Eslint itself handles these scenarios just fine, it is just this plugin that causes issue.

An option to disable the cache would be much appreciated here. If there are other approaches to resolve this issue, please let me know.

Thanks!

**Comment by ljharb** [comment]
The cache applies across different rules in the same linting run - I’m quite sure the performance of linting would be untenable with the cache disabled.

Adding a programmatic method to reset the cache, however, seems workable.

**Comment by chichiwang** [comment]
@ljharb A programmatic method would help to solve the issue.

Pardon my lack of familiarity with this codebase, but alternatively would it be possible to scope the cache to an instances of the `ExportMap` class rather than at the module level, or would that be problematic for performance?

**Comment by ljharb** [comment]
It's not a class and there are no instances; it's a stateful module.

**Comment by chichiwang** [comment]
@ljharb I misunderstood as I did not carefully look at it's uses, based on [the class declaration](https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L20) I thought it might be used as a class. I see now that we are simply appending methods onto the class object and using those directly instead.

**Comment by soryy708** [comment]
Is this still needed?

`clear()`ing the `exportCache` sounds trivial.

https://github.com/import-js/eslint-plugin-import/blob/18787d3e6966028983af81a878d1a505893932d4/src/exportMap/builder.js#L23

**Comment by ljharb** [comment]
It's certainly something a vscode extension can opt in to doing.

I definitely don't want to officially support this use case, though, so I'll close.
