### ISSUE TITLE
Add `.json` file extension to typescript config

### ISSUE THREAD

**Issue by dietergeerts** [import-js/eslint-plugin-import#1508]
We are adding TypeScript to our project, and I have added the import/typescript extends to fix the extensions for the airbnb-base settings, but I see that `.json` is not provided. As this is a much used feature, it would be great to have this added by default. (it's also a default for require in node)

```
  extends: [
    'airbnb-base',
    'plugin:import/typescript',
  ],
  settings: {
    // 'plugin:import/typescript' does not have the `.json` extension configured
    'import/resolver': {
      node: {
        extensions: [
          ...importTypescript.settings['import/resolver'].node.extensions,
          '.json',
        ],
      },
    },
  },
```
I was wondering if it's allowed to add this by default?

**Comment by ljharb** [comment]
TypeScript doesn't support importing json by default.

**Comment by dietergeerts** [comment]
But it does enforce JSON as configuration?

**Comment by dietergeerts** [comment]
And it supports it if the compiler option is on (resolveJsonModule)

**Comment by dietergeerts** [comment]
I understand that you would not like to do this because it's something optional, but will it hurt for people that don't have this option on to include it? If it doesn't, then I would like to see this being added, as right now, it adds a lot of extra stuff that we need to maintain to our linting configuration. And needing to overwrite these settings means that when they change, we need to check and change with it. I don't like this kind of maintenance.

**Comment by ljharb** [comment]
Yes, because typescript would warn on things the linter allows.

If there’s a way to determine the tsconfig setting here, then we could automatically include it when relevant.

**Comment by dietergeerts** [comment]
Would we have access to the config given to the typescript parser? https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#configuration
If this would be the case, then it could also be used to find out if the settings is on, and then also allow `.json` files.

**Comment by ljharb** [comment]
That's what I'd assume on all points.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript
