### ISSUE TITLE
[import/order] Side-effect imports break autofix

### ISSUE THREAD

**Issue by seb-saletes** [import-js/eslint-plugin-import#1548]
I have a problem with autofix and side-effect import

- eslintrc:
```javascript
"import/order": ["error", { "groups": ["unknown", "external", "internal", "builtin", "index", "sibling", "parent"] }],
```

- file.tsx
```javascript
import { Component1 } from './file1';
import './style.scss';
import { Component2 } from 'my-lib/component2';
```
What is the workaround to make this scenario autofixable ?

**Comment by ljharb** [comment]
No autofix should not be moving any imports across a "bindingless" import (ie, `import 'path'` versus anything else) - and by strong convention, side-effecting modules should only be imported without a binding.

If you're seeing the autofix for this rule violate that invariant, then the autofix should be removed pending a bugfix.

**Comment by youssefm** [comment]
Why doesn't `import/order` move these bindingless imports to the top of the file and preserve their relative order? It's unfortunate that these just break autofix.

**Comment by lgenzelis** [comment]
For anyone arriving here in 2022, [`warnOnUnassignedImports`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#warnonunassignedimports-truefalse) may be what you need: it won't autofix, but it'll warn you, and that's what I wanted.
