### ISSUE TITLE
import/named: Typescript interface export from *.d.ts file not found

### ISSUE THREAD

**Issue by mtjn** [import-js/eslint-plugin-import#1699]
import/named reports an error on the code: `import { Moment } from "moment";`

"Moment not found in 'moment' (import/named)"

This is valid code, typescript correctly parses the imported interface from moment.d.ts

Likely related to: https://github.com/benmosher/eslint-plugin-import/issues/1282

**Comment by ljharb** [comment]
Although now that `import type` exists, I'd suggest using that.

**Comment by mtjn** [comment]
Thanks for the tip, I will use that!
