### ISSUE TITLE
import/default with camelcase-keys

### ISSUE THREAD

**Issue by w4-jake** [import-js/eslint-plugin-import#1757]
Hi and thank you for your work on this plugin. I am having trouble default importing without lint errors from [camelcase-keys](https://github.com/sindresorhus/camelcase-keys), even though others seem to be able to do so.

camelcase-keys: `6.2.2`
snakecase-keys: `3.2.0`

eslint: `6.8.0`
eslint-plugin-import: `2.20.1`

typescript: `3.8.2`
vs code: `1.44.2`

In my project, camelcaseKeys is imported and called successfully, but I get the below error when linting:

```typescript
import camelcaseKeys from 'camelcase-keys' // <-- here
import { expect } from 'chai'
import snakecaseKeys from 'snakecase-keys'

describe('keys tests', () => {
  describe('camelcaseKeys', () => {
    it('changes keys to camelcase', () => {
      // eslint-disable-next-line @typescript-eslint/camelcase
      const result = camelcaseKeys({ snake_case: 'value' })
      expect(result).to.be.deep.equal({ snakeCase: 'value' }) // <-- passes
    })
  })

  describe('snakecaseKeys', () => {
    it('changes keys to snakecase', () => {
      const result = snakecaseKeys({ camelCase: 'value' })
      // eslint-disable-next-line @typescript-eslint/camelcase
      expect(result).to.be.deep.equal({ camel_case: 'value' }) // <-- passes
    })
  })
})
```

`1:8 error No default export found in imported module "camelcase-keys" import/default`

Strangely, I have no linting issue when default importing from snakecase-keys, whose [index file](https://github.com/bendrucker/snakecase-keys/blob/master/index.d.ts) seems structurally the same to [that](https://github.com/sindresorhus/camelcase-keys/blob/master/index.d.ts) of camelcase-keys.

If it is useful, here is the tsconfig:

```json
{
  "compilerOptions": {
    "alwaysStrict": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "*": ["@types/*.d.ts"]
    },
    "allowJs": true,
    "typeRoots": ["overrides", "node_modules/@types"]
  }
}
```

Thank you for any guidance. I am pretty new to typescript so I may be missing something simple.

**Comment by ljharb** [comment]
I'm very confused why one would work and the other wouldn't.

**Comment by w4-jake** [comment]
We are too. If there are difficulties reproducing the problem, please let me know what more about the project I should share.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript

And the two declaration files are different

https://github.com/sindresorhus/camelcase-keys/blob/1082010f742c9f5b371a4e2e7f86e2faa28f4e41/index.d.ts#L190

https://github.com/bendrucker/snakecase-keys/blob/b3a1abb37648da041d153286141138825266c613/index.d.ts#L108
