### ISSUE TITLE
[max-dependencies]: new option 'ignoreTypeImports'

### ISSUE THREAD

**Issue by rfermann** [import-js/eslint-plugin-import#1843]
This rule aims to notify about potential code smell or a module doing too much based on the number of imported dependencies.

It doesn't differentiate between regular imports and type imports though. Type imports are neither indicating code smell nor do they indicate that a module is doing too much.

Therefore it might be good to implement a new option allowing or disallowing the consideration of type imports.

Note: this would only influence users of Typescript and Flow.

**Comment by ljharb** [comment]
That seems reasonable.
