### ISSUE TITLE
How do you debug anything with import/order

### ISSUE THREAD

**Issue by NullVoxPopuli** [import-js/eslint-plugin-import#1886]
there are a lot of group/names - -wondering how I can tell what specific imports are identified as what, cause based on my conflagrations, it looks like a lot of what I'm doing doesn't matter or is incorrect, or.... I don't even know

this is my config:

```js
    groups: [
      ['builtin'], ['external'], ['internal'], 'unknown',
      ['parent',  'index', 'sibling'], 'object',
    ],
```
and based on my pathGroups, it looks like external and internal and unknown are all still being grouped together

**Comment by ljharb** [comment]
Can you provide your entire eslint config, and also the code in question?

**Comment by theahura** [comment]
apologies for reviving a dead thread, but was this ever resolved @NullVoxPopuli ? how did you debug?

**Comment by ljharb** [comment]
Closing, but happy to keep discussing here.
