### ISSUE TITLE
[import/no-extraneous-dependencies] Error with Angular 10 strict mode

### ISSUE THREAD

**Issue by gagle** [import-js/eslint-plugin-import#1893]
When using Angular 10 strict mode, it adds a new `package.json` file inside `src/app` directory. When I enable `import/no-extraneous-dependencies` I get lots of errors, one per import of a node_module package.

```
1:31  error  '@ngneat/spectator' should be listed in the project's dependencies. Run 'npm i -S @ngneat/spectator' to add it  import/no-extraneous-dependencies
```

When I remove the `src/app/package.json` file the errors disappear. The dependencies are listed in the root package.json. Maybe this error comes directly from Eslint. Could you confirm?

**Comment by ljharb** [comment]
In what directory are you running eslint?

**Comment by gagle** [comment]
At the root always.

-------- Original message --------From: Jordan Harband <notifications@github.com> Date: 8/29/20  00:33  (GMT+01:00) To: benmosher/eslint-plugin-import <eslint-plugin-import@noreply.github.com> Cc: Gabriel Llamas <gabriel.llamas.llopis@gmail.com>, Author <author@noreply.github.com> Subject: Re: [benmosher/eslint-plugin-import]
  [import/no-extraneous-dependencies] Error with Angular 10 strict mode (#1893) 
In what directory are you running eslint?

**Comment by ljharb** [comment]
That's correct :-)

It's entirely possible that this rule doesn't look upwards to `process.cwd()`, merging package.jsons along the way. I'd be happy to accept a PR fixing it, or implement a fix on top of a PR with failing test cases.

**Comment by ljharb** [comment]
@gagle is this no longer a problem for you?
