### ISSUE TITLE
[import/default] typescript - esModuleInterop value not read correctly

### ISSUE THREAD

**Issue by Ebooth** [import-js/eslint-plugin-import#1908]
The following PR was created to detect the esModuleInterop parameter in tsconfig.json. https://github.com/benmosher/eslint-plugin-import/commit/0b585a14d605eb059050bb07ab3c2a2abf3961a6

It seems that the tsconfig.json file is loaded like a text file. So any extended configuration provided in the  "extends" parameter of the tsconfig.json file won't be detected. 

**Expected:**
I can set the esModuleInterop value in a tsconfig.base.json that will be extended by tsconfig.json and the rule import/default will work

**Here you can find a reproduction of the bug:**
https://github.com/Ebooth/eslint-plugin-import-esModuleInterop-bug

Also it could be nice to add support for monorepo as the current code works only in you have one typescript project.

**Comment by ljharb** [comment]
Hmm, I would expect `tsConfigLoader` to resolve "extends".

**Comment by mrmckeb** [comment]
We hit this ourselves and I've only now gotten around to submitting a fix sorry!
https://github.com/import-js/eslint-plugin-import/pull/2240
