### ISSUE TITLE
[no-unused-modules] Dynamic import doesn't mark exports as used

### ISSUE THREAD

**Issue by phaux** [import-js/eslint-plugin-import#1951]
Repro:

```ts
// foo.ts
export const foo = "foo"

// index.ts
async function test() {
  const { foo } = await import("./foo")
  const foo2 = await import("./foo").then(mod => mod.foo)
  const mod = await import("./foo") // should mark all non-type exports as used
}
```

My specific use case is:

```tsx
import { lazy } from "react"
const Foo = lazy(() => import("./Foo"))
```

> exported declaration 'foo' not used within other modules

Config:

```json5
{
  "extends": [
    "plugin:import/recommended",
    "plugin:import/typescript",
    // and more ...
  ],
  "rules": {
    "import/no-unused-modules": ["error", { "unusedExports": true }],
  },
}
```

Versions:

```
@typescript-eslint/parser: 4.8.0
eslint: 7.13.0
eslint-plugin-import: 2.22.1
```

**Comment by ljharb** [comment]
This was intentional during the design of the rule (#1142, cc @rfermann).

When a dynamic import is done with a static, hardcoded path, it does seem possible for this plugin to detect it, but it would have to ignore any other forms of `import()`. A PR that detects these would be appreciated.

**Comment by taoliujun** [comment]
me too.
components are lazy imported.

**Comment by silverwind** [comment]
Related PR: https://github.com/benmosher/eslint-plugin-import/pull/1660
