### ISSUE TITLE
eslint-plugin-import doesn't work when load entire module

### ISSUE THREAD

**Issue by IlyaSavich** [import-js/eslint-plugin-import#2013]
Hello, while using this packahe found that it doesn't work correctly when try to load entire module.

My configuration is
```
// .eslintrc

"extends": [
    ...
    "plugin:import/typescript"
],

"rules": {
    ...
    "import/order": [
            "error",
            {
                "groups": ["builtin", "external", "internal", ["parent", "sibling", "index"]],
                "pathGroupsExcludedImportTypes": ["builtin"],
                "pathGroups": [
                    {
                        "pattern": "core-config/**",
                        "group": "internal",
                        "position": "before"
                    },
                    {
                        "pattern": "core/**",
                        "group": "internal",
                        "position": "before"
                    },
                    {
                        "pattern": "config/**",
                        "group": "internal",
                        "position": "before"
                    },
                    {
                        "pattern": "inject!*/**",
                        "group": "internal",
                        "position": "after"
                    },
                    {
                        "pattern": "core-test/**",
                        "group": "internal",
                        "position": "after"
                    },
                    {
                        "pattern": "test/**",
                        "group": "internal",
                        "position": "after"
                    }
                ],
                "newlines-between": "always",
                "alphabetize": {
                    "order": "asc",
                    "caseInsensitive": true
                }
            }
        ]
}

"settings": {
        ...
        "import/resolver": {
            "typescript": {
                "project": [
                    "*/tsconfig.json"
                ]
            }
        }
    },
```
```
// core/tsconfig.json, other tsconfigs are similar

{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "core-config/*": [
                "../core/config/*"
            ],
            "core/*": [
              "../core/src/*"
            ]
        }
    },
    "include": [
        "../core/src/**/*",
        "../core/config/**/*",
        "../core/typings/**/*"
    ]
}

```
So my example is
```
import Popup from 'core/popups/Popup';
import Interceptor from 'core/routers/interceptors/Interceptor';
import Router from 'core/routers/Router';

import 'core/plan/SomeManager';

import 'core/steps/some-step/SomeStep';
import 'core/steps/another-step/AnotherStep';

import 'core/popups/Popup1';
import 'core/popups/Popup2';

import 'core/controllers/Controller1';
import 'core/controllers/popups/PopupController';

import 'core/service/SomeService';
```
So I wonder why eslint argues only about first 3 rows if anything wrong, other stuff just ignores.
Interesting note, I tried to debug it a bit and all that modules are correctly detected as "internal" modules.
It quite looks like this plugin doesn't support such case

**UPD.** The example above is expected to be like below, but linter doesn't argue it
```
import 'core/controllers/Controller1';
import 'core/controllers/popups/PopupController';
import 'core/plan/SomeManager';
import Popup from 'core/popups/Popup';
import 'core/popups/Popup1';
import 'core/popups/Popup2';
import Interceptor from 'core/routers/interceptors/Interceptor';
import Router from 'core/routers/Router';
import 'core/service/SomeService';
import 'core/steps/another-step/AnotherStep';
import 'core/steps/some-step/SomeStep';
```

**Comment by ljharb** [comment]
I'm really not sure what you're referring to. Can you provide the error output you're getting, versus what you expect?

**Comment by IlyaSavich** [comment]
@ljharb sorry, posted update

**Comment by ljharb** [comment]
I'm not sure what the issue is, but I'll be happy to review a PR.

If a PR can be opened that adds failing test cases that would help as well.

**Comment by evenfrost** [comment]
The issue describes the case with the `import/order` rule, when, if you import an entire module, e.g.
```ts
import '@/views/Settings/Settings.pcss';
```
the rule won't work compared to the case when you import a named/partial module with a `from` statement, e.g.
```ts
import styles from '@/views/Settings/Settings.pcss';
```
In this case, the `import/order` rule will work as expected.

**Comment by ljharb** [comment]
@evenfrost this is by design - that's not "importing the entire module", that's "evaluating it for side effects" - and as such, its order can *never* be safely changed programmatically.

"Importing the entire module" would be `import * as something from 'specifier'`.

**Comment by evenfrost** [comment]
Let's put the wording aside as this is rather irrelevant here. Sorry if I confused you with it but glad you understood my example.

As for the rule itself, I don't quite understand what you mean by "can never be safely changed programmatically", but I believe this one should support any import notation — including "importing the entire module", "evaluating it for side effects" etc. There are definitely cases where you should want to use `import 'something'` notation, like, in my case, importing scoped CSS with [`babel-plugin-react-css-modules`](https://github.com/gajus/babel-plugin-react-css-modules).

**Comment by ljharb** [comment]
It’s fine to use the notation - but it’s impossible to know if changing the ordering of a side-effecting import with respect to other imports that may implicitly depend on it will break code or not.

**Comment by JounQin** [comment]
`import 'x'` can have side effects, so the order can not be changed in many cases AFAIK.
