### ISSUE TITLE
Definition for rule 'import/no-extraneous-dependencies' was not found

### ISSUE THREAD

**Issue by vladkasianenko** [import-js/eslint-plugin-import#2019]
Hello.

I have this rule in my `.eslintrc.json`:

``` json
"import/no-extraneous-dependencies": [
          "warn",
          {
            "devDependencies": false,
            "optionalDependencies": false,
            "peerDependencies": false,
            "bundleDependencies": false,
            "packageDir": "./"
          }
        ]
```

But for a few files I have an error:
```
C:\Users\vlad\source\repos\project_name\src\environments\environment.ts
  1:1  error  Definition for rule 'import/no-extraneous-dependencies' was not found  import/no-extraneous-dependencies
```

Here's file:
``` ts
export const environment = {
  production: false,
  hmr: true,
  var1: "val1",
  var2: "val2",
  varn: "varn"
};

```

It's not only for the env.file, but also for the files with just functions and even for some Angular components where I have a lot of `import {} from ''`. Everytime it fails on the first line, first symbol. Looks like this rule is just not working.

``` json
    "@angular-eslint/builder": "^2.0.2",
    "@angular-eslint/eslint-plugin": "2.0.2",
    "@angular-eslint/eslint-plugin-template": "^2.0.2",
    "@angular-eslint/schematics": "2.0.2",
    "@angular-eslint/template-parser": "2.0.2",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.23.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsdoc": "^32.3.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-sonarjs": "^0.6.0",
```

**Comment by ljharb** [comment]
I have no idea why this is happening for you - in which directory is package.json and node_modules and your eslint config?

**Comment by efilibaas** [comment]
Try close and reopen your editor.

**Comment by hippo-guy** [comment]
Any resolution on this? running into the same thing.

**Comment by ljharb** [comment]
@hippo-guy can you provide all the info in the OP, and also that i requested above? without the ability to repro, no resolution is possible.

**Comment by adred** [comment]
@ljharb Here's a sample project that reproduces the problem. Only difference is `import/no-extraneous-dependencies` rule is not set in `eslintrc`

[https://github.com/adred/import-no-extraneous-dependencies](url)

**Comment by ljharb** [comment]
@adred `yarn eslint .` seems to pass there (i'm not 100% sure since it's using yarn instead of npm).

**Comment by AnthonyLzq** [comment]
I had the same issue, but in my case I forgot to extend the plugin in my `eslintrc` file, hope it helps.

**Comment by leotm** [comment]
Ran into this too ^ upgrading _eslint_ v7.32.0 -> v8.9.0

Both [extends and manual config](https://github.com/import-js/eslint-plugin-import#installation) `Failed to load plugin 'import' declared in '.eslintrc.js'`, which easily fixed/resolved by upgrading _eslint-plugin-import_ from v2.24.2 -> v2.25.4.

**Comment by karolyi** [comment]
This keeps happening to me even after a complete node_modules reinstall AND using 2.25.4

**Comment by leotm** [comment]
@karolyi u got a repo to peek at, or could paste the offending eslint.rc/es.eslintrc.js to a gist

no guarantees tho 😅

**Comment by jscholar** [comment]
Is the "import" plugin specified in your `eslint.config.js`?

```
module.exports = {
  plugins: ['import'],
  rules: {
    'import/no-extraneous-dependencies': ['error'],
  },
};

**Comment by ChiefBK** [comment]
> Try close and reopen your editor.

This did the trick with Webstorm :)
