### ISSUE TITLE
Import rule import/extensions complaining on custom path (typescript config)

### ISSUE THREAD

**Issue by SimonSimCity** [import-js/eslint-plugin-import#2020]
The import rule `import/extensions` seems not to work on import definitions using a custom path provided by `tsconfig.json` (https://www.typescriptlang.org/tsconfig#paths).

It complains that an extension should be given even though it works when using the relative import.

**Comment by ljharb** [comment]
Are you using the typescript-eslint resolver?

**Comment by ljharb** [comment]
Closing, but happy to reopen if you are using that resolver.
