### ISSUE TITLE
`import/no-internal-modules` forbid option no working

### ISSUE THREAD

**Issue by RomainGaillard33** [import-js/eslint-plugin-import#2082]
Hello, 

I wanted to test the new forbid option for the no-import-modules rule but this one doesn't seem to work.
Here is part of my config : 

`
{
  "plugins": ["import"],
  "rules": {
    "import/no-internal-modules": [
      "error",
      {
        "forbid": ["**/modules/*"]
      }
    ]
  }
}
`

And the error : 
`
Error: .eslintrc:
	Configuration for rule "import/no-internal-modules" is invalid:
	Value {"forbid":["**/modules/*"]} should NOT have additional properties.
`

😥 Thank you.

**Comment by ljharb** [comment]
Are you sure you have v2.23.2 installed?

**Comment by RomainGaillard33** [comment]
Yes.  I'm sure. Why it's work for you ? 

My yarn.lock :

`eslint-plugin-import@^2.22.1, eslint-plugin-import@^2.23.2, eslint-plugin-import@^2.8.0:
  version "2.23.2"
  resolved "http://tfsdropserver:8082/repository/npm-group/eslint-plugin-import/-/eslint-plugin-import-2.23.2.tgz#ee15dd68fc7a1a1ba4c653c734e0d01c100d3484"
  integrity sha512-LmNoRptHBxOP+nb0PIKz1y6OSzCJlB+0g0IGS3XV4KaKk2q4szqQ6s6F1utVf5ZRkxk/QOTjdxe7v4VjS99Bsg==
  dependencies:
    array-includes "^3.1.3"
    array.prototype.flat "^1.2.4"
    contains-path "^1.0.0"
    debug "^2.6.9"
    doctrine "^2.1.0"
    eslint-import-resolver-node "^0.3.4"
    eslint-module-utils "^2.6.1"
    find-up "^2.0.0"
    has "^1.0.3"
    is-core-module "^2.4.0"
    minimatch "^3.0.4"
    object.values "^1.1.3"
    pkg-up "^2.0.0"
    read-pkg-up "^3.0.0"
    resolve "^1.20.0"
    tsconfig-paths "^3.9.0"
`

A i have checked in the nodes_modules installed too. It's 2.23.2 !

**Comment by ljharb** [comment]
Yes, it works in our tests - however, it might be an issue with publishing that version. Can you try v2.23.3?

**Comment by RomainGaillard33** [comment]
Version **2.23.4** is still KO. =/

**Comment by ljharb** [comment]
@RomainGaillard33 what is "KO"?

Can you set up a repro repo? Since our tests are passing, that strongly suggests a local issue - perhaps you're running a global eslint (if so, uninstall that; it should only ever be local)?

**Comment by RomainGaillard33** [comment]
> @RomainGaillard33 what is "KO"?
> 
> Can you set up a repro repo? Since our tests are passing, that strongly suggests a local issue - perhaps you're running a global eslint (if so, uninstall that; it should only ever be local)?

I just initiated a new react app with react-create-app.
And I extracted the eslint config into an .eslintrc file.
https://github.com/RomainGaillard33/eslintPluginImport 

It still does not work and yet I have nothing to install globally. 😐

**Comment by RomainGaillard33** [comment]
Any news from a fix please ?

**Comment by ljharb** [comment]
@RomainGaillard33 I've checked out your repo, but when i `yarn install`, both `npx eslint .` and `yarn eslint .` say `Error: Failed to load parser '@typescript-eslint/parser'`.

When I `npm install`, both `npx eslint .` and `yarn eslint .` say `Resolve error: unable to load resolver "alias"`.

Can you fix the repo so it actually demonstrates the issue?

**Comment by RomainGaillard33** [comment]
> @RomainGaillard33 I've checked out your repo, but when i `yarn install`, both `npx eslint .` and `yarn eslint .` say `Error: Failed to load parser '@typescript-eslint/parser'`.
> 
> When I `npm install`, both `npx eslint .` and `yarn eslint .` say `Resolve error: unable to load resolver "alias"`.
> 
> Can you fix the repo so it actually demonstrates the issue?

Yes sorry i forget add eslint-import-resolver-alias dependencies. 
But today I see that it works on my test repo in fact...  😅
And it also works on my real repo. 😱🤔🤯
I don't know what has changed between June and today, but that's okay! Thank you for your help. 😉
