### ISSUE TITLE
Extending "plugin:import/typescript" turns off create-react-app's typescript overrides

### ISSUE THREAD

**Issue by jdgarcia** [import-js/eslint-plugin-import#2107]
So I wasn't really sure whether I should create this issue here, in the create-react-app repo or the airbnb repo, but here's my issue. Hopefully someone can help.

I am using a Create React App (4.x) with Typescript.

I have an `.eslintrc` file that extends `['react-app', 'airbnb', 'plugin:import/typescript']`. Airbnb enables `import/no-unresolved`, which by default doesn't support .ts(x) files.  When I don't extend `plugin:import/typescript`, I get a ton of `import/no-unresolved` errors. But when I do extend it, it seems to solve _that_ issue but also seems to turn off everything listed in [this file's overrides](https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js).

Copy/pasting those overrides into my own eslintrc "fixes it", but that seems like a bandaid to the actual issue.

**Comment by ljharb** [comment]
You need to configure this plugin in your eslint config to recognize `tsx` - which is what https://github.com/benmosher/eslint-plugin-import/blob/HEAD/config/typescript.js should be doing. That should only turn off `import/named`, however.

**Comment by JounQin** [comment]
This is a usage question instead of an issue.
