### ISSUE TITLE
[feature][typescript] enforce import type when imported elems only used as types

### ISSUE THREAD

**Issue by alanszp** [import-js/eslint-plugin-import#2126]
Would love to configure in my typescript projects a rule like this:

This makes an lint error on line 1, because SomeClass is only used as a type. 
```typescript
import {SomeClass} from "../a/package"

export function myFunction(someClass: SomeClass) {
   return someClass.prop;
}
``` 

So the correct code would be:
```typescript
import type {SomeClass} from "../a/package"

export function myFunction(someClass: SomeClass) {
   return someClass.prop;
}
``` 

## Motivation

When using typescript many times you have to import modules between each other just for the types (no real dep) but that makes a lint error: `import/no-cycle`

The fix for that is to mark those imports as types.

So an autofixer for this rule would be great!

## Thoughts about this rule

My goal with this is to autofix the imports that are cyclical but are safe (because only uses types).

My main concern about this rule is that in some cases, changing it to `import type` will make webpack to not include that file in the final compilation, so the autofix will not be safe to use in every project.

But wanted to post it anyways so we can discuss it

Thanks!

**Comment by ljharb** [comment]
That sounds great, but is type-system-specific, so it may be a better fit for typescript-eslint’s plugin.

**Comment by TheAkio** [comment]
This may be what you are looking for: https://github.com/typescript-eslint/typescript-eslint/blob/13d0a4c4f950920fd73e68d4aacbae8018b8721c/packages/eslint-plugin/docs/rules/consistent-type-imports.md

Looks to me as there is no need to add such a rule to this project.
