### ISSUE TITLE
[Feature request] Support a 'depth' option for no-relative-parent-imports

### ISSUE THREAD

**Issue by Slapbox** [import-js/eslint-plugin-import#2133]
I find the `no-relative-parent-imports` rule to be very useful, but perhaps a bit too stringent. There's enough cases where reaching up one level makes more sense than creating a new package - but too many for it to make sense to add `eslint-disable-line import/no-relative-parent-imports` to all the exceptions.

I think it would be enormously helpful if this rule had an option to allow `../`, but disallow `../../` and so on. Reaching up one level is quite common and not always a bad practice, but once you get to reaching up two and three levels, that's a code smell for sure.

**Comment by ljharb** [comment]
Once you can reach up one level, you can make a chain of "reach up one level" and easily get to more than one. I don't think there are that many cases where it makes sense to reach up even one level.

**Comment by Slapbox** [comment]
> Once you can reach up one level, you can make a chain of "reach up one level" and easily get to more than one.

Fair concern, but I don't think that it necessarily makes this request pointless.

I really have to disagree about reaching up one level though. What if we have some utility that we use in `foo/bar` and in `foo/bar/baz` we also need that utility. I'm all for moving things to packages to maintain a more tree-like project structure, but this is the kind of thing that, when taken to the logical extreme, can result in dozens of packages that work around just a couple dozen cases of `import { something{ from `'../utils'`.

In my studying of a number open source repos while determining which rules were worth our time, I found a number of them relied on relative parent imports, even when they had a monorepo. I think you'd be harder pressed to find a substantial codebase entirely devoid of relative parent imports.

**Examples:**

- https://github.com/palantir/blueprint/tree/develop/packages/core/src (used extensively)
- https://github.com/ianstormtaylor/slate/tree/main/packages/slate-react/src  (used extensively)
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/handlers/plugin.ts#L2  (used sparingly)

Could Gatsby move their `reporter` into its own package in their monorepo? Yeah definitely, but to avoid a single line of `'../reporter'` - it may not necessarily make sense in real life even if it does on paper; only the maintainers are going to understand why that choice was made.

Or could Slate move the `components`, `hooks`, `plugins`, and `utils` all into their own packages? Sure - but this is a perfect example of how quickly this can get unwieldy. There is some developer time cost involved in creating those additional packages which can definitely outweigh the benefits of doing so in this case.

I feel like this is the kind of rule that could be more helpful if it were more configurable - especially since the current "all of nothing" configuration precludes the possibility of fixing the issues that already exist over time. If there were a way to limit levels you could reach, then a project that already has issues flagged could potentially be fixed over time by reducing the maximum allowable parent levels, with a default of zero.

**Comment by ljharb** [comment]
Dozens of packages sounds great to me - the more the better. It almost always makes sense to extract something to a small package.

In small packages, I think this rule provides much less value - relative imports are fine there. In a monorepo or larger packages tho, I think it's exceedingly important to avoid them.

**Comment by Slapbox** [comment]
Agh I'm inclined to agree now, two months later, but at the same time the rule does still seem limiting. It's easy to find fault though and I can't suggest any better option than what already exists.

The overhead of creating so many packages for one or two is just a huge pain. Maybe in some months there will be a popular tool to help eliminate that overhead. That's the best hope for this, I think.
