### ISSUE TITLE
eslintimport/no-extraneous-dependencies Issue

### ISSUE THREAD

**Issue by AakashAlagarsamy** [import-js/eslint-plugin-import#2148]
I'm using eslint 7.29.0
Same error is showing

'webpack-merge' should be listed in the project's dependencies, not devDependencies.eslintimport/no-extraneous-dependencies
'webpack' should be listed in the project's dependencies, not devDependencies.eslintimport/no-extraneous-dependencies

My file is below

**development.config.js**
```
const { merge } = require('webpack-merge');
const webpack = require('webpack');
```

**package.json**

```
"devDependencies": {
    "eslint-plugin-import": "^2.23.4",
    "webpack": "^5.41.1",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.8.0"
  },
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  }
```

_Originally posted by @AakashAlagarsamy in https://github.com/benmosher/eslint-plugin-import/issues/1396#issuecomment-877382574_

**Comment by ljharb** [comment]
What is your eslint config? By default everything is assumed to disallow dev deps.
