### ISSUE TITLE
Legacy dependencies causing warnings for vulnerability.

### ISSUE THREAD

**Issue by sandeshvijayraj** [import-js/eslint-plugin-import#2169]
There seem to be some legacy libraries getting used in the dependency definition. One such example is Debug <4.0 all debugger versions less than 4 are detected as vulnerable but are still being used in this project.

**Comment by ljharb** [comment]
Duplicate of #1892.

The reason is because:
 a) debug 4 drops support for node versions we must support
 b) the vulnerabilities, like most in the JS ecosystem, are a false positive, and are non-issues for the manner in which this package uses `debug`.
