### ISSUE TITLE
Alias not working when have `settings.node.tryExtensions`

### ISSUE THREAD

**Issue by linonetwo** [import-js/eslint-plugin-import#2171]
Have alias setting:

```js
  settings: {
    react: {
      version: '17.0.2',
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
      typescript: {
        alwaysTryTypes: true,
      },
      alias: {
        map: [
          ['@', './src'],
          ['@services', './src/Background/services'],
          ['@pages', './src/ContentScript/pages'],
        ],
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
  rules: {
```

Got:
 
```js
Unable to resolve path to module '@services/bindServiceAndProxy'.eslintimport/no-unresolved
```

<img width="1163" alt="截屏2021-08-01 下午4 04 13" src="https://user-images.githubusercontent.com/3746270/127763997-86f02f72-ff9e-45b9-ae75-cf29617f63a4.png">

When have:

```
  settings: {
    node: {
      tryExtensions: ['.js', '.jsx', '.ts', '.tsx']
    },
  },
```

<img width="1351" alt="截屏2021-08-01 下午4 01 36" src="https://user-images.githubusercontent.com/3746270/127763921-45248e9a-0b94-41bf-9378-6863236de854.png">

## Solution

If remove these lines, then the alias will work.

**Comment by YuanRuQian** [comment]
I guess that this is about the `@services/bindServiceAndProxy` module's extension?

According to https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-import.md#tryextensions

<img width="1190" alt="Screen Shot 2021-08-01 at 18 01 09" src="https://user-images.githubusercontent.com/32387159/127766991-4aa6fcc1-7c71-4af4-b3e7-5697e9d49866.png">

default `tryExtensions` includes `.json` and `.node`

If you remove `tryExtensions: ['.js', '.jsx', '.ts', '.tsx']` and it works, it might be that `@services/bindServiceAndProxy` is `.json` or `.node` file ?

Cloud you check the file extension of the `@services/bindServiceAndProxy` module?

**Comment by linonetwo** [comment]
No， actually it is just .ts file... So this is pretty weird.

**Comment by ljharb** [comment]
A repro repo would be most helpful.

**Comment by JounQin** [comment]
`typescript` should come before `node`.
