### ISSUE TITLE
[no-extraneous-dependencies] feat: path mapping support for alias

### ISSUE THREAD

**Issue by JounQin** [import-js/eslint-plugin-import#2204]
We're using `lodash: 'lodash-es'` mapping in our `vite.config.ts`.

So we install `lodash-es` as `dependencies` rather than `lodash`.

**Comment by ljharb** [comment]
You’ll have to configure eslint so the plugin knows about it too, since vite’s config isn’t something eslint knows about.

**Comment by JounQin** [comment]
> You’ll have to configure eslint so the plugin knows about it too, since vite’s config isn’t something eslint knows about.

@ljharb 

Yeah, I know, but there is no configuration for `no-extraneous-dependencies`.

**Comment by JounQin** [comment]
Besides, if we have a path mapping like `lodash: 'lodash-es'`, `lodash` should be always preferred.

**Comment by ljharb** [comment]
There’s configurable resolvers. That’s what tells every rule to remap one thing to another.

**Comment by JounQin** [comment]
> There’s configurable resolvers. That’s what tells every rule to remap one thing to another.

OK, I'll try it locally.

**Comment by JounQin** [comment]
It seems `eslint-import-resolver-typescript` should be updated then. `paths` in `tsconfig.json` should be resolved first.
