### ISSUE TITLE
Import order of groups messed up

### ISSUE THREAD

**Issue by a-tonchev** [import-js/eslint-plugin-import#2224]
I have following eslint rules:

```JS
   "import/order": ["error", {
      "newlines-between": "always",
      "groups": [["builtin", "external"], "internal", ["index", "parent", "sibling"]],
      "pathGroups": [
        {
          "pattern": "@/",
          "group": "internal",
          "position": "after"
        }
      ]
    }]
```

This requires following order:
```
import ExternalPackage from 'somewhere';

import InternalPackage from '@/components/SomeLocalModule';

import Sibling from './SomeModule';
```

Until version 2.23.4 everything works fine. But after that the order of the sibling and the internal package "@/components" is mixed up, the plugin requires me to switch the places of the Sibling and the @/ package.

**Comment by amritk** [comment]
+1!!! Just upgraded then had to downgrade this plugin unfortunately. It renders it unusable.
