### ISSUE TITLE
Using eslint-plugin-import in a monorepo

### ISSUE THREAD

**Issue by cmdcolin** [import-js/eslint-plugin-import#2247]
Hi there
I was wondering if there is any way I can use eslint-plugin-import to catch errors from bad imports in a monorepo

I noticed if I have a monorepo setup like this

- `packages/app1` has `is-even` in it's `package.json`
- `packages/app2` does not have `is-even` in its `package.json`
- `packages/app2` tries to use `is-even`

I'd like to get a warning from packages/app2's bad usage of is-even, but I don't get this

I made a  small reproducible repo here https://github.com/cmdcolin/yarn_workspaces_eslint_plugin_import (run yarn && yarn lint from root of the repo) and there are no warnings from lint, though it would be cool to see if I can get warnings from this...

Note: I tried cross-posting this to stackoverflow too

https://stackoverflow.com/questions/69457844/using-eslint-plugin-import-in-a-monorepo-not-reporting-errors-when-it-should

**Comment by cmdcolin** [comment]
will close for now as I think this is effectively solved, thanks!

**Comment by cmdcolin** [comment]
I meant, is it not part of `plugin:import/recommended`?
my small demo repo only had that enabled and it didn't catch the error but manually adding the import/no-extraneous-dependencies did fix

**Comment by ljharb** [comment]
I don't believe it is, no. I'd suggest using the airbnb config :-)

we can't update the recommended config without a major bump, so it's quite behind.
