### ISSUE TITLE
eslint-plugin-import does not support eslint 8 yet

### ISSUE THREAD

**Issue by miladezzat** [import-js/eslint-plugin-import#2252]
## Environment Info:

Node version: v14.17.6
npm version: v8.0.0
Local ESLint version: v8.0.0 (Currently used)
Global ESLint version: v8.0.0
Operating System: linux 5.13.19-200.fc34.x86_64

```bash
Oops! Something went wrong! :(

ESLint: 8.0.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in /home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:43:34)
    at Module._compile (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

**Comment by ljharb** [comment]
Yes, it should have.

Either way, eslint-plugin-import supports eslint 8 now, so you shouldn’t have any issues.

**Comment by BeAmazedVariable** [comment]
@ljharb I just try and it did work out. Thank you so much for your instruction

**Comment by morijenab** [comment]
The same problem :
1- update eslint-plugin-import": "^2.25.2"
2- update "eslint": "^8.1.0",
node -v   v14.17.5
 
eslint config 
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier",
        "plugin:jsx-a11y/recommended",
        "react-app",
        "eslint-config-prettier"
    ],
    "parser": "@typescript-eslint/parser",
    "plugins": ["@typescript-eslint", "prettier", "jsx-a11y"],

ran to this error : Package subpath './lib/rules/no-unused-expressions' is not defined by "exports

**Comment by ljharb** [comment]
@morijenab that's because the jsx-a11y plugin doesn't support eslint 8 yet.

You won't be able to update until *everything* you depend on supports it.

**Comment by Maxeeezy** [comment]
Still facing same issue here. Try to install newest version 2.25.2 and get the warnings

**Comment by Maxeeezy** [comment]
I get this:

`npm install eslint-plugin-import@2.22.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-import@2.22.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`

Does the version not exist anymore?

**Comment by JannikZed** [comment]
we are facing the same issue - using eslint-plugin-import@2.24.2 and eslint 8.15.0 .. could somebody explain this issue to us better and re-open this issue?

**Comment by ljharb** [comment]
@JannikZed the issue is you’re using an outdated version of the plugin. Update it to the latest. There’s nothing left to fix, and no need to reopen.

**Comment by ChrisIT9** [comment]
Issue still present with 2.26.0
