### ISSUE TITLE
Allow cyclic dependencies for `import/no-cycle` iff mixing static/dynamic imports

### ISSUE THREAD

**Issue by D-Pow** [import-js/eslint-plugin-import#2265]
## Request

Add a new option for `import/no-cycle` to allow/warn/error about cyclic dependencies if, and only if, the cycle involves dynamic imports.

## Problem Statement

There exists a use case for web apps where some modules are stored in a form of global state and then other modules import that state to update it. For example, an (overly simplistic/half-pseudo code) purpose for this might look something like:

```javascript
// state.js
import Comp1 from './Comp1';
import Comp2 from './Comp2';
import Comp3 from './Comp3';

const routeModuleMap = {
    '/path1': Comp1,
    '/path2': Comp2,
    '/path3': Comp3,
};

const routeOrder = [
    '/path1',
    '/path2',
    '/path3',
];

let state = 0;

export function getActiveModule() {
    return routeModuleMap[location.pathname];
}

export function setActiveModule(dx = 1) {
    if (dx === 0) {
        return;
    }

    if (dx < 0) {
        state = Math.max(0, state + dx);
    }

    if (dx > 0) {
        state = Math.min(routeOrder.length - 1, state + dx);
    }

    history.pushState(null, null, routeOrder[state]);
}

export default const Context = React.createContext({ getActiveModule, setActiveModule });


// parent.jsx
import Context, { getActiveModule, setActiveModule } from './state';

export default function App() {
    const Component = getActiveModule();

    return (
        <Context.Provider value={{ getActiveModule, setActiveModule }}>
            <Component />
        </Context.Provider>
    );
}


// Comp1.jsx
import Context from './state';

export default Comp1() {
    const { setActiveModule } = useContext(Context);

    return (
        <button onClick={() => setActiveModule()}>
            Go to next page
        </button>
    );
}
```

Obviously this has a circular dependency, so when bundled, it might result in `CompN is not defined` errors.
However, that can easily be resolved by mixing static and dynamic imports, which return promises instead of the code itself. This means that all files are parsed/run _before_ any promises resolve, meaning that we never have `X is not defined` errors.

i.e.

```javascript
// old
import Comp1 from './Comp1';
import Comp2 from './Comp2';
import Comp3 from './Comp3';

const routeModuleMap = {
    '/path1': Comp1,
    '/path2': Comp2,
    '/path3': Comp3,
};


// new
const routeModuleMap = {
    '/path1': React.lazy(() => import('./Comp1')),
    '/path2': React.lazy(() => import('./Comp2')),
    '/path3': React.lazy(() => import('./Comp3')),
};
```

While this is a very simple and contrived example, there are cases where some sort of global state links to modules, and each module needs to modify that global state. In these cases, mixing static with dynamic imports solves the problem of code not being defined because your bundler of choice converts `A --> B --> A` to `A --> B --> Promise.resolve(A)`.

Of course, having circular dependencies in your code is an anti-pattern and reflects brittle code that should still be refactored. This is a great plugin/rule to do exactly that: fix old code and guide new code standards.
But for gigantic repositories, those can't all be fixed at once, especially when the code is in more complex global state. For those specific situations, it'd be really helpful to be able to toggle dynamic-import-cycles using dynamic imports from allow --> warn --> error gradually as they are addressed.
This would mean **errors are still shown** for static import cycles, protecting new code while old code is refactored.

**Comment by ljharb** [comment]
(for future reference, emoji-reacting to your own comment is pretty strange)

I'm not sure exactly what you're asking. You want an option so cycles are not tracked through dynamic import entry points?

In general, the transition path for all rules for a large legacy codebase is "eslint overrides", not "add config options to rules".

**Comment by D-Pow** [comment]
I did look into overrides, but those are usually for specific files, not specific uses. And we generally want the `import/no-cycle` rule to error at all times, it's just that cyclic dependencies when using dynamic imports technically doesn't make the code nearly as fragile as when the cycles use static imports. (Again, cycles _should_ be removed, but at least dynamic imports makes them not crash the whole app.)

The request for a new option to the rule was for that case: We want all static import cycles to error and all dynamic import cycles to warn.

**Comment by ljharb** [comment]
@arpowers is your use case the same (where you intentionally used dynamic imports to hack around this plugin's incorrect behavior of ignoring them), or do you have a different use case where these cycles aren't actually a problem?

**Comment by ljharb** [comment]
Sure, but it's still a cycle - you're still importing something from a file that itself depends on that file. Circular deps "work fine" with static imports too - the issue isn't that it doesn't work, it's that it's an inherently unmaintainable and poorly designed application architecture.

**Comment by D-Pow** [comment]
Don't get me wrong, I do believe that the cons outweigh the pros in every situation. But I wasn't going to claim it as an absolute truth because it's virtually impossible to prove it; e.g. Idk what @arpowers design is (not trying to ask what it is, mind you, just as an example), but maybe there exists some case in some world where they're acceptable. But let's not beat this dead horse too much longer, I think we've covered the conceptual portion enough.

Regardless, I think this entire discussion can be summed up as:

1. Cyclic dependencies are bad.
2. "Bad" is a spectrum -- in high level terms/not related to cyclic deps: breaking the app is the worst and somewhat unclean code is one of the least.
3. People want to use this plugin to help remove cyclic deps.
4. Since dynamic imports are "bad" but not "breaking-the-app bad," an option should be added until the dynamic import cycles can be removed because they exist on different levels of "bad."

Anyway, @ljharb you said you'd consider it, so the ball's in your court. Thanks for your time and discussion. Let's leave this issue open until a decision and/or fix is made.

**Comment by AdrienLemaire** [comment]
Yes, there shouldn't be any cycle dependencies when a module is dynamically loaded from a callback.
I'm also using that pattern to lazy-load pages with react-router.

To get eslint to ignore these, I had to replace my imports with a wrapper function

```ts
const importWithoutCycle = (path: string) => import(path);
```

**Comment by Anber** [comment]
Completely agree with @arpowers. We also use dynamic imports in callbacks for referring states in the router. It doesn't cause actual circular reference but it allows us to use strictly typed links and check on compile-time that referred state exists. And I don't see any downsides here.

**Comment by ljharb** [comment]
All of these are still conceptually circular dependencies. That's the downside, and it remains for every provided use case because cycles are bad architecture, harder to maintain, etc.

I do hear that there are a number of use cases, and that drawing a line between "all imports" and "only static imports" may be useful *despite* the inherent downsides. I'm still evaluating that.

**Comment by GerkinDev** [comment]
My 2 (useless) cents on this: this should be configurable IMHO. Even if they are dangerous, they can be used carefully.

**Comment by GerkinDev** [comment]
Well, I'm willing to give it a try! I'm super confused by some parts of the project, and I've never really touched typescript ast-related code, but hey, there's a first to everything!

**Comment by GerkinDev** [comment]
Thank you for the merge!
