### ISSUE TITLE
import/no-unresolved if add new alias path

### ISSUE THREAD

**Issue by WxSwen** [import-js/eslint-plugin-import#2278]
When i add a new alias path in tsconfig，others pull my code and restart will found this error:  import/no-unresolved。

And he should open the file in project and save again。It will be solved，so i think it will be a eslint cache problem?

Please tell me how to solve this error，thanks。

**Comment by Oliver84** [comment]
I'm seeing this in our Bitbucket Pipelines. Just started seeing this with new builds

**Comment by Oliver84** [comment]
Sorry, I thought it was a related issue but I can file a new one for this. I'm seeing the same error with 2.25 but I'm not adding a new alias to tsconfig. Just added a new import to a regular jsx file and I'm getting:

`Unable to resolve path to module 'react-toastify/esm/react-toastify'. [Error/import/no-unresolved]
1 problemerror: 'eslint' errored after 12s
{
  "data": {
    "message": "Failed with 1 error",
    "name": "ESLintError"
  }
}
npm ERR! Test failed.  See above for more details.`

**Comment by ljharb** [comment]
I’m on mobile rn so i can’t check, but my guess is that that package doesn’t support CJS - ie, it lacks a main and relies on “exports”. If so, this plugin (like much of the ecosystem) doesn’t support that yet, and you’ll have to use import/ignore for it.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript
