### ISSUE TITLE
import/extensions enhancement

### ISSUE THREAD

**Issue by UltiRequiem** [import-js/eslint-plugin-import#2286]
It would be nice if there was an option to ignore directories, so this would be possible:

![image](https://user-images.githubusercontent.com/71897736/140204713-3533e85a-6526-4d24-9cdf-82eaa3d79ebd.png)

https://github.com/import-js/eslint-plugin-import/blob/v2.25.2/docs/rules/extensions.md

It should be something like `ignoreDirectories` following:
```javascript
module.exports = {
rules:{
    'import/extensions': ['error', 'always', { ignorePackages: true }],
  }
}

**Comment by ljharb** [comment]
I'm not sure what you mean. You want to configure the rule to require extensions (the best practice is to omit them) but you want to omit them when requiring a directory?

**Comment by UltiRequiem** [comment]
Yes

**Comment by ljharb** [comment]
Can you help me understand why? Every argument I’ve heard for including extensions is either about explicitness (which applies to directories too) or about native node ESM requiring extensions (which applies to directories too).

**Comment by UltiRequiem** [comment]
I'm working in a project using [Next.js](https://nextjs.org), where I can use the ESM syntax but also the Node.js shortcuts like the `index.js` file or not using extensions.

For explicitness it seems fine to me to use file extensions, but it seems too long to have to:

```javascript
import {something} from '../../directory/index.js`
```

In this case I would like to be able to skip it.

**Comment by ljharb** [comment]
If explicitness is important, it's more important than length; if length is important, it's far better to omit the extensions everywhere. I'm not hearing a compelling argument for adding this complexity to the plugin.

**Comment by UltiRequiem** [comment]
I don't think there is a good argument to add it, even so I would like to have the option.

If you don't want to add it, I understand, thanks for your work on this plugin.

**Comment by ljharb** [comment]
I think that it's far better to be consistent - if there's any dynamic lookup, you should be benefiting from it as much as possible; otherwise you should be explicit in every case.

You could certainly make your own eslint rule that does what you want, but I think for now we won't be including it here.
