### ISSUE TITLE
`import/no-unresolved` unable to resolve in a monorepo with path mapping

### ISSUE THREAD

**Issue by HaveSpacesuit** [import-js/eslint-plugin-import#2301]
I'm trying to set up [path-mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) in a mono-repo. It is working fine, but the import/no-unresolved rule is unable to resolve the paths. My issue seems very similar to #1485, but I already have the `eslint-import-resolver-typescript` package installed.

```
app/
├─ package/
│  ├─ src/
│  ├─ tsconfig.json
.eslintrc
tsconfig.json
```

.eslintrc looks like
```json
{
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint",
    "import",
  ],
  "extends": [
    "eslint:recommended",
    "plugin:import/recommended",
    "plugin:import/typescript"
  ],
  "settings": {
    "import/resolver": {
      "typescript": {}
    }
  }
}
```

The inner tsconfig.json looks like:
```json
{
  "extends": "../tsconfig",
  "compilerOptions": {
    "baseUrl": "./src/"
  }
}
```

The paths map just fine, but I have the lint error "Unable to resolve path to module '...'" wherever I try to use the mapped path. I must be missing a configuration step, or maybe there is an issue with using the baseUrl in a nested tsconfig?

**Comment by JounQin** [comment]
You need to config `project` settings for `eslint-import-resolver-typescript`.

The default `project` is only `tsconfig.json` in `cwd`.

**Comment by ljharb** [comment]
You *also* need the `node` resolver, after the typescript one.

**Comment by HaveSpacesuit** [comment]
Thanks! This solves a lot of annoying messages. For anyone who comes after, this is the settings I added; not sure if the project is needed in the node resolver or not.

```json
"settings": {
  "import/parsers": {
    "@typescript-eslint/parser": [".ts", ".tsx"]
  },
  "import/resolver": {
    "typescript": {
      "project": ["tsconfig.json", "package/tsconfig.json"]
    },
    "node": {
      "project": ["tsconfig.json", "package/tsconfig.json"]
    }
  }
}
```

**Comment by JounQin** [comment]
> You _also_ need the `node` resolver, after the typescript one.

Why? I don't think it's needed.

**Comment by ljharb** [comment]
@JounQin i suppose if the TS resolver also covers node resolution, then great, but the intention is that resolvers should stack - the TS resolver should ideally only be handling TS things that the node resolver can't, the webpack resolver only handling webpack things the node resolver can't, etc.

**Comment by JounQin** [comment]
@ljharb I think that is needed, for example `types` field is preferred than `main` or `module` in `package.json` for ts resolver.

**Comment by ljharb** [comment]
@JounQin yes - and the TS resolver should find something when there's a types field, and should find nothing otherwise, thereby deferring to the node resolver.

**Comment by JounQin** [comment]
@ljharb `foo/lib/bar` should prefer `foo/lib/bar.d.ts` even if there is no `types` field for ts resolver, and it already tries `.ts`/`.tsx`/`.d.ts` so it is just easy to try `.js` at the same time, `node` resolution is a part of `typescript` itself IMO.

**Comment by ljharb** [comment]
Sure, that’s all fine. But when there’s no difference between the TS and node resolvers, why would the TS resolver want to duplicate the logic?

**Comment by JounQin** [comment]
The logic has been already there for `types`, `.d.ts`, `.ts`, etc. Then the users would only configure ts resolver, that would be enough, no `node` settings will be needed by default.

**Comment by ljharb** [comment]
What happens when there’s a package with zero type information tho?

**Comment by JounQin** [comment]
> What happens when there’s a package with zero type information tho?

It will continue to work like the node resolver.

**Comment by ljharb** [comment]
Right - which means it has duplicated the logic living in the node resolver. It’s free to do this, of course, but the entire plugins resolver system was designed so resolvers stack.

**Comment by JounQin** [comment]
Again, the logic is already there for typings, there is no need to disable it specially. I believe webpack resolver has same ability too.

**Comment by kylemh** [comment]
I think I see that this issue is basically closed, but JounQin touches on something that I'm wondering as I implement this plugin into a new config/project.

Since the Node logic is already handled by typescript, why not make `'plugin:import/typescript',` do:

```js
"import/resolver": {
  "typescript": {
    "project": "tsconfig.json",
  },
}
```

by default?

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript

**Comment by peter-coastpay-com** [comment]
> eslint-import-resolver-typescript

what file does this go in? im currently facing this issue

**Comment by ljharb** [comment]
@peter-coastpay-com See https://github.com/import-js/eslint-plugin-import#resolvers

**Comment by mirhamasala** [comment]
The proposed solution didn’t work as expected in our case. We had to explicitly add the full path ./apps/site/tsconfig.json to make it work, even though this is the workspace configuration. This behavior feels a bit unusual—did we overlook something? Here’s the relevant section online for reference: https://github.com/FilecoinFoundationWeb/filecoin-foundation/blob/2cab714ea0f982811710e8bf5e6b1cae18acd141/apps/site/.eslintrc.json#L126 🙏🏼

```json
"settings": {
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true,
        "project": ["./apps/site/tsconfig.json", "./cypress/tsconfig.json"]
      }
    }
  }
```
