### ISSUE TITLE
How can i set new line between common import and .css imports?

### ISSUE THREAD

**Issue by 243083df** [import-js/eslint-plugin-import#2309]

**Comment by ljharb** [comment]
You'd use the `order` rule: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

**Comment by 243083df** [comment]
@ljharb But "newlines-between" enforce empty line between each group, i need to maintain order of each group but add new line before ".css" group

**Comment by ljharb** [comment]
Ah. The inconsistency you want isn’t supported at the moment.
