### ISSUE TITLE
Feature Request: Sort import specifiers in import/order rule.

### ISSUE THREAD

**Issue by gluxon** [import-js/eslint-plugin-import#2316]
The [`import/order` rule](https://github.com/import-js/eslint-plugin-import/blob/e15631696440396f39dad6daf99d48f56f7defce/src/rules/order.js#L1) does a great job of sorting import statements. Would it be possible to add support for sorting _specifiers_ on each import statement?

For example, I'm hoping `import/order` can be configured in the future to autofix:

**From**:
```ts
import { b, a } from "foo";
```

**To**:
```ts
import { a, b } from "foo";
```

I'd be willing to help create a PR for this feature if it sounds reasonable. Thanks!

**Comment by ljharb** [comment]
That's not a specifier ("foo" is the specifier), that's the import names themselves.

I believe the core https://eslint.org/docs/rules/sort-imports rule already handles this case?

**Comment by gluxon** [comment]
> That's not a specifier ("foo" is the specifier), that's the import names themselves.

Oh interesting. I was going off of astexplorer.net, which seems to call these `ImportSpecifier` nodes for `typescript` and `@typescript-eslint/parser`.

![Screen Shot 2021-11-30 at 4 04 56 PM](https://user-images.githubusercontent.com/906558/144128061-2022cf01-fc2d-4da9-b620-15ce90215529.png)

> I believe the core https://eslint.org/docs/rules/sort-imports rule already handles this case?

Yes, that looks exactly like what we want. (Down to the example, haha.) Thanks a lot @ljharb. 🙂
