### ISSUE TITLE
Conflict with VSCode's autoImport 

### ISSUE THREAD

**Issue by YangChen00** [import-js/eslint-plugin-import#2322]
while i open the autoImport, the sort result will conflict with the eslint rule

![image](https://user-images.githubusercontent.com/94821645/144959100-98997e5a-749a-4996-b769-3526423740ab.png)

detail in:

- https://github.com/eslint/eslint/issues/15398
- https://github.com/microsoft/vscode/issues/137930

**Comment by ljharb** [comment]
Ok - so disable vscode’s? I usually disable 100% of vscode’s default formatting; that’s what eslint is for.

**Comment by YangChen00** [comment]
> Ok - so disable vscode’s? I usually disable 100% of vscode’s default formatting; that’s what eslint is for.

OK, I think that's ok
