### ISSUE TITLE
Question: No unused imports

### ISSUE THREAD

**Issue by MrSquaare** [import-js/eslint-plugin-import#2324]
Is there any rule to warn and autofix unused imports?

**Fail**
```js
import fs from "fs";
import http from "http";
import { join, basename } from "path";

console.log(fs.readFileSync(join(__dirname, "./file")));
```

**Pass**
```js
import fs from "fs";
import { join } from "path";

console.log(fs.readFileSync(join(__dirname, "./file")));
```

**Comment by ljharb** [comment]
No - duplicate of #1473.

**Comment by andresgutgon** [comment]
@ljharb maybe I'm not understanding but #1473 is talking about "unused exports". 

@MrSquaare is asking (and me too) for "unused imports"

``` ts
import fs from "fs";
import http from "http";
import { join, basename } from "path";

console.log('using fs', fs)
console.log('using join', join)
console.log('using basename', basename)
```

What I would do is to remove `import http from "http";` because it's not used

**Comment by ljharb** [comment]
@andresgutgon the eslint core no-unused-vars rule should already be handling that, I’d expect.

**Comment by bflatmajor** [comment]
I think it's meaningful, `no-unused-vars` is not auto fixable, but a rule like this can be.

**Comment by ljharb** [comment]
@bflatmajor no it can't, for the same reason that rule isn't safely autofixable - the variable name might be unused but the import's side effects might not be.
