### ISSUE TITLE
eslint-plugin-import v2.24.2 not working anymore?

### ISSUE THREAD

**Issue by AyushMittal1999** [import-js/eslint-plugin-import#2350]
From `version 2.25.0` eslint-plugin-import has started identifying cyclic dependency in dynamic imports. But we are having a huge codebase containing some cyclic dependency in dynamic imports. So, till the time we fixed that, we decided to restrict to eslint-plugin-import  `version 2.24.2`.
Using version 2.24.2, we found that it is not working now due to lapse in dependency version of `eslint-module-utils`. Latest version of `eslint-module-utils` (>= `2.7.0`) is not compatible with eslint-plugin-import `v2.24.2`.  But in package.json of eslint-plugin-import `v2.24.2` we are using  `"eslint-module-utils": "^2.6.2"` (https://github.com/import-js/eslint-plugin-import/blob/v2.24.2/package.json#L108).  We need to use `"eslint-module-utils": "2.6.2"` to use v2.24.2.

Please let me know how can we overcome this problem. Can we go for a `v2.24.3` with the required change to support the required feature. Thanks

**Comment by ljharb** [comment]
I'm confused, there doesn't seem to be a bug here.

**Comment by ljharb** [comment]
In what way is `eslint-module-utils` v2.7.0+ incompatible with `eslint-plugin-import` v2.24.2?

If there's a bug here, it'd be in `utils/`, and *not* in the main eslint-plugin-import package.

**Comment by AyushMittal1999** [comment]
Considering this https://github.com/AyushMittal1999/eslint-testing sample repo, eslint-plugin-import is unable to identify cyclic dependency here.
But if I used raised [PR](https://github.com/AyushMittal1999/eslint-plugin-import/tree/eslint-plugin-import-fix-version-2.24.2) branch for eslint-plugin-import i.e.     `"eslint-plugin-import": "github:AyushMittal1999/eslint-plugin-import#fix-version-2.24.2"` it works fine

**Comment by ljharb** [comment]
That an older version of the plugin isn't identifying things that a newer version does isn't a problem.

Are you saying that v2.24 of the plugin with v2.6 of the utils DOES report them, but v2.24 of the plugin with v2.7 of the utils does not?

**Comment by AyushMittal1999** [comment]
Yes I mean,
 v2.24 of the plugin with v2.6 of the utils DOES report cyclic dependencies, but v2.24 of the plugin with v2.7 of the utils does not.

**Comment by ljharb** [comment]
but, v2.25 of the plugin with v2.7 of the utils does?

**Comment by AyushMittal1999** [comment]
yes

**Comment by ljharb** [comment]
Thanks. In that case, we should figure out how to make the latest version of the utils again work with v2.24 as well (not that it's a good idea to stay on a non-latest version of the plugin).

**Comment by ljharb** [comment]
@AyushMittal1999 can you provide a minimal example of something that works in those two combos and fails in that other combo?

**Comment by AyushMittal1999** [comment]
This [example](https://github.com/AyushMittal1999/eslint-testing) is simple only, two files are there a.js, b.js importing and exporting to each other.

In this example v2.24 with utils v2.6
Or v2.25 with utils v2.7 works good. But v2.24 with utils v2.7 fails

**Comment by ljharb** [comment]
Thanks, I'll take a look.

**Comment by AyushMittal1999** [comment]
@ljharb On exploring more in depth, I found out that contract of utils/parse.js has changes in utils v2.7.
Referring to [this](https://github.com/import-js/eslint-plugin-import/blob/main/utils/parse.js#L74), Return type of defaut parse function is as below:
```
      const parserRaw = parser.parseForESLint(content, parserOptions);
      ast = parserRaw.ast;
      return {
        ast,
        visitorKeys: keysFromParser(parserPath, parser, parserRaw),
      };
```
it returns an object that contains ast in a key.
But earlier in v2.6 It was  directly returning ast [refer](https://github.com/import-js/eslint-plugin-import/blob/v2.24.2/utils/parse.js#L61):
```
return parser.parse(content, parserOptions);```
I think this is the reason breaking v2.24.2.

**Comment by AyushMittal1999** [comment]
Hii @ljharb Thanks for the change.
Can you let me know, Are we planning to publish these changes anytime soon?

**Comment by ljharb** [comment]
Yes.
