### ISSUE TITLE
Issue with internal modules recognition for import/order

### ISSUE THREAD

**Issue by vertic4l** [import-js/eslint-plugin-import#2361]
Hi,

i struggle to get the import/order setting right.

The order should be:

syles import
node_modules / "external"
internal
...rest

Here is the import/order rules:

```
"import/order": [
            1,
            {
                "warnOnUnassignedImports": true,
                "groups": [
                    "index",
                    "builtin",
                    "external",
                    "object",
                    "type",
                    "unknown",
                    "internal",
                    "sibling"
                ],
                "pathGroups": [
                    {
                        "pattern": "./*.scss",
                        "patternOptions": { "matchBase": true },
                        "group": "index",
                        "position": "after"
                    }
                ],
                "alphabetize": { "order": "asc", "caseInsensitive": true }
            }
        ]
```

and here the settings:

```
"settings": {
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".tsx"]
        },
        "import/resolver": {
            "node": {},
            "ts": {
                "directory": ["./src"],
            }
        }
    },
```

Example imports:
<img width="753" alt="Bildschirmfoto 2022-01-20 um 12 04 24" src="https://user-images.githubusercontent.com/1771763/150327457-f01427dc-4e32-4bf8-b227-5a28833c1b3e.png">

And here the folder structure:
<img width="447" alt="Bildschirmfoto 2022-01-20 um 12 09 28" src="https://user-images.githubusercontent.com/1771763/150327761-efb2b36c-a0da-4b01-8cdb-2495bff723f1.png">

Paths:
/src/tsconfig.json
/src/.eslintrc

path to internal modules would be:
/src/src/**

**Comment by vertic4l** [comment]
@ljharb The issue is that all components from /src/... are treated as externals, although they should been treated as internals.

**Comment by ljharb** [comment]
You don’t have anything in your eslint settings that would mark them as internal.

**Comment by vertic4l** [comment]
@ljharb could enlighten me what would be necessary for it?
