### ISSUE TITLE
New rule: enforce-package-exports

### ISSUE THREAD

**Issue by bworline** [import-js/eslint-plugin-import#2366]
package.json exports maps is a new feature in node 12+ and webpack 5.

https://nodejs.org/api/packages.html#exports 
https://webpack.js.org/guides/package-exports/ 

This rule would enforce a package's declared interface, preventing consumers from taking a dependency on internal and/or unsupported APIs that could change in the future with even a semver patch.  
* If the import refers to a package that declares an exports map, then imports are only allowed from explicitly declared exports.
* If the import refers to a package that doesn't have an exports map, assume the only valid import is the top-level package export and error on any subpath-based imports.  e.g., `import { xyz } from "mypackage"` is OK, `import { xyz } from "mypackage\subpath"` is an Error.

**Comment by ljharb** [comment]
We use `resolve`, which (like most of the ecosystem) lacks support for "exports".

There's already the `no-unresolved` rule - once `resolve` supports "exports", it would automatically trigger on anything that's not in exports, because you can't resolve it.

**Comment by dzearing** [comment]
One thing to consider with the rule is how exports conditionals will be specified. For this to work well, the no-unresolved rule might need an option to provide the array of conditionals overrides. That way if, say, a package has development vs production or browser vs node exports, the rule can be explicit.

**Comment by bworline** [comment]
@ljharb  Will the `no-unresolve` rule handle the second aspect of the proposed new rule, where the import refers to a package that doesn't have an exports map?

**Comment by ljharb** [comment]
@bworline no, a package with no "exports" map allows *everything* to be imported, so it would be wildly incorrect to error on importing something from there.

@dzearing that is a very good point; altho it should be very rare that there's something that a) has a different set of exports based on the condition, or b) lacks a node-friendly condition entirely.
