### ISSUE TITLE
Option for `no-nodejs-modules` to pass when Node-specific environment detected

### ISSUE THREAD

**Issue by brettz9** [import-js/eslint-plugin-import#2369]
For `no-nodejs-modules`, I think it would be convenient to have an option to fail to enforce this when:

1. The file is pointed to by a `node` conditional export in `package.json`
2. The file has `{env: {node: true}}` applied to it

These conditions are more likely to suggest that the file or the entire package is Node only.

Such an option ought to help discourage packages which could be polyglot friendly from restricting their files or packages unnecessarily to Node.

While the second condition would be more likely to be accidentally added by a project and thus unduly suppress cases where a package could be poylglot but is not (and thus perhaps this condition could be made disable-able by option as well), I think this condition should be allowed as some projects may be Node only.

**Comment by ljharb** [comment]
I'm a bit confused; `no-nodejs-modules` is only for use of node builtin modules. Its purpose is in no way to have "no modules designed for use in node".

**Comment by brettz9** [comment]
This is not intended to prevent use in Node. It is intended to liberalize application of the rule, by option, so that Node-specific environments are exempted from the rule while allowing the rest of the code base to enforce the rule.

The rule states, "Can be useful for client-side web projects that do not have access to those modules." Such an option would better encourage this purpose by allowing for a convenient co-existence by which Node-specific code must be kept to its own files. The user would not need to specifically configure this rule for specific files, but it would instead be auto-detected for them.

**Comment by ljharb** [comment]
Linter rules apply to both apps and packages. You’re saying you want the rule to decide how it behaves based on whether its package.json has “exports”, and points to it with a ”node” condition?

Everything that node could consume is a file meant for use in node - so the only case when a file *wouldn't* qualify is when it’s in a package with “exports”, *and* it’s not imported by any other file that’s a “node file”, and when it’s also referenced by a non-node exports condition?

That’s a ton of complexity that definitely doesn’t belong in this rule, setting aside that `resolve` doesn’t yet support exports at all, and that there’s no tool i know of that can reverse-map from a file to the exports entry that it may resolve to.

It’s very interesting to consider a totally new rule that’s meant for packages (not apps) and provides some guarantees about the dependency graphs for each condition - but i don’t think the tools exist yet to make it possible.

**Comment by brettz9** [comment]
> Linter rules apply to both apps and packages. You’re saying you want the rule to decide how it behaves based on whether its package.json has “exports”, and points to it with a ”node” condition?

Whether it has `exports` and points to it with a "node" condition OR `env: {node: true}`.

> Everything that node could consume is a file meant for use in node - so the only case when a file _wouldn't_ qualify is when it’s in a package with “exports”, _and_ it’s not imported by any other file that’s a “node file”, and when it’s also referenced by a non-node exports condition?

No, by a "node file", I am talking about something already flagged by the user as Node-*specific*. 

Of course most files can normally be used by Node. But unless a project needs Node-specific globals (as flagged well by `env: {node: true}`) or are intended as a Node-specific export, then a project might wish to assume that all other files in its projects not so marked are polyglot--i.e., they can potentially be run in any environment.

If the user has flagged their files already in one of the two manners, then such files would be allowed under this option to also require Node built-in modules. (Of course a user could override this in their ESLint `overrides`, insisting that specific files are not exempted, whether they meet the two conditions or not).

A project might wish to enforce a policy of having Node-specific entry files, browser-specific entry files, and having all other files be environment-independent--expecting an implementation, for example, whether from the Node entry or the browser one. For example, the Node entry file might require or import `node-fetch` and pass it to the function exported by the polyglot file, while the browser entry file might just pass in `window.fetch` to that function in the polyglot file. (And yes, as discussed elsewhere, I am aware there may be subtle differences by which the fetch implementations might not work the same in every way.)

I am thus saying that I want to put the burden of indicating that a file is Node-only on projects which either indicate `node` in `package.json` `exports` or by setting `{env: {node: true}}`. Once a project is flagged as Node-only, then all other files will be assumed *not* to support built-in Node modules either and will report errors on encountering them (but not the Node-specific ones).

Please note that this is only an additional option. I realize that some projects will wish to ban built-in modules even where the Node environment (and its globals) are used.

Thanks for your consideration.

**Comment by ljharb** [comment]
ok, so let me repeat back to make sure i understand.

You want a way to have `no-nodejs-modules` ignore any code that meets any of the following criteria:
 1. has `env.node` set to true
 2. is referenced by the current package's "exports" field under a `node` condition
 
In general, all JS code in a node package is node-specific by default (altho the majority of that works automatically in a browser via a working node module bundler), and it's up to the package author to opt in to providing code for other environments, via the "browser" field, for example.

It kind of seems like your use case is that you want to be able to assume that code is universal by default (which means it doesn't use setTimeout, or any i/o including file or network or UI, or any globals outside of ecma262) - but that's not how packages work in the node ecosystem.

**Comment by brettz9** [comment]
> ok, so let me repeat back to make sure i understand.
> 
> You want a way to have `no-nodejs-modules` ignore any code that meets any of the following criteria:
> 
> 1. has `env.node` set to true
> 2. is referenced by the current package's "exports" field under a `node` condition

Right.
 
> In general, all JS code in a node package is node-specific by default (altho the majority of that works automatically in a browser via a working node module bundler), and it's up to the package author to opt in to providing code for other environments, via the "browser" field, for example.

If a browser-based package installs an npm package, and adds a script tag for a JavaScript file within `node_modules` (or does its own bundling from source and references that in a script tag), the code in an npm package is not Node-specific by default. It is whatever content is published within it--whether that code relies on browser globals or not.

But yes, the fields for special awareness of browser builds such as the `browser` field, or now `browser` within conditional `exports` as used by bundlers, as well as the leveraging of `package.json` dependencies by the likes of [importly](https://www.npmjs.com/package/importly) and [@jsenv/importmap-node-module](https://www.npmjs.com/package/@jsenv/importmap-node-module) which convert the dependency information into import maps which can then be used in a browser without a build step for the source code which consumes it, have been grafted on top of the Node system, though noting this grafting has worked well, even to the extent that a good number of packages do so solely with browser builds. The *Node* package manager is nevertheless useful as a generic JavaScript package manager.

> It kind of seems like your use case is that you want to be able to assume that code is universal by default (which means it doesn't use setTimeout, or any i/o including file or network or UI, or any globals outside of ecma262) - but that's not how packages work in the node ecosystem.

Yes, that is what I would like to do. (I might make an exception for allowing `setTimeout` and the like given my own general interest being more or less limited to the target environments of Node, the browser, workers, and perhaps with an eye to compatibility with Deno even though I am not using it myself currently, though I might be convinced to separate out `setTimeout` and friends as well if there are practical benefits for many users in doing so).

There's nothing to stop packages from working in this way as desired within the Node ecosystem. I and many others have done so; I would just like a way to enforce this to ensure proper structure and behavior in my own projects as well as a nudge to others (who might inherit such rules in their ESLint configs), to consider structuring their code in the same manner so as to benefit browser users. From my experience, most projects are open to doing so when it is meaningful for their code to be universal/polyglot, but they have simply relied on CJS-only source or distribution files, with Node built-ins mixed in, out of habit and inertia.

**Comment by brettz9** [comment]
> ok, so let me repeat back to make sure i understand.
> 
> You want a way to have `no-nodejs-modules` ignore any code that meets any of the following criteria:
> 
> 1. has `env.node` set to true
> 2. is referenced by the current package's "exports" field under a `node` condition

Right.
 
> In general, all JS code in a node package is node-specific by default (altho the majority of that works automatically in a browser via a working node module bundler), and it's up to the package author to opt in to providing code for other environments, via the "browser" field, for example.

If a browser-based package installs an npm package, and adds a script tag for a JavaScript file within `node_modules` (or does its own bundling from source and references that in a script tag), the code in an npm package is not Node-specific by default. It is whatever content is published within it--whether that code relies on browser globals or not.

But yes, the fields for special awareness of browser builds such as the `browser` field, or now `browser` within conditional `exports` as used by bundlers, as well as the leveraging of `package.json` dependencies by the likes of [importly](https://www.npmjs.com/package/importly) and [@jsenv/importmap-node-module](https://www.npmjs.com/package/@jsenv/importmap-node-module) which convert the dependency information into import maps which can then be used in a browser without a build step for the source code which consumes it, have been grafted on top of the Node system, though noting this grafting has worked well, even to the extent that a good number of packages do so solely with browser builds. The *Node* package manager is nevertheless useful as a generic JavaScript package manager (and this was itself envisioned by the fact of `engines` allowing for other engines besides Node).

> It kind of seems like your use case is that you want to be able to assume that code is universal by default (which means it doesn't use setTimeout, or any i/o including file or network or UI, or any globals outside of ecma262) - but that's not how packages work in the node ecosystem.

Yes, that is what I would like to do. (I might make an exception for allowing `setTimeout` and the like given my own general interest being more or less limited to the target environments of Node, the browser, workers, and perhaps with an eye to compatibility with Deno even though I am not using it myself currently, though I might be convinced to separate out `setTimeout` and friends as well if there are practical benefits for many users in doing so).

There's nothing to stop packages from working in this way as desired within the Node ecosystem. I and many others have done so; I would just like a way to enforce this to ensure proper structure and behavior in my own projects as well as a nudge to others (who might inherit such rules in their ESLint configs), to consider structuring their code in the same manner so as to benefit browser users. From my experience, most projects are open to doing so when it is meaningful for their code to be universal/polyglot, but they have simply relied on CJS-only source or distribution files, with Node built-ins mixed in, out of habit and inertia.

**Comment by ljharb** [comment]
I think I’d encourage you to build your own eslint plugin for that, since there’s likely to be a number of rules that you want to be able to enforce it. I don’t think that it’d be worth the complexity here to try to support wishful thinking about what the ecosystem might become.

**Comment by brettz9** [comment]
Ok...thanks for the consideration!

**Comment by brettz9** [comment]
Btw, even if this isn't your cup of tea, if you have any ideas for rules and care to share, let me know, as I can only really think of those I mentioned.
