### ISSUE TITLE
Add support for "node:<package>" in import/extensions rule

### ISSUE THREAD

**Issue by MrNossiom** [import-js/eslint-plugin-import#2373]
Hi, 
While using the plugin, I ran into a bug.
When importing a node package using the `node:<package>` syntax, the rule thinks it is a module and asks for the `.js` extension.

Example:
```js
import { readdir } from 'node:fs/promises'; // Error
import { readdir } from 'fs/promises'; // No error
```

I think this might be easily fixed.

I'll try to do a PR.
Thanks for your feedback.

**Comment by MrNossiom** [comment]
Yeah sure,
Indeed, the error come from the VS Code ESLint official extension version 2.2.2

In the logs, it says: 
```
[Info] ESLint server is starting
[Info] ESLint server running in node v14.16.0
[Info] ESLint server is running.
[Info] ESLint library loaded from: /path/to/project/node_modules/eslint/lib/api.js
```

**Comment by ljharb** [comment]
The node: prefix started working in v14.18, so that’s the problem.

I’d suggest avoiding it anyways; there’s precisely zero advantage to using it.

**Comment by MrNossiom** [comment]
Ok thanks

**Comment by burtek** [comment]
@MrNossiom 

Just found out, in vscode one can set `"eslint.runtime"` setting to `"node"` to force eslint execution in locally installed version of node (see [explanation for this option here](https://github.com/microsoft/vscode-eslint#settings-options)). Requires full restart of vscode.

![image](https://user-images.githubusercontent.com/2940958/151642055-93f490dd-818c-416b-861c-164d6c115c5f.png)

**Comment by MrNossiom** [comment]
This works really well after reload! Thanks

**Comment by s-h-a-d-o-w** [comment]
Hm, I'm getting errors even when using node 18.15 and plugin version 2.27.5:
```
1:26  error    Unable to resolve path to module 'node:fs/promises'  import/no-unresolved
2:18  error    Unable to resolve path to module 'node:path'         import/no-unresolved
```

Is there anything I might be missing about configuration or something?

**Comment by ljharb** [comment]
@s-h-a-d-o-w what version of node are you using where you get those errors?

**Comment by s-h-a-d-o-w** [comment]
18.15

**Comment by ljharb** [comment]
@s-h-a-d-o-w in that case, if you're getting that on the cli with that node version, there's something very strange going on. Can you file a new issue?

**Comment by s-h-a-d-o-w** [comment]
Fortunately, I've gotten into the habit of always trying to create a minimal repro before creating a new issue. 😅 

Turns out that in the larger project where I got that error, [eslint-import-resolver-alias](https://www.npmjs.com/package/eslint-import-resolver-alias) is used and caused this problem.

Thanks a lot for the quick replies though!
