### ISSUE TITLE
"core-modules" doesn't work for submodules

### ISSUE THREAD

**Issue by arturenault** [import-js/eslint-plugin-import#2380]
I added the following line to my .eslintrc to indicate that aws-sdk is a core module
```
    "import/core-modules": ["aws-sdk"]
```

This was working fine until I had to import a submodule of that package:
```
import { GetParametersByPathResult } from "aws-sdk/clients/ssm"
```

When this line is in the code I get the following error:
```
  3:1  error  'aws-sdk' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

I'd expect "core-modules" to apply to all submodules of that particular module, right?

**Comment by ljharb** [comment]
`aws-sdk/clients/ssm` is not a core module, no. Core modules are *only* the precise path in the list - in the same way, `fs` and `fs/promises` are core modules, but if you try to import `fs/something` you'll get `node_modules/fs/something`.

**Comment by arturenault** [comment]
Interesting, TIL. Thanks for the clarification.

In this particular case I was able to work around this by importing "@aws-sdk/client-ssm" instead of the global "aws-sdk" package.
