### ISSUE TITLE
[order] move nested import entries closer to the main import entry

### ISSUE THREAD

**Issue by zaverden** [import-js/eslint-plugin-import#2385]
I want to keep `next` and `next/*` imports together
```ts
import Core from "next";
import Image from "next/image";
import Link from "next/link"
import Auth from "next-auth";
```

But the plugin forces me to break them with `next-*` imports
```diff
  import Core from "next";
+ import Auth from "next-auth";
  import Image from "next/image";
  import Link from "next/link"
- import Auth from "next-auth";
```

Same issue for the relative imports, the plugin wants me to change the order this way 
```diff
  import e1 from "../businesses";
+ import e3 from "../businesses-users";
  import e2 from "../businesses/components";
- import e3 from "../businesses-users";
```

**Comment by pri1311** [comment]
Hey, I was going through the codebase and I believe I have a basic understanding about required changes for the particular issue. Would like to give it a try if the issue is up for grabs.

**Comment by ljharb** [comment]
Go for it! Anything with "help wanted" that doesn't already have a PR associated, please feel free to submit one :-)
