### ISSUE TITLE
Error while loading rule 'import/no-unused-modules': Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by tomdglenn91** [import-js/eslint-plugin-import#2388]
So this one may be difficult to reproduce as I cannot replicate in a sandbox, but in my big codebase it breaks. 

I have a mixture of javascript and typescript as we migrate over to ts, and have just switched on this rule. I have it configured as such:

```
'import/no-unused-modules': [
          'warn',
          {
            unusedExports: true,
            src: [path.join(__dirname, 'src', 'main')],
            ignoreExports: ['**/white/**'],
          },
        ],
```

This is turned on for both javascript and the typescript overrides. I basically do not want to use this rule in anything that exists in a folder called `white`. This is due to some module hacking we are doing to overwrite code at build time.

I get the following stack trace when it errors:

```
❯ yarn run eslint --ext .js --ext .jsx --ext .ts --ext .tsx src/main/constants
yarn run v1.22.17
$ /Users/tom/code/projects/frontend/node_modules/.bin/eslint --ext .js --ext .jsx --ext .ts --ext .tsx src/main/constants

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Error while loading rule 'import/no-unused-modules': Cannot read properties of undefined (reading 'get')
Occurred while linting /Users/tom/code/projects/frontend/src/main/constants/access-permissions.js
    at /Users/tom/code/projects/frontend/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:277:44
    at Set.forEach (<anonymous>)
    at /Users/tom/code/projects/frontend/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:274:11
    at Map.forEach (<anonymous>)
    at prepareImportsAndExports (/Users/tom/code/projects/frontend/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:273:13)
    at doPreparation (/Users/tom/code/projects/frontend/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:344:3)
    at Object.create (/Users/tom/code/projects/frontend/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:484:9)
    at createRuleListeners (/Users/tom/code/projects/frontend/node_modules/eslint/lib/linter/linter.js:765:21)
    at /Users/tom/code/projects/frontend/node_modules/eslint/lib/linter/linter.js:937:31
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I can get around this by going into the code itself in `node_modules` and changing:

```
var currentExports = exportList.get(val);
var currentExport = currentExports.get(EXPORT_ALL_DECLARATION);
currentExport.whereUsed.add(key);
```

to:

```
var currentExports = exportList.get(val);
if (currentExports) {
  var currentExport = currentExports.get(EXPORT_ALL_DECLARATION);
  currentExport.whereUsed.add(key);
}
```

I can raise a PR for this if necessary, however before doing so I wanted to check if this seems like a valid solution as I wasn't sure if it could be something my side (I also couldn't figure out your testing pattern in the 10 minutes i looked!)

Thanks.

**Comment by ljharb** [comment]
This plugin will crawl your entire dep graph, including stuff in the white folder. You may need the import/ignore setting.

Can you share the code that it’s erroring on?

**Comment by tomdglenn91** [comment]
The file it falls over on is a simple constants file.

```
export const REGISTER = 'register'
export const CLASS = 's_class'
export const ORDERS = 's_orders'
```

For experimentation, I tried just deleting this file and it then errors on the next file down the list. I assume it's just the first file it tries to lint.

I can try adding the same glob to `import/ignore`, but to be honest I didn't quite understand the `import/ignore` rule to begin with 😞 .

**Comment by ljharb** [comment]
In this case, I’m talking about a global setting, not a rule - see the docs.

I assume even though you’re on eslint 7, you’re on the latest version of the plugin?

what file _imports_ that access-permissions file?

**Comment by tomdglenn91** [comment]
Ah sorry I meant the global setting yeah.

I am indeed on the latest version (^2.25.4) with eslint 7. Have tried upgrading to eslint 8 but the issue still occurs. 

It's imported all over the place which may make this more difficult. An example is we have it imported from `constants/permissions`, then from `helpers`. It's a pretty big spaghetti mess. 

I went to the extreme and deleted all of `constants` as well as some other huge directories and the issue still occurs.

**Comment by tomdglenn91** [comment]
I've managed to recreate it! The culprit seems to be when there's an index file. I don't know the specifics without digging into your code (stuck at work right now 😭 ) .

I've managed however to recreate it in a tiny little repository. I hope this format is okay to observe the issue:

![Screenshot 2022-02-21 at 18 57 37](https://user-images.githubusercontent.com/31797732/155012842-75ae1597-bdb9-445b-b4b4-3dc1850c122a.png)

The second i delete the `index.js` file, everything is all good.

![Screenshot 2022-02-21 at 18 58 14](https://user-images.githubusercontent.com/31797732/155012898-408cfcdf-f578-4d95-96de-e09d1c99818b.png)

**Comment by ljharb** [comment]
@tomdglenn91 could you share that repo? That would make it much easier to fix this :-)

**Comment by tomdglenn91** [comment]
> @tomdglenn91 could you share that repo? That would make it much easier to fix this :-)

Hey sorry for the radio silence. I've pushed the repo up here:
https://github.com/tomdglenn91/import-lint-issue

If you try to run the linter, you get an error , despite the folder being ignored. If you remove the `index.js` file however, the linter will run again fine. I've gotten around this by adding the matching ignoreExports to `import/ignore` config as you mentioned above.

**Comment by doctorby** [comment]
The issue is still there in 2.27.5 version
