### ISSUE TITLE
[import/no-unresolved] when using with typescript and "paths" option

### ISSUE THREAD

**Issue by kristijorgji** [import-js/eslint-plugin-import#2405]
I get [import/no-unresolved] error with eslint while using typescript tsconfig.json paths option.

nextjs + typescript + eslint

My eslint file
```
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaFeatures: { jsx: true },
    },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/eslint-recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:react/recommended',
        'plugin:jsx-a11y/recommended',
        'plugin:import/errors',
        'plugin:import/warnings',
        'plugin:import/typescript',

        // Prettier plugin and recommended rules
        'plugin:prettier/recommended',
    ],
    rules: {
        // Include .prettierrc.js rules
        'prettier/prettier': ['error', {}, { usePrettierrc: true }],

        'no-empty': 'off',
        'react/prop-types': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
        '@typescript-eslint/no-non-null-assertion': 'off',
        'jsx-a11y/click-events-have-key-events': 'off',
        'jsx-a11y/no-static-element-interactions': 'off',
        'jsx-a11y/interactive-supports-focus': 'off',
        'jsx-a11y/no-noninteractive-element-interactions': 'off',
        'jsx-a11y/no-onchange': 'off',
    },
    settings: {
        'import/extensions': ['.js', '.jsx', '.tsx', '.ts'],
        'import/resolver': {
            typescript: {},
        },
    },
};
```

In tsconfig.json i use `paths` 
```
"paths": {
      "@/core/*": ["src/core/*"],
}
```
and get errors from eslint like

```
  18:23  error  Unable to resolve path to module '@/core/useRouter'                  import/no-unresolved

```

Compilation build all works great, just linting fails eslint

**Comment by SalahAdDin** [comment]
It does not work with bare `React` and `Typescript` setup.

I tried all solutions I found on StackOverflow and the linked issue, and I could not make it work.

**Comment by lifedup** [comment]
Do you have your baseUrl set in tsconfig?

```
"baseUrl": ".",
"paths": {
      "@/core/*": ["src/core/*"],
}
```

I can get the module to resolve or eslint to work, not both simultaneously.

**Comment by SalahAdDin** [comment]
> turborepo

I'm using `"baseUrl": "src"`, it should work, isn't it?

**Comment by tettoffensive** [comment]
> Do you have your baseUrl set in tsconfig?
> 
> ```
> "baseUrl": ".",
> "paths": {
>       "@/core/*": ["src/core/*"],
> }
> ```
> 
> I can get the module to resolve or eslint to work, not both simultaneously. It builds fine when eslint works and vscode can't find the module.
> 
> I'm using turborepo, next, eslint, and typescript

Did you figure this out? I also have an issue with eslint showing the error in vscode, but it otherwise compiles and the error goes away for a bit when I run `eslint` with a file open. Reopening the file causes the error to come back.

**Comment by SalahAdDin** [comment]
> Do you have your baseUrl set in tsconfig?
> 
> ```
> "baseUrl": ".",
> "paths": {
>       "@/core/*": ["src/core/*"],
> }
> ```
> 
> I can get the module to resolve or eslint to work, not both simultaneously. It builds fine when eslint works and vscode can't find the module.
> 
> I'm using turborepo, next, eslint, and typescript

Mine is this:
```
"baseUrl": "src",
  "paths": {
    "@/application/*": ["application/*"],
    "@/domain/*": ["domain/*"],
    "@/presentation/*": ["presentation/*"]
  },
```

**Comment by loweoj** [comment]
On the plugin docs (https://github.com/alexgorbatchev/eslint-import-resolver-typescript):

Adding 
```
  settings: {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"],
    },
    "import/resolver": {
      typescript: {},
    },
  },
```

has worked for me - the `import/parsers` bit seemed to fix it.

**Comment by ilya-adnymics** [comment]
@loweoj warked for me. Thanks!

**Comment by SalahAdDin** [comment]
> On the plugin docs (https://github.com/alexgorbatchev/eslint-import-resolver-typescript):
> 
> Adding
> 
> ```
>   settings: {
>     "import/parsers": {
>       "@typescript-eslint/parser": [".ts", ".tsx"],
>     },
>     "import/resolver": {
>       typescript: {},
>     },
>   },
> ```
> 
> has worked for me - the `import/parsers` bit seemed to fix it.
> 
> this is with ` "eslint-import-resolver-typescript": "^2.7.1",`

Well, I have this configuration, and it does not work.

**Comment by SalahAdDin** [comment]
> > Do you have your baseUrl set in tsconfig?
> > ```
> > "baseUrl": ".",
> > "paths": {
> >       "@/core/*": ["src/core/*"],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can get the module to resolve or eslint to work, not both simultaneously. It builds fine when eslint works and vscode can't find the module.
> > I'm using turborepo, next, eslint, and typescript
> 
> Mine is this:
> 
> ```
> "baseUrl": "src",
>   "paths": {
>     "@/application/*": ["application/*"],
>     "@/domain/*": ["domain/*"],
>     "@/presentation/*": ["presentation/*"]
>   },
> ```
> 
> > > Do you have your baseUrl set in tsconfig?
> > > ```
> > > "baseUrl": ".",
> > > "paths": {
> > >       "@/core/*": ["src/core/*"],
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I can get the module to resolve or eslint to work, not both simultaneously. It builds fine when eslint works and vscode can't find the module.
> > > I'm using turborepo, next, eslint, and typescript
> > 
> > 
> > Did you figure this out? I also have an issue with eslint showing the error in vscode, but it otherwise compiles and the error goes away for a bit when I run `eslint` with a file open. Reopening the file causes the error to come back.
> 
> And yeah, it compiles, not problem with it, but `eslint` still gives the problem.

I was not putting it inside of the `compiler` settings.

**Comment by maikelvl** [comment]
In case you have a custom path tsconfig, you might want to add it to `typescript.project` as found in https://github.com/import-js/eslint-plugin-import/issues/2301#issuecomment-974473228

```js
  settings: {
    "import/resolver": {
      typescript: {
        project: ["tsconfig.base.json"]
      },
    },
  },
```

**Comment by liamjsc** [comment]
Facing a similar issue here, I've tried each of the solutions above and no resolution. nextjs + typescript + eslint
typescript compiles fine, but eslint throws errors like:
```
./src/api/auth.ts
1:28  Error: Unable to resolve path to module 'config'.  import/no-unresolved
```

My repo is set up like
```
tsconfig.json
.eslintrc.json
src/
- api/
- components/
- config.ts
```

relevant tsconfig.json:
```
{
  "compilerOptions": {
    "baseUrl": "src",
  },
  "include": ["next-env.d.ts", "vendor.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

and .eslintrc.json
```
{
  "settings": {
    "import/resolver": {
      "typescript": {
        "project": ["tsconfig.json"]
      }
    },
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    }
  },
  "env": {
    "es6": true,
    "jest": true
  },
  "extends": ["next/core-web-vitals", "prettier"],
  "plugins": ["prettier", "import"],
  "globals": {
    "React": "writable"
  },
  "ignorePatterns": ["vercel-ignore.js"],
  "rules": {
    "react/react-in-jsx-scope": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "import/no-anonymous-default-export": "off",
    "import/no-unresolved": "error"
  }
}
```

Anything look off here? Thanks

**Comment by ljharb** [comment]
@liamjsc yes, you're missing the `import/extensions` setting, which would need to include `.ts`.

**Comment by CloudLooks** [comment]
@ljharb thank you! eslint passes now.

Still trying to configure vscode to:
1. Stop complaining about this syntax. `import { baseApiURL } from 'config'` has 'config' red underlined, and "problems" includes ts(2307)
<img width="261" alt="Screen Shot 2022-09-26 at 10 49 41 AM" src="https://user-images.githubusercontent.com/99063434/192346509-fbc1d19d-cd32-461a-bbd3-862223cdf481.png">

2. "quick fix" is suggesting a relative import for cases like this 
<img width="380" alt="Screen Shot 2022-09-26 at 10 48 25 AM" src="https://user-images.githubusercontent.com/99063434/192346473-1a84ab1d-2d23-42e7-a7d3-7dbd54ad87ad.png">

I expect these may not be related to eslint or import-js, but if you have a suggestion I am stuck here. thanks

**Comment by liamjsc** [comment]
@ljharb thank you! eslint passes now.

Still trying to configure vscode to:

1. Stop complaining about this syntax. import { baseApiURL } from 'config' has 'config' red underlined, and "problems" includes ts(2307)
<img width="261" alt="Screen Shot 2022-09-26 at 10 49 41 AM" src="https://user-images.githubusercontent.com/12700715/192346958-561d542b-240f-41ec-b6d7-5d50ddd4f3e6.png">

2. "quick fix" is suggesting a relative import for cases like this
<img width="380" alt="Screen Shot 2022-09-26 at 10 48 25 AM" src="https://user-images.githubusercontent.com/12700715/192346980-3334f468-6e47-4fdb-a69c-aba299fa3b37.png">

I expect these may not be related to eslint or import-js, but if you have a suggestion I am stuck here. thanks

**Comment by JounQin** [comment]
@liamjsc You may need to reload VSCode.

**Comment by SalahAdDin** [comment]
> @liamjsc You may need to reload VSCode.

@liamjsc did you try this?

**Comment by liamjsc** [comment]
@JounQin @SalahAdDin yes, unplug it and plug it back in 😮‍💨 

Thanks for the followup

**Comment by karolis-sh** [comment]
@damiangreen to my understanding, this plugin doesn't completely resolve tsconfig when it's being extended, try:

```json
  settings: {
    'import/resolver': {
      typescript: {
        project: ['../../tsconfig.settings.json'],
      },
    },
  },
```

Had similar issues in SvelteKit project and this solved it:

```json
  settings: {
    'svelte3/typescript': () => require('typescript'),
    'import/resolver': {
      typescript: {
        project: ['./.svelte-kit/tsconfig.json'],
      },
    },
  },
```

**Comment by karolis-sh** [comment]
@ljharb when the `paths` compiler option is placed in a tsconfig that is being extended from, it doesn't **seem** to resolve that.

Having

`tsconfig.json`
```json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "stripInternal": true
  }
}
```

and `./.svelte-kit/tsconfig.json`
```json
{
  "compilerOptions": {
    "paths": {
      "$lib": ["../src/lib"],
      "$lib/*": ["../src/lib/*"]
    },
    ...
  }
}
```

This fails

```js
  settings: {
    'svelte3/typescript': () => require('typescript'),
    'import/resolver': {
      typescript: {
        project: ['./tsconfig.json'],
      },
    },
  },
```
as `3:22  error  Unable to resolve path to module '$lib/components/Footer.svelte'  import/no-unresolved`

While this works
```js
  settings: {
    'svelte3/typescript': () => require('typescript'),
    'import/resolver': {
      typescript: {
        project: ['./.svelte-kit/tsconfig.json'],
      },
    },
  },
```

🤷

**Comment by ljharb** [comment]
interesting, ok - maybe that's a feature in v4 of tsconfig-paths and we're stuck on v3.

**Comment by scorsi** [comment]
@karolis-sh is it still working on your side ? When I try your solution I got `Unable to resolve path to module` on every single imports even from modules...

Here's my full eslint config:
```js
module.exports = {
	root: true,
	parser: "@typescript-eslint/parser",
	extends: [
		"eslint:recommended",
		"plugin:@typescript-eslint/recommended",
		"prettier",
		"plugin:import/recommended",
		"plugin:import/typescript",
	],
	plugins: ["svelte3", "@typescript-eslint"],
	ignorePatterns: ["*.cjs"],
	overrides: [{ files: ["*.svelte"], processor: "svelte3/svelte3" }],
	settings: {
		"svelte3/typescript": () => require("typescript"),
		"import/resolver": {
			typescript: {
				project: ["./.svelte-kit/tsconfig.json"],
			},
		},
	},
	rules: {
		"import/order": [
			"error",
			{
				groups: ["builtin", "external", "internal", ["sibling", "parent"], "index", "unknown"],
				"newlines-between": "always",
				alphabetize: {
					order: "asc",
					caseInsensitive: true,
				},
			},
		],
	},
	parserOptions: {
		sourceType: "module",
		ecmaVersion: 2020,
	},
	env: {
		browser: true,
		es2017: true,
		node: true,
	},
};
```

To remove errors, I have to remove the resolver + `import/no-unresolved": "off"`.

**Comment by ljharb** [comment]
@scorsi the import/resolver settings should include `node: {}` after the typescript resolver.

**Comment by scorsi** [comment]
> @scorsi the import/resolver settings should include `node: {}` after the typescript resolver.

It partially fixes my issue, still have `Unable to resolve path to module '$app/environment'`,
which is declared like so in `ambient.d.ts` included in "./.svelte-kit/tsconfig.json":
```ts
declare module '$app/environment' {}
```
<img width="375" alt="Capture d’écran 2023-05-01 à 15 04 05" src="https://user-images.githubusercontent.com/8389441/235455243-cd7f07ad-4e47-4a1f-9caf-0a722ac51493.png">

What a mess...

**Comment by Doug-Colin** [comment]
### What worked for me (Vite, React, and TypeScript):
- Installing plugins  [eslint-import-resolver-alias](https://github.com/johvin/eslint-import-resolver-alias#readme) , and [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript#readme).
- Adding 'import-resolver-alias' to the plugins array of my eslint config. 

### Notes:
- You can also try adding 'eslint-import-resolver-typescript' to the plugins array of your eslint config. At one point, this also fixed the `Unable to resolve path to module` flags for me, but that plugin had a strange error which I resolved with nuance (by nuking package.json and re-running npm install). After that, I only needed to add 'import-resolver-alias' to my eslint config's plugins array.  
- I have a path alias defined in my tsconfig.json, which is in the same directory as my eslint config. The [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript#readme) plugin seems to resolve my path alias just fine via tsconfig.json.  As per the [docs](https://github.com/import-js/eslint-import-resolver-typescript#configuration), so long as tsconfig.json is in the same directory as eslint config, you shouldn't need to add the project property and path to the typescript object.
- I was predominantly getting eslint `Unable to resolve path to module`  flags on internal project imports.

### Configs
- eslintrc.cjs:
```js
module.exports = {
  root: true,
  env: { browser: true, es2020: true },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react-hooks/recommended',
    'plugin:prettier/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
  ],
  ignorePatterns: ['dist', '.eslintrc.cjs'],
  parser: '@typescript-eslint/parser',
  plugins: [
    'import',
     /* This line here was key. */
    'import-resolver-alias', 
    'react-refresh',
  ],
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
  rules: {
    'import/no-unresolved': 'error',
    'react-refresh/only-export-components': [
      'warn',
      { allowConstantExport: true },
    ],
  },
}
```

- tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Resolve paths/path alias without error. */
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    /* Bundler mode. */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    /* Linting. */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": [
    "src"
, "project_notes/DialogDemo.tsx"  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

- viteconfig.ts:
```ts
import path from "path"
import { defineConfig } from "vite"

export default defineConfig({
  /* Resolve path alias. */
  resolve: {
    alias: {                                                    
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    proxy: {
         /* My proxy config*/
    }
  }
});
```
