### ISSUE TITLE
Remove duplicates names in `no-duplicates` autofix

### ISSUE THREAD

**Issue by remcohaszing** [import-js/eslint-plugin-import#2437]
Let’s say we have the following content:

```js
import { a, b } from 'module'
import { a, c } from 'module'
```

The `import/no-duplicates` rule will report this, then perform the following autofix:

```js
import { a, b, a, c } from 'module'
```

I would expect it to remove duplicates, so the output would be:

```js
import { a, b, c } from 'module'
```

In my experience this is common when resolving merge conflicts if two branches added a new member to the import statement. It’s easy to _Accept both changes_, then let ESLint autofix resolve any issues with the imports. However, afterwards one has to remove the duplicates manually.

**Comment by ljharb** [comment]
That seems like a good approach. One could be renamed ofc, in which case both would need to be kept, but when neither has a rename, or when they both have the same one, the autofix should be collapsing them.
