### ISSUE TITLE
type: module should have option to require .js when .ts or .tsx is used

### ISSUE THREAD

**Issue by ntucker** [import-js/eslint-plugin-import#2446]
If you have a file with .ts or .tsx it will potentially create a .js file. When package type is 'module' this means .js needs to be used as the extension for relative imports.

**Comment by ljharb** [comment]
That's true, but this plugin, via `resolve`, doesn't yet support "exports" or "type module" (which should be avoided regardless). Additionally, extensions are only required in native ESM; CJS files can still follow the best practice of omitting then.

When `resolve` gets this support, then the plugin will need a setting for people to opt in to "native ESM" mode for files, and the "extensions" rule will need to be updated to handle this use case.

**Comment by ukstv** [comment]
I made a crack to solve the issue in https://github.com/import-js/eslint-plugin-import/pull/2483
