### ISSUE TITLE
Prefer default export in svelte routes folder

### ISSUE THREAD

**Issue by justingolden21** [import-js/eslint-plugin-import#2449]
I have files in `/routes/` that contain a `get` method, for example:

`export async function get({ locals }) {`

However, ESLint tells me `Prefer default export.eslint[import/prefer-default-export](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/prefer-default-export.md)` and highlights the entire file in red.

**Comment by ljharb** [comment]
Then you’ll need to use an override. The advice doesn’t change even if a particular framework encourages something different.
