### ISSUE TITLE
[question] does it support require() and webpack aliases?

### ISSUE THREAD

**Issue by eng-dibo** [import-js/eslint-plugin-import#2452]
this plugin validate `import` syntax, 
does it also linting `require()` and `webpack aliases` syntax as [require-path-exists plugin](https://www.npmjs.com/package/eslint-plugin-require-path-exists) does?

**Comment by ljharb** [comment]
Yes.

**Comment by eng-dibo** [comment]
nice, please update your docs

**Comment by ljharb** [comment]
Which docs need updating? https://github.com/import-js/eslint-plugin-import#resolvers discusses webpack aliases, and https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md#importno-unresolved discusses the `commonjs` option.

Perhaps, please read the docs?
