### ISSUE TITLE
RFC: Respect TypeScript baseUrl in no-useless-path-segments

### ISSUE THREAD

**Issue by tpict** [import-js/eslint-plugin-import#2455]
This is something that's been bugging me in a project I'm working on. Given some directory structure
```
my-project
├── app.ts
└── helpers
    └── index.ts
└── pages
    └── about
        └── index.ts
```

and a `baseUrl` of `my-project`, It's common to see imports from e.g. `my-project/pages/about/index.ts` that look like

```ts
import { helpMe } from "../../helpers";
```

which could instead by written as

```ts
import { helpMe } from "helpers";
```

with the advantage that the file can be relocated without breaking imports (and it saves a few characters).

- Is this already possible with any of the built-in rules?
- If I were to implement an enforcement of this style, where would be the best place to put it? I'm thinking of an opt-in option in `no-useless-path-segments`.

**Comment by ljharb** [comment]
It's possible if you use an import resolver that handles the aliases, yes.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript
