### ISSUE TITLE
import/no-cycle does not work for typescript files

### ISSUE THREAD

**Issue by ilyub** [import-js/eslint-plugin-import#2462]
I used the first sample from here:
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md
but changed extension for files from .js to .ts.

My eslint configuration:
```
.eslintrc.js
module.exports = {
  plugins: ["import"],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2017,
    project: "tsconfig.json",
    sourceType: "module"
  },
  rules: {
    "import/no-cycle": "error",
  },
};
```

For .ts files the rule does not work.
But when I change extension back to .js it works again.

NOTE:
I made sure that .ts files are actually checked by eslint by adding code that triggers core eslint rule.
So, I am sure that the issue is not because .ts files are not checked.

**Comment by JounQin** [comment]
close in favor of https://github.com/import-js/eslint-import-resolver-typescript
