### ISSUE TITLE
addition to rule: import/no-duplicates

### ISSUE THREAD

**Issue by snewcomer** [import-js/eslint-plugin-import#2470]
The proposal here is to improve this rule and handle inline type modifiers

```
import { type Foo } from 'T';
import { type Bar } from 'T';
//^^^^^^^^^^^^^^^^^^^^ Error: duplicate import from module 'T' (import/no-duplicates)
```

Fixer
```
import { type Foo,  type Bar } from 'T';
```

ref https://github.com/import-js/eslint-plugin-import/issues/2469 and https://github.com/typescript-eslint/typescript-eslint/pull/5050#discussion_r889606802

**Comment by ljharb** [comment]
I absolutely agree this should be autofixable by no-duplicates.

**Comment by nerdjfpb** [comment]
I'm new to the codebase, but can I take this issue?

**Comment by snewcomer** [comment]
@nerdjfpb Happy if you did!  If you don't happen to get to it by this weekend, I'll plan on jumping in.

**Comment by nerdjfpb** [comment]
Some personal issue came up and I don't think I can jump on this in next 1/2 week. I think you can start working on this @snewcomer
