### ISSUE TITLE
add support for Node.js ESM resolution

### ISSUE THREAD

**Issue by piranna** [import-js/eslint-plugin-import#2480]
Similar to https://github.com/weiran-zsd/eslint-plugin-node/pull/4, add support on `import/no-unresolved` rule for packages using `exports` field instead of `main`. At this moment, https://github.com/import-js/eslint-plugin-import/blob/main/resolvers/node/index.js only supports `main` and (non standard) `module` fields.

**Comment by ljharb** [comment]
This will be done automatically once the resolve package supports exports. It won’t be done until then.

**Comment by piranna** [comment]
At `jest` it was needed to be added explicitly on Jest v28 after one year and a half waiting it to be added to `resolve` package, seems it's abandoned...

**Comment by ljharb** [comment]
@piranna it's not abandoned (i'm the maintainer), and yes, i'm aware jest decided not to wait. However, once `resolve` supports it, jest will likely switch back to using it.
