### ISSUE TITLE
[import/no-extraneous-dependencies] - Feature request: More options to whitelist dependencies

### ISSUE THREAD

**Issue by ilyub** [import-js/eslint-plugin-import#2486]
Motivation:

I am having quasar project.
I know for sure that quasar already adds "@vue/test-utils" dependency.
So, I don't want to include "@vue/test-utils" explicitly, because it may install wrong "@vue/test-utils" version.
Also, I don't want to use "@vue/test-utils": "*" because it creates problems in combination with "overrides" section in package.json.

Ideally, I would prefer to configure "import/no-extraneous-dependencies" so that it ignores "@vue/test-utils" dependency.

This can be "ignore" or "whitelist" option.

Or more sofisticated "allowSubdependencies" option:
```json
{
  "allowSubdependencies": [
    {
      "peerDependency": "quasar",
      "subdependencies": ["@vue/test-utils"]
    }
  ]
}
```
This option tells that if project has "quasar" dependency then it should assume that "@vue/test-utils" is also available.

**Comment by ljharb** [comment]
If you don't install it explicitly, then quasar (i have no idea what that is) might install the wrong version.

If it's something you require/import, you MUST explicitly depend on it. If quasar wants to ensure this, it should have a peer dep on `@vue/test-utils`, which would force you to explicitly specify it.

**Comment by vincenthend** [comment]
Hi, we have a similar requirement where we need to allow whitelisting some dependencies.

We are currently implementing a microfrontend architecture. Our current architecture looks like below


For local development purpose, each sub application already got the dependencies (e.g. react) from the host application's main package.

If we decided to add the dependencies to each application
