### ISSUE TITLE
Not working with vscode-eslint and yarn 3

### ISSUE THREAD

**Issue by brunomacf** [import-js/eslint-plugin-import#2487]
I'm not sure if this is an issue with eslint-plugin-import or vscode-eslint itself but i created this repo https://github.com/brunomacf/vscode-eslint-yarn-berry reproducing the issue. If i open `src/index.ts` in vscode i don't see any lint errors (i do see the correct errors when i totally remove the eslint-plugin-import settings from `.eslintrc.js` config file). But if i run lint manually through `yarn lint` i see the lint errors just fine (bellow is a screenshot showing on the left the result of `yarn lint` on the left and on the right vscode showing no lint errors). Any ideas? PS.: I created a similar issue in vscode-eslint [here](https://github.com/microsoft/vscode-eslint/issues/1494)

![Captura de Tela 2022-07-03 às 17 38 08](https://user-images.githubusercontent.com/2754593/177056630-d353ec52-0be6-46ef-8038-bbc78e0225cb.png)

**Comment by ljharb** [comment]
If it works on the command line, then the editor is the thing that's broken.

In general, PnP breaks a ton of things, including the way modules are resolved, so it's highly likely that vscode isn't pulling in the PnP.js hacks that attempt to fix them. I'll close in favor of the vscode-eslint issue.
