### ISSUE TITLE
[import/extensions] Getting ESLint warning for `import/extensions`

### ISSUE THREAD

**Issue by jmcombs** [import-js/eslint-plugin-import#2488]
I am triggering the [eslint(import/extensions)](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md) when I am trying to import service `import { WebexService } from '../services/webex.js';`. I am using NodeJS, ES6, ESLint, Airbnb Style and Prettier.

I store my ESLint configuration in `package.json`. I have tried the following settings to get the error to go away and it doesn't:

```json
    "settings": {
      "import/extensions": [
        "always",
        {
          "ignorePackages": true
        }
      ]
    }
```

```json
    "settings": {
      "import/extensions": [
        "warn",
        "always",
        {
          "ignorePackages": true
        }
      ]
    }
```

```json
    "settings": {
      "import/extensions": [
        {
          "ignorePackages": true
        }
      ]
    }
```

Here is my `package.json`:

```json
{
  "devDependencies": {
    "eslint": "^8.18.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.7.1"
  },
  "eslintConfig": {
    "extends": [
      "airbnb-base",
      "plugin:import/recommended",
      "plugin:prettier/recommended"
    ],
    "env": {
      "node": true
    },
    "settings": {
      "import/extensions": [
        "warn",
        "always",
        {
          "ignorePackages": true
        }
      ]
    }
  },
  "prettier": {
    "printWidth": 100,
    "singleQuote": true,
    "arrowParens": "always",
    "trailingComma": "all"
  }
}
```

I could really use some help on what I am doing wrong. Thank you!

**Comment by ljharb** [comment]
`import/extensions` is a rule, you don't configure it in settings, you configure it in "rules".

**Comment by jmcombs** [comment]
Thank you, @ljharb. That resolved my problem. I honestly have spent my entire day reading both the [Main Docs](https://github.com/import-js/eslint-plugin-import/tree/v2.26.0#eslint-plugin-import) and [import/extensions - Ensure consistent use of file extension within the import path](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md) and did not extrapolate that requirement. I'll chalk it up to be being new at this. Would you be apposed to me submitting a PR to the latter document updating the two references in that document to include `"rules" {}`?  

Current:

```js
"import/extensions": [
  <severity>,
  "never" | "always" | "ignorePackages",
  {
    <extension>: "never" | "always" | "ignorePackages"
  }
]
```

Proposed

```js
"rules": {
  "import/extensions": [
    "always",
    {
      "ignorePackages": true
    }
  ]
}
```

Either way, I appreciate your prompt response in helping me resolve this.

**Comment by ljharb** [comment]
Sure, given that there's both a rule and a setting called "import/extensions", that seems useful to clarify.

Yes, in a rule, the first option must always be a severity - either off/warn/error, or 0/1/2.
