### ISSUE TITLE
ESLint returns "import/no-extraneous-dependencies" with Electron

### ISSUE THREAD

**Issue by HasanTheSyrian** [import-js/eslint-plugin-import#2489]
ESLint gives this error when Electron is under dependencies instead of devDependencies which is inaccurate.

![image](https://user-images.githubusercontent.com/69906596/177287402-a3a5c524-ad77-4714-a236-9aafa1aa32e6.png)

**Comment by ljharb** [comment]
By default, everything is assumed to only be allowed to import runtime deps. You need to configure which files are allowed to reference dev deps.
