### ISSUE TITLE
Add support for Module Federation Plugin

### ISSUE THREAD

**Issue by ScriptedAlchemy** [import-js/eslint-plugin-import#2492]
I see you support externals. It would be great if this also supported Module Federation where remotes are listed. Any of those keys should not throw unresolved lint errors since it would behave similar to an external import

**Comment by ljharb** [comment]
Import resolvers are a plugin system; you can write one yourself for this and use it just fine.

Remote imports aren't a standard part of node nor a good idea in general, so it's not something the plugin will likely ever support by default.

**Comment by ScriptedAlchemy** [comment]
Wouldn’t go as far to say it’s not a good idea. 
but should be used probbbely and by knowing what’s going to happen. I’ll take a look and see if I can write a plugin for this package 📦

**Comment by gyrgy** [comment]
I ended up adding the remote federated modules manually into the core modules, based on the documentation:
`import/core-modules: ['pathtToRemote/module' ]`
This is the path how I importing them.
There might be better ways and I'm happy to hear about them.
