### ISSUE TITLE
Collaborate on `TypeScript` related things on this repository?

### ISSUE THREAD

**Issue by JounQin** [import-js/eslint-plugin-import#2501]
Hi, @ljharb 

I'm now the maintainer of https://github.com/import-js/eslint-import-resolver-typescript, we just moved it to `import-js` org recently. And there are a lot of `TypeScript` only related [issues](https://github.com/import-js/eslint-plugin-import/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Atypescript) in this repository, maybe I can help to collaborate, how do you think?

**Comment by ljharb** [comment]
That'd be great! PRs are most welcome :-)

**Comment by JounQin** [comment]
> That'd be great! PRs are most welcome :-)

@ljharb

Some issues can be closed directly in favor of `eslint-import-resolver-typescript`, another thing would be adding a section about TypeScript resolver.

I’m here also asking for permission to maintain the issues at least, how do you think?

**Comment by ljharb** [comment]
Sure, I've given you Triage access.
