### ISSUE TITLE
[no-extraneous-dependencies] no error when `@types` package not listed in dependencies

### ISSUE THREAD

**Issue by DetachHead** [import-js/eslint-plugin-import#2507]
```ts
import eslint from 'eslint'
```
```json
"dependencies": {
  "eslint": "^8.13.0",
}
```

this is invalid for a `.ts` file as it needs `@types/eslint` to be in the `dependencies` (or devDependencies`) as well

**Comment by JounQin** [comment]
I don't think `@types/eslint` is **required**, it **is valid**, it resolves `eslint` package correctly instead of `@types/eslint`, and TypeScript has told you to install `@types/eslint`.

**Comment by DetachHead** [comment]
the reason i use the `no-extraneous-dependencies` rule is to prevent cases where i accidentally install a package locally but forget to add it to `package.json`, which results in a successful build locally but a failed build in the CI.

the same thing happens when there's a missing `@types` package. it may work at runtime but typescript will fail to compile it in the CI because of the missing package. i would like this problem to be picked up locally by eslint for the same reason.

**Comment by JounQin** [comment]
But `eslint` is already in `dependencies`.

If you want all dependencies resolve `.ts`(including `.d.ts`), you can use [`import/extensions`](https://github.com/import-js/eslint-plugin-import#importextensions) setting to enforce that.

**Comment by DetachHead** [comment]
@JounQin that doesn't work
```js
// .eslintrc.js
module.exports = {
    rules: {
        'import/no-extraneous-dependencies': 'error',
        'import/extensions': 'error'
    },
    settings: {
        'import/extensions': ['.js', '.d.ts', '.ts'],
    }
}
```
```ts
// index.ts
import { Linter } from 'eslint' // no error
```
```json
// package.json
{
    "dependencies": {
        "eslint": "^8.13.0"
    }
}
```

is there something i'm missing?

**Comment by JounQin** [comment]
If you want always TypeScript files, you should omit `.js`.

`'import/extensions': ['.d.ts', '.ts']`

**Comment by ljharb** [comment]
It would be better to use `import type` to import types.

**Comment by JounQin** [comment]
`eslint-plugin-import` can only resolves one filepath at a time, see https://github.com/import-js/eslint-plugin-import/tree/main/resolvers#resolvesource-file-config---found-boolean-path-string-

So it can only be `.js` or `.ts`, not both at the same time.

**Comment by maslade** [comment]
Some of the comments are misunderstanding the issue. @DetachHead is *not* trying to import types, but compiled JS. The error is saying that the *types* should be dependencies, which is not correct. CI needs types to build, but that's why CI installs dev dependencies. Production use of the repo (ie when it's installed under another project) only needs `eslint` (the runtime package) and does not require `@types/eslint`.

I was up against this and found that simply running `ESLint: Restart ESLint Server` in VSCode fixed it. I think it was just a caching issue.
