### ISSUE TITLE
errant linter error when encountering an underscore as numeric separator

### ISSUE THREAD

**Issue by waffledonkey** [import-js/eslint-plugin-import#2512]
Firstly, thank you -- and the entire eslint community -- for your efforts; amazing.

I had occasion to import camelcase-keys and I take 4 separate import linter errors using the recommended ruleset.  I dug into it and on line 15 of index.js they are [using an underscore as a numeric separator ](https://github.com/sindresorhus/camelcase-keys/blob/main/index.js#L15) which is completely [valid](https://www.javascripttutorial.net/es-next/javascript-numeric-separator/).  As they only have a 6 digits in the number in question, I'm not personally seeing the value in the choice to use an underscore as a numeric separator, but it's not really for me to say.  I did [notify them of the issue](https://github.com/sindresorhus/camelcase-keys/issues/95) and said I'd notify you as well.  In the meantime, I can continue to disable the four rules as shown below.

Cheers

```
// eslint-disable-next-line import/namespace, import/default, import/no-named-as-default, import/no-named-as-default-member
import camelcaseKeys from 'camelcase-keys' 
```

**Comment by JounQin** [comment]
Please provide a github repository that can reproduce the problem.

 [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by waffledonkey** [comment]
that's completely fair; sorry about that.  here's a [repo](https://github.com/waffledonkey/eslint-import-2512) as requested

**Comment by ljharb** [comment]
You have ecmaVersion 2020, but numeric separators are in ES2021.

**Comment by waffledonkey** [comment]
omg.  I am so sorry.  now i need to go unring the bell at camelcase-keys.  thanks again!
