### ISSUE TITLE
Upgrade debug dependency to 4.3.1+ or 3.2.7+

### ISSUE THREAD

**Issue by apupier** [import-js/eslint-plugin-import#2513]
currently on 2.6.9 https://github.com/import-js/eslint-plugin-import/blob/0ef8cbaab5ba0789a6e1b716317b000b55ee4555/package.json#L104

but `npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)`

**Comment by ljharb** [comment]
This is a non-problem; like most CVEs, it doesn’t apply to the way it’s used her3.
