### ISSUE TITLE
[HELP] Style guide

### ISSUE THREAD

**Issue by WarrenMfg** [import-js/eslint-plugin-import#2517]
Hello, do I have to add the style guide rules manually. They don't seem to be working for me. 

For example, I have an anonymous default export but I'm not getting an error or warning associated with `import/no-anonymous-default-export`. 

I'm running Node v16.15.0 and working in TypeScript if that matters. Below is my rc file:

```js

module.exports = {
  env: {
    node: true,
    jest: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/recommended',
    'plugin:import/typescript',
    'plugin:prettier/recommended',
  ],
  overrides: [
    // jest
    {
      files: ['*.test.ts'],
      plugins: ['jest'],
      extends: ['plugin:jest/all'],
      rules: {
        'jest/no-hooks': 'off',
        'jest/prefer-lowercase-title': 'off',
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['import'],
  settings: {
    'import/extensions': ['.ts'],
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
  rules: {
    // prettier
    'prettier/prettier': 'warn',
    // everything else
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        argsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    // 'import/no-anonymous-default-export': 'error', <-- This is what I have to manually turn on. Is that normal?
  },
  ignorePatterns: ['dist'],
};

```

And here are my eslint dev dependencies:

```json

    "@typescript-eslint/eslint-plugin": "^5.31.0",
    "@typescript-eslint/parser": "^5.31.0",
    "eslint": "^8.21.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.4.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^26.7.0",
    "eslint-plugin-prettier": "^4.2.1",

```

Thanks in advance!

**Comment by JounQin** [comment]
https://antfu.me/posts/why-reproductions-are-required

**Comment by JounQin** [comment]
> 'import/no-anonymous-default-export': 'error', <-- This is what I have to manually turn on. Is that normal?

I don't understand what's your meaning, you want some rules to be enabled, and then you need to enable it, what's the problem.

The `recommended` config does not do much, you can just view https://github.com/import-js/eslint-plugin-import/blob/main/config/recommended.js

Maybe you are just confused like #2515?

**Comment by WarrenMfg** [comment]
Yes, that answers my question, thank you. It was unclear to me which rules were on or off by default when using `recommended`. Now I understand they are not all on by default. Thank you.
