### ISSUE TITLE
Is sort imports by length supported?

### ISSUE THREAD

**Issue by sarat1669** [import-js/eslint-plugin-import#2520]
Is it possible to sort by length along with grouping?

Before:
```
import Head from "next/head";
import AuthModal from '../../../../../components/Auth/AuthModal';
import { useRouter } from 'next/router';
import Footer2 from "../../../../../components/Footer/Footer2";
import Breadcrumbs from '../../../../../components/Breadcrumbs';
import ImageExplorer from '../../../../../components/brands/Style/ImageExplorer';
import HeaderBrands from "../../../../../components/Header/HeaderBrands";
import moment from 'moment';
import * as StyleCatalogService from '../../../../../services/style-catalog.service';
import { SuperExpandedStyle as IStyle } from '../../../../../types';
import React, { FC, ReactNode, useState } from "react";

```

After:
```
import moment from 'moment';
import Head from "next/head";
import { useRouter } from 'next/router';
import React, { FC, ReactNode, useState } from "react";

import Footer2 from "../../../../../components/Footer/Footer2";
import Breadcrumbs from '../../../../../components/Breadcrumbs';
import AuthModal from '../../../../../components/Auth/AuthModal';
import { SuperExpandedStyle as IStyle } from '../../../../../types';
import HeaderBrands from "../../../../../components/Header/HeaderBrands";
import ImageExplorer from '../../../../../components/brands/Style/ImageExplorer';
import * as StyleCatalogService from '../../../../../services/style-catalog.service';
```

**Comment by JounQin** [comment]
I'm personally fine with a PR for this proposal.

**Comment by ljharb** [comment]
Related to #2401, perhaps.

By length of what? The import names list? The specifier? Both?

It seems like it would be a supremely terrible user experience to have to resort your imports any time you add, remove, or rename a default or named import. I'm not sure I see the value of this sorting mode.

**Comment by JounQin** [comment]
@ljharb I guess it should be the length of the importee path.

**Comment by ljharb** [comment]
If it's the length of the specifier, then the lines will still not be in a nice aesthetic pyramid (due to varying lengths of the specifiers), so what's the point of that sorting method?

**Comment by JounQin** [comment]
I reread the issue content, it seems to be the whole length of the import statement.

**Comment by JounQin** [comment]
> It seems like it would be a supremely terrible user experience to have to resort your imports any time you add, remove, or rename a default or named import. I'm not sure I see the value of this sorting mode.

It seems to be true to me now.

But I was finding a rule to ensure the order of import names list, so that it could be easier reduce conflict on merging. (I don't remember if there is already a rule proposal for it, if not I'd like to create one. HDYT?)

And for this issue, I agree we don't want to resort when modifying the import statement.

**Comment by ljharb** [comment]
I think eslint's own https://eslint.org/docs/latest/rules/sort-imports rule handles that.

Seems like all (three) of us are in agreement.

**Comment by JounQin** [comment]
@ljharb Does sort-imports support TypeScript?

**Comment by ljharb** [comment]
If not, I'd expect the TS eslint plugin to provide a replacement.

**Comment by JounQin** [comment]
> If not, I'd expect the TS eslint plugin to provide a replacement.

cc @bradzacher

**Comment by bradzacher** [comment]
The core eslint rule will support most TS usecases, but it won't support "import equals" and it won't allow different treatment of type/value imports.

That being said - there are so many different sorting rules and plugins honestly I wouldn't want to add an extension rule to ts-eslint.

There are better alternatives like `import/order` or `simple-import-sort/imports` for example.

We already made this mistake with the `no-duplicate-imports` rule (`import/no-duplicates` is a much better version, and we'll be deleting our version in the next major).

**Comment by ljharb** [comment]
I think the main feature in the core rule that we don’t have is sorting the import names themselves.

**Comment by JounQin** [comment]
I tried `simple-import-sort/imports` a few days ago, and found it's much lack of features, also the order of imports sometimes matter due to side effects, so we ended with giving up to use `simple-import-sort/imports`, so I still think we should include that feature in this rule in case `simple-import-sort` is less popular then `import`.

**Comment by JounQin** [comment]
Should I raise a new issue for discussion?

**Comment by ljharb** [comment]
Sure. I think the important first task will be to thoroughly audit the core rule, and figure out what the actual missing feature comparisons are.

**Comment by bradzacher** [comment]
> also the order of imports sometimes matter due to side effects

I think I just threw up in my mouth a little.

Jokes aside if modules with side-effects are common then the codebase shouldn't consider a sorting rule ever.

At meta we have various tooling which pretty much prevents side-effects from working, which keeps the codebase nice and pure and allows us to indiscriminately sort the entire codebase (100s of thousands of files).

---

> simple-import-sort/imports ... and found it's much lack of features

I think the lack of features is a feature - I liked that I could just turn it on and have a good sort without any config effort. Opinionated defaults are a good thing sometimes!

**Comment by JounQin** [comment]
> Jokes aside if modules with side-effects are common then the codebase shouldn't consider a sorting rule ever.

We have legacy projects and want to migrate to modern toolchains, unfortunately.

> I think the lack of features is a feature - I liked that I could just turn it on and have a good sort without any config effort. Opinionated defaults are a good thing sometimes!

I'd love use it in my personal projects, but for business projects, I just can't. 😅

(I just hate to use Angular in my business projects, it use NgModule which may be the root cause of side effects. 😭)

**Comment by ljharb** [comment]
@bradzacher i think that there's only two reasonable positions to take:
1. every module can have side effects, and nothing can ever safely be sorted
1. only modules without bindings are expected to have side effects, and anything else can be safely sorted (but nothing can be moved across a side-effecting import)

This plugin assumes the latter.
