### ISSUE TITLE
`import/default` broken under TypeScript 4.8

### ISSUE THREAD

**Issue by boris-petrov** [import-js/eslint-plugin-import#2533]
I updated my TypeScript version to 4.8.2 (from 4.7.4) and started getting a bunch of bogus `import/default` warnings. I see that it's because of a decorator:

```ts
@someDecorator
export default class Foo {}
```

Importing this leads to a `import/default` warning. That could be related to TypeScript 4.8's change to [decorator handling](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees)?

**Comment by ljharb** [comment]
Very likely - we'll almost certainly have to update our AST node visitors to handle TS 4.8's new approach.

**Comment by boris-petrov** [comment]
After updating `@typescript-eslint` packages to `5.36.1` the error is gone so I'll close the issue, thanks!

**Comment by ljharb** [comment]
Glad to hear it!
