### ISSUE TITLE
How to restrict imports from same tsconfig project

### ISSUE THREAD

**Issue by kristiannotari** [import-js/eslint-plugin-import#2534]
Hello, I have a monorepo with two packages and two different tsconfig, in a directory structure like:
```
packages/
├─ a/
│  ├─ tsconfig.json
│  ├─ package.json
├─ b/
│  ├─ tsconfig.json
│  ├─ package.json
```

I'd like for files in package `a` to be able to only import files relative to package `a`, and to not be able to import, let's say:

```typescript
import * as b from "../b"
```

The `no-relative-parent-imports` does that, but also forces me to use that guideline for every import inside both `a` and `b` internal folder structures, which I'd like to have free from more eslint rules.

Is this something impossible? Or something possible that has a simple solution that I can't find anywhere?

**Comment by ljharb** [comment]
Use eslint overrides to configure the rule just for `a`.

**Comment by kristiannotari** [comment]
I need both `a` and `b` to not have imports directly referring to files in the other package. But I want complete freedom over relative imports within the same package, so using `no-relative-parent-imports` inside the packages is a no go at the moment.

**Comment by JounQin** [comment]
`overrides` separately for `a` and `b`? Actually, I'm quite sure what you want to achieve.

A minimal but runnable reproduction would help.

https://antfu.me/posts/why-reproductions-are-required

**Comment by kristiannotari** [comment]
Ok while I was creating a repro I hit the "rootDir" option in tsconfig file which does just what I wanted, giving me a typescript error if it finds imports from relative paths outside the current tsconfig project.
