### ISSUE TITLE
New release which includes the `distinctGroup` option in `order`

### ISSUE THREAD

**Issue by kamil-basebuild** [import-js/eslint-plugin-import#2539]
I saw that the `distinctGroup` option has been added to `order` in commit [998655b1438c9718403ae876163b739c57f658ca](https://github.com/import-js/eslint-plugin-import/commit/998655b1438c9718403ae876163b739c57f658ca). I was wondering when a new release that includes this commit might be released, as it's critical to what I'm trying to achieve.

I set up a number of custom `pathGroups` for different `external` dependencies so that they stay in this custom order despite using alphabetical sorting, but with `"newlines-between": "always"` empty lines are being added between the different `external` dependencies not just between different categories (e.g. `external` and `internal`), which I believe is something `distinctGroup: false` is supposed to address.

My config:

```
    "import/order": [
      "warn",
      {
        pathGroups: [
          { pattern: "react", group: "external", position: "before" },
          {
            pattern: "*next/**",
            group: "external",
            position: "before",
            patternOptions: { partial: true },
          },
          { pattern: "prop-types", group: "external", position: "before" },
          { pattern: "@mui/**", group: "external", position: "before" },
        ],
        pathGroupsExcludedImportTypes: ["react"],
        groups: [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type",
        ],
        "newlines-between": "always",
        alphabetize: { order: "asc" },
      },
    ]
```

Current result:
```
import { useState } from "react";

import PropTypes from "prop-types";

import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
```

Desired result:
```
import { useState } from "react";
import PropTypes from "prop-types";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
```

**Comment by kamil-basebuild** [comment]
Ideally it would be possible to specify whether a given `pathGroup` has an empty line after it or not, but I'm not sure how difficult something like this would be to achieve.

**Comment by ljharb** [comment]
I think `distinctGroup` would handle that, without having to cover both "new line before" and "new line after".

Releases aren't done on any particular schedule.

**Comment by lewxdev** [comment]
@kamil-basebuild Can you share the rest of your config and version number for this plugin? For my use case, I'm actually trying to separate out the groups exactly like that but it's no longer enforcing the rule

**Comment by kamil-basebuild** [comment]
> @kamil-basebuild Can you share the rest of your config and version number for this plugin? For my use case, I'm actually trying to separate out the groups exactly like that but it's no longer enforcing the rule

Hi @lewxdev, sorry for the late reply. The included my whole config in my original post. I'm using version `^2.26.0`. Hope it works for you!

**Comment by josemigallas** [comment]
Any estimates on when will this be available? Any workaround config in the meantime?

**Comment by ljharb** [comment]
No estimates or workaround.

**Comment by inker** [comment]
The [readme](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#distinctgroup-boolean) file is misleading, because this functionality hasn't been released.

**Comment by ljharb** [comment]
@inker that's only if your expectations are flawed. Every single repo on github works this way - master/main is for unreleased changes, and you have to check the tag for the latest version if you want to see the released repo contents.

**Comment by ErAz7** [comment]
@ljharb as @inker mentioned, readme is very misleading on main. Not sure where you bring the claim `Every single...` from, but from what I've seen, `main/master` readme has always (at least mostly) been the latest usable (public/released/...) version

This misleading caused some time to figure out and was really unexpected to see you claim it's like this on `Every single repo!`

**Comment by ljharb** [comment]
@ErAz7 that’s how everything works. Perhaps the projects your familiar with release frequently enough that you haven’t run into it, but your anecdotal experience doesn’t match how github actually works, and has always worked.
