### ISSUE TITLE
Support query parameters in `import/no-unresolved`

### ISSUE THREAD

**Issue by lachrist** [import-js/eslint-plugin-import#2562]
Passing parameters to a module can be done via the import url -- cf: https://flaming.codes/en/posts/es6-import-with-parameters. So `import "./lib.mjs?foo=bar` will cause node to load `./lib.mjs` but it will be flagged by the `import/no-unresolved` rule because the file `./lib.mjs?foo=bar` does not exist.

**Comment by ljharb** [comment]
This plugin currently does not yet support native ESM, and node does *not* support query parameters in transpiled ESM.

It's a good idea regardless to never use a query string in a specifier URL, but either way, this plugin will support it once `resolve` supports ESM.

**Comment by lachrist** [comment]
Hi @ljharb, thanks for your answer. If you have time, could clarify two points?

> This plugin currently does not yet support native ESM, and node does not support query parameters in transpiled ESM.

Are you saying that `eslint-plugin-import` relies on a transpiler to transform esm modules into commonjs modules? And since commonjs modules cannot be imported with query parameters, making `eslint-plugin-import` support query parameters is hard?

> It's a good idea regardless to never use a query string in a specifier URL

Could you explain why?

**Comment by ljharb** [comment]
I’m saying that eslint-plugin-import still expects a world where all ESM is transpiled into CJS.

Sure - a query string suggests that you could get a different module from what conceptually would be expected to be the same specifier. Modules aren’t supposed to be dynamic, they’re supposed to be static.

**Comment by lachrist** [comment]
Oke, thanks for your time!
