### ISSUE TITLE
import text!templates/template.html -> ESLint unable resolve path

### ISSUE THREAD

**Issue by egrekov** [import-js/eslint-plugin-import#2563]
There are imports in .js
```js
import BaseItemView from 'views/base_views/item_view';
import Template from 'text!templates/content/template.html';
```
Configure ESLint like this:
```
"import/resolver": {
    "alias": [
        ["text!", "scripts/"]
    ],
    "node": {
        "extensions": [".js", ".jsx", ".ts", ".tsx"],
        "moduleDirectory": ["node_modules", "scripts/"]
    }
}
```
Nothing works with the templates, the error does not disappear, maybe you can also tweak something to make the text! did it resolve?
Thanks in advance.

**Comment by ljharb** [comment]
The ! syntax is webpack-specific nonstandard stuff; you need the webpack resolver to handle it.

**Comment by egrekov** [comment]
> The ! syntax is webpack-specific nonstandard stuff; you need the webpack resolver to handle it.
I solved it this way, thanks
```
"settings": {
    "import/resolver": {
        "webpack": {
            "config": "webpack.dev.js"
        }
    }
}
```
