### ISSUE TITLE
Definition for rule 'import/consistent-type-specifier-style' was not found in 2.26.0

### ISSUE THREAD

**Issue by h0adp0re** [import-js/eslint-plugin-import#2567]
Hello! I had this error when using the latest version (`2.26.0`) of your package:
```
Definition for rule 'import/consistent-type-specifier-style' was not found.
```
After checking `node_modules`, the rule was indeed not even mentioned anywhere inside the package. What gives?

**Comment by simmo** [comment]
@h0adp0re I was wondering the same but it is marked as Unreleased currently in the changelog - https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#unreleased

**Comment by h0adp0re** [comment]
Good catch. The latest release according to their GH releases is `2.25.2`. Yet, I'm able to access `2.26.0` via npm. That is confusing if `2.26.0` shouldn't be available yet.

**Comment by ljharb** [comment]
Everywhere on Github, you need to look at the docs for the tagged version you're using, and not those on master/main.

There's no explicit schedule for releases, nor any blockers. It will be released when I have the time both to do the release, and also to field any bug reports that come in after it's published.

**Comment by h0adp0re** [comment]
Understood. That's a good point about only looking at the tagged version I'm using, I have not paid any mind to that in the past!

Thanks for replying and explaining.
