### ISSUE TITLE
When is scheduled the next release

### ISSUE THREAD

**Issue by pierreinglebert** [import-js/eslint-plugin-import#2579]
Hello,
There are some features that I'd really like to use in the main branch that are not yet released.
So my question is : when the next release is scheduled ? Do you need help for that ?

**Comment by ljharb** [comment]
No releases are ever scheduled.

Duplicate of #2571. Duplicate of https://github.com/import-js/eslint-plugin-import/issues/2539. Duplicate of https://github.com/import-js/eslint-plugin-import/issues/2567.
