### ISSUE TITLE
Jest encountered an unexpected token from vue 2 application

### ISSUE THREAD

**Issue by ashif25** [import-js/eslint-plugin-import#2581]
![image](https://user-images.githubusercontent.com/40867499/198351867-587007ea-4017-4ed8-a707-927ebe5183dc.png)
I'm trying to update the node version from 12 to 16 and all node packages. I'm able to build successfully and clean up errors from
ESLint but while running jest most of the test failed due to that import underscore issue.

**Comment by ljharb** [comment]
This is jest failing, not eslint, so you'll need to file an issue on jest.

Either way, I'd suggest updating packages one at a time, and jumping from node 12 to 14 to 16, instead of trying to do it all at once.

**Comment by ashif25** [comment]
> This is jest failing, not eslint, so you'll need to file an issue on jest.
> 
> Either way, I'd suggest updating packages one at a time, and jumping from node 12 to 14 to 16, instead of trying to do it all at once.
Could you please direct me any places where I can post?

**Comment by ljharb** [comment]
@ashif25 jest's repo is https://github.com/facebook/jest
