### ISSUE TITLE
eslint 8 throwing error in CI

### ISSUE THREAD

**Issue by snewcomer** [import-js/eslint-plugin-import#2594]
> Error: Error while loading rule 'import/no-unused-modules': Failed to load plugin 'import' declared in '.eslintrc': Cannot find module '/home/runner/work/eslint-plugin-import/eslint-plugin-import/node_modules/eslint-plugin-import/lib/index.js'. Please verify that the package.json has a valid "main" entry

> Occurred while linting /home/runner/work/eslint-plugin-import/eslint-plugin-import/tests/files/just-json-files/invalid.json
[71](https://github.com/import-js/eslint-plugin-import/actions/runs/3449533983/jobs/5757534657#step:5:72)

See https://github.com/import-js/eslint-plugin-import/actions/runs/3449533983/jobs/5757534657#step:5:66

Happened within the last 4 days.  Last versioned release of eslint was 8 days ago.  Node also release 8 days ago.

**Comment by ljharb** [comment]
npm 9 was promoted to "latest" in that timeframe.

I won't be able to properly investigate until next week.
