### ISSUE TITLE
Is the current main branch in sync with the package in npm?

### ISSUE THREAD

**Issue by alshdavid** [import-js/eslint-plugin-import#2596]
I am looking to use a feature documented in the repo, specifically the `includeTypes` option under the [no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) rule.

When implementing the option, I got a schema validation error on the `no-extraneous-dependencies` plugin's options.

Upon further inspection, the [code from the latest version in npm](https://www.runpkg.com/?eslint-plugin-import@2.26.0/lib/rules/no-extraneous-dependencies.js#239) (version 2.26.0 at the time of writing) seems to differ from [the source code under main](https://github.com/import-js/eslint-plugin-import/blob/main/src/rules/no-extraneous-dependencies.js#L262).

Is the npm package up to date?

Should I be installing this with?

```
npm install --save-dev eslint-plugin-import
```

**Comment by ljharb** [comment]
Like most github repos, the default branch indeed often contains unreleased things.

Anything not published isn't consumable yet. This repo happens to track unreleased items here: https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#unreleased

**Comment by alshdavid** [comment]
Got ya, is there a release schedule documented anywhere?

**Comment by ljharb** [comment]
No, there's no schedule for releases, and automatic deployments would create a scenario where maintainers aren't around to handle bug reports, so that would be unwise :-)
