### ISSUE TITLE
import/no-extraneous-dependencies error when array of globs is used

### ISSUE THREAD

**Issue by Titi-layo** [import-js/eslint-plugin-import#2599]
I have the following code in my .eslintrc.json file and i get an error when i run eslint 

```
"import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": ["**/*.test.ts"]
      }
    ]
```

Not sure why this is happening, reading through the readme i expected otherwise [https://github.com/import-js/eslint-plugin-import/blob/8b0fb989ae08161499a478ab23fb10b68e3cd828/docs/rules/no-extraneous-dependencies.md?plain=1#L34](https://github.com/import-js/eslint-plugin-import/blob/8b0fb989ae08161499a478ab23fb10b68e3cd828/docs/rules/no-extraneous-dependencies.md?plain=1#L34)

Error i get is `xxxxxx should be listed in the project's dependencies, not devDependencies.  import/no-extraneous-dependencies`

**Comment by ljharb** [comment]
In what file do you get the error?

**Comment by Titi-layo** [comment]
In an `index.test.tsx` file

**Comment by ljharb** [comment]
That file doesn't match your glob, which only checks for `.ts` files, not `.tsx` files.

**Comment by Titi-layo** [comment]
Oh I see!  For some reason, I had assumed it'd treat `.ts `and `.tsx` files the same :weary: . I changed the glob to the code below :point_down: and i no longer see the error anymore, Thank you 

```
"import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": ["**/*.test.tsx"]
      }
    ]
```
