### ISSUE TITLE
import/extensions rule not working correctly with Typescript absolute paths and eslint-import-resolver-typescript

### ISSUE THREAD

**Issue by elliason** [import-js/eslint-plugin-import#2610]
I have standard configuration eslint with typescript. 
The import/extensions rule is configured this way:
`'import/extensions': [
            'error',
            'ignorePackages',
            {
                js: 'never',
                jsx: 'never',
                ts: 'never',
                tsx: 'never',
            },
        ],`
If I import package (.tsx) using relative paths the rule gives expected output (no problem)
If I import the same package via absolute path defined in tsconfig, eslint reports problem:
ESLint: Missing file extension for "~/components/button/Button"(import/extensions)

As the file is .tsx extension, and there is clearly stated that this extension should be ignored, this behavior seems as a bug.

**Comment by ljharb** [comment]
Can you provide your full eslint config?

**Comment by elliason** [comment]
`module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: {
            jsx: true,
        },
        tsconfigRootDir: __dirname,
        project: ['./tsconfig.json'],
        sourceType: 'module',
    },
    env: {
        browser: true,
        node: true,
        es2022: true,
        jest: true,
    },
    extends: [
        'eslint:recommended',
        'plugin:import/recommended',
        'plugin:import/typescript',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
        'plugin:react/recommended',
        'plugin:react/jsx-runtime',
        'plugin:react-hooks/recommended',
        'plugin:jsx-a11y/recommended',
        'prettier',
    ],
    plugins: ['@typescript-eslint', 'import', 'react', 'react-hooks', 'jsx-a11y'],
    settings: {
        /* A map from parsers to file extension arrays. If a file extension is matched,
        the dependency parser will require and use the map key as the parser instead of the configured ESLint parser. */
        'import/parsers': {
            '@typescript-eslint/parser': ['.ts', '.tsx'],
        },
        'import/resolver': {
            typescript: {
                alwaysTryTypes: true,
            },
            node: {
                extensions: ['.js', '.jsx'],
            },
        },
        // A list of file extensions that will be parsed as modules and inspected for exports.
        'import/extensions': ['.js', '.jsx', '.ts', '.tsx', 'cjs', 'mjs'],
        'import/ignore': ['\\.(coffee|scss|css|less|hbs|svg|json)$'],
        react: {
            version: 'detect',
        },
    },
    overrides: [
        {
            files: ['**/__tests__/*.?(spec)?(test).[jt]s?(x)'],
            plugins: ['jest', 'testing-library'],
            extends: ['plugin:testing-library/react', 'plugin:jest/recommended'],
            rules: {
                'import/no-extraneous-dependencies': 'off',
            },
        },
        {
            files: ['**/*.cjs'],
            rules: {
                '@typescript-eslint/no-var-requires': 'off',
            },
        },
    ],
    rules: {
        'import/default': 'off',
        'import/no-named-as-default-member': 'off',
        '@typescript-eslint/no-floating-promises': ['error', { ignoreIIFE: true }],
        eqeqeq: ['error', 'always'],
        'no-console': ['warn'],
        '@typescript-eslint/no-unused-vars': ['warn'],
    },
};
`

Here is my config. 
I have already found a missing piece that was causing the problem. It appears there needs to be a 
"**project: 'packages/*/tsconfig.json**'," for TS monorepos in **settings['import/resolver'].typescript**
So this issue can be closed.
