### ISSUE TITLE
When will the release be?

### ISSUE THREAD

**Issue by stenin-nikita** [import-js/eslint-plugin-import#2621]
Hi. The last publication was 9 months ago. I did a pull request about 4 months ago. Can I expect a release soon? Thanks.

**Comment by ljharb** [comment]
We release when we have time to triage the bug reports that it produces. There’s no schedule.

**Comment by snewcomer** [comment]
Happy to help triage and look into this bugs when you decide the time is right.  Just let me know and I can take on whatever number of them.

**Comment by ljharb** [comment]
v2.27.0 is released.
