### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by trim21** [import-js/eslint-plugin-import#2622]
It has been 9 month since last release 2.26.0, do you have a plan to make a new release to include new features?

I'm reading the ducoment and try to use option `import/order` `alphabetize.orderImportKind`, and after a while I finally realize it's not release in npm 🤔

**Comment by ljharb** [comment]
Duplicate of #2621.

I don't have any plan; I will make a release when I have time to respond to the bug reports it produces.

**Comment by ljharb** [comment]
v2.27.0 is released.
