### ISSUE TITLE
Vulnerable dependency

### ISSUE THREAD

**Issue by PeterNelsonT** [import-js/eslint-plugin-import#2625]
![image](https://user-images.githubusercontent.com/41645842/209944806-8ff10d44-f37f-4a8b-81d8-ffbd7b264a25.png)

Affected versions: including latest
Fix needed: Update tsconfig-paths to latest

**Comment by olekbaran** [comment]
Same
![image](https://user-images.githubusercontent.com/74045117/209945704-0eff0a45-e869-4dd5-991b-6816d0eaf353.png)

**Comment by PeterNelsonT** [comment]
Looks like PR is already open:
https://github.com/import-js/eslint-plugin-import/pull/2624

**Comment by P1K3N** [comment]
Also waiting for the fix

**Comment by PraveenVerma17** [comment]
Please fix this.

**Comment by air2** [comment]
I do not think this will be fixed, because they want to support node4 (which is downloaded 13 times in the last 7 days) and the security issue is not a security issue in the way json5 is used within this project. See the discussion in #2624.

**Comment by rattkin** [comment]
please somebody do something this is ridiculous.
I put `tsconfig-paths` newer version in package.json resolutions and ewerything works, but it's a stupid workaround

**Comment by ljharb** [comment]
It's not actually a vulnerability.

You should ignore this CVE when used via an eslint plugin - you can't attack yourself.

If you want the vuln "fixed", ask the json5 maintainers to publish a v1 backport that fixes it.

**Comment by air2** [comment]
You could use eslint-plugin-i instead of this project

**Comment by rattkin** [comment]
I guess it's time to abbandon ship a go to the fork
![image](https://user-images.githubusercontent.com/910080/210064627-c1e4e56f-c859-4611-9989-22024e6a884d.png)
@ljharb deleting comments won't stop anything

**Comment by ljharb** [comment]
@rattkin abusive comments won't help anything.

**Comment by ljharb** [comment]
json5 v1.0.2 has been published, which also addresses the vulnerability - update your lockfiles, and this (inapplicable regardless) vulnerability warning will be silenced.
