### ISSUE TITLE
npm audit error by tsconfig-paths

### ISSUE THREAD

**Issue by ebao-Xin-liang** [import-js/eslint-plugin-import#2626]
please update tsconfig-paths to "^4.1.1"

**Comment by kmturley** [comment]
There is already a discussion here:
https://github.com/import-js/eslint-plugin-import/pull/2447

**Comment by ljharb** [comment]
Indeed - also, the audit error is not actually a vulnerability, so you can simply ignore it.

**Comment by air2** [comment]
You could use eslint-plugin-i instead of this project
