### ISSUE TITLE
eslint-plugin-import depends on vunerable ts-config-paths please upgrade this dependency

### ISSUE THREAD

**Issue by air2** [import-js/eslint-plugin-import#2627]

**Comment by ljharb** [comment]
This has been discussed in #2447 - tsconfig-paths can not be upgraded, because it's a breaking change.

Also, it's not actually vulnerable, and this is also a duplicate of #2625, and a duplicate of #2626.

**Comment by air2** [comment]
The discussion in #2447 is closed so I cannot place my reaction there. The point is of course the support for node4
This is the thing in software development, maintaining backwards compatibility (which you try to the mac according to you profile) is lots of work. It means branching, releasing major versions etc. So that is why most project at one point drop support for node4, (like eslint) I understand you want to still support eslint 2, that is fine. However, to respect all users (also one of your personal goals) it would be good habit, to make sure for every eslint major version you also maintain a major version of this project. In this way you would respect your users, maintain backwards compatibility, but NOT perse port all new functionality back. This last thing is never intended with backwards compatibility. Nobody is paying you to backport new functionality. This way you focus your time on the major users of your product, whithout leaving the users who use node4 and eslint2 in the dark. You could of course make most changes to the branch for eslint2 and also merge those changes to the branches for the others eslint versions if you want, but that is up to you and how you want to spent your time.

So please in the future consider a different approach, to reach your goals, because it would benefit a lot more users of your product.

**Comment by air2** [comment]
For people who want a drop in replacement could move to eslint-plugin-i instead of this project
