### ISSUE TITLE
tsconfig-paths contains json5 vulnerability

### ISSUE THREAD

**Issue by TannerS** [import-js/eslint-plugin-import#2631]
I am seeing this with our team 

```
├─┬ eslint-plugin-import@2.26.0
│ └─┬ tsconfig-paths@3.14.1
│   └── json5@1.0.2

```

for this vulnerability, https://github.com/advisories/GHSA-8cf7-32gw-wr33

now `tsconfig-paths` has a fix coming out, but there PR is for there major version 4.x (https://github.com/dividab/tsconfig-paths/pull/2320) while i noticed, the eslint-plugin-import library only allows `"tsconfig-paths": "^3.14.1"` which if i remember correctly, will not pull up the version 4.

is there anything that can be done?

**Comment by ljharb** [comment]
json5 v1.0.2 has already been updated with this fix, and either way, it's *not a valid vulnerability*.

As is the case with almost every JS CVE, the best course of action is to *do nothing* until the ecosystem fixes it for you.

This is a duplicate of #2625; a duplicate of #2628; a duplicate of #2626; a duplicate of #2627.

**Comment by TannerS** [comment]
Thanks for the reply, but can you explain what you mean by ecosystem? What do u mean by that fixing it for us?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljharb** [comment]
I mean that the vulnerability is in the `json5` package. tsconfig-paths happens to depend on that, and eslint-plugin-import happens to depend on tsconfig-paths.

The best place for the fix is the vulnerable package itself - luckily, the json5 maintainers published a fix on both the v1 and v2 lines. That means that there's nothing *anybody* has to do except update their lockfiles - no intermediate maintainers need to release updates, or need issues filed, etc.

**Comment by TannerS** [comment]
Ah ok I understand,

Eslint-plugin-import uses version 3 of tsconfig-paths, which that uses jsin5 version 1

Where they pushed a fix into tsconfig-paths version 4, which uses json5 version 2

So two ways of solving is, update Eslint-plugin-import to version 4 of tsconfig-paths which has the fixed version of Jason 5

Or the better solution

Json5 should have the fixed (ported?/added?) To version 1, and in that case, eslint-plugin-import nor tsconfig-paths has to do anything at all

Sound about correct?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljharb** [comment]
Yes, exactly - and json5 v1.0.2 is that fixed version, it's just that the audit warning hasn't been updated to reflect that yet.

**Comment by TannerS** [comment]
Ah that makes sense! Thanks for helping me learn this.

Do you happen to know what or how long it takes for the audit message to be fixed? Does nom control that?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljharb** [comment]
github/npm controls that. GIven that it's a holiday week, it probably won't happen until Monday.

**Comment by TannerS** [comment]
Good stuff! Thanks for the lesson man

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
