### ISSUE TITLE
Bump tsconfig-paths dependency to 4.1.2 to fix high severity vulnerability

### ISSUE THREAD

**Issue by sspenst** [import-js/eslint-plugin-import#2635]
json5 high severity vulnerability described here https://github.com/advisories/GHSA-9c47-m6qq-7p4h

tsconfig-paths has updated their dependency here https://github.com/dividab/tsconfig-paths/pull/232

Requesting a new eslint-plugin-import version that updates the tsconfig-paths dependency to v4.1.2

**Comment by sspenst** [comment]
Found there was already a lot of discussion here on this: https://github.com/import-js/eslint-plugin-import/pull/2447

Will wait for https://github.com/github/advisory-database/pull/1541 to get merged

**Comment by ljharb** [comment]
Indeed, json5 v1.0.2 has already been updated with this fix, and either way, it's *not a valid vulnerability*.

As is the case with almost every JS CVE, the best course of action is to *do nothing* until the ecosystem fixes it for you.

This is a duplicate of #2625; a duplicate of #2628; a duplicate of #2626; a duplicate of #2627; a duplicate of #2631; a duplicate of #2632; a duplicate of #2634.

Please stop filing issues about a vulnerability on "not the vulnerable package", it doesn't help.

**Comment by air2** [comment]
@sspenst  you could use the eslint-plugin-i package instead
