### ISSUE TITLE
Package is dependent on an outdated copy of `tsconfig-paths`

### ISSUE THREAD

**Issue by zackdotcomputer** [import-js/eslint-plugin-import#2651]
While noted in #2649 that there is a path to resolving the CVE warnings around json5 currently, there's still the issue that this package is dependent on an outdated version of tsconfig-paths (`^3.14.1`) when major release newer version exists (`^4.1.2`) which both fixes and extends some issues the package had with parsing the tsconfig.json and also bumps their dependency on `json5` up to `2.2.2`, bringing it in line with other libraries that depend on `json5`.

Unless there's a strong conflict that prevents this package from upgrading, I'd request for the health of `node_modules` folders everywhere if this package could move to the next major release.

**Comment by ljharb** [comment]
There is a strong conflict, which is discussed at length in #2447.

Note that it's not inherently "unhealthy" or bad to be on "not the latest major version line".

**Comment by zackdotcomputer** [comment]
I mean that mostly in that we have to keep both the `@1` and `@2` copies of `json5` in our dependency trees, managing each of their respective CVEs and updates. Thanks for the point to 2447.

**Comment by ljharb** [comment]
Sure, but since the vast majority of CVEs in the JS ecosystem are false positives due to the CVE system's lack of code path nuance, it's a nightmare regardless.
