### ISSUE TITLE
tsconfig-paths update from 3.14.1 to 4.1.2 to resolve json5 vulnerability

### ISSUE THREAD

**Issue by edwardlee-msft** [import-js/eslint-plugin-import#2655]
https://github.com/import-js/eslint-plugin-import/blob/6304ddc70fc187e248aa65c69bc8983c5051ecd3/package.json#L117

Hi team, 

Can you please update tsconfig-paths from 3.14.1 to 4.1.2 to resolve a vulnerability with its json5 dependency? 

We were notified of a dependabot issue with json5 and were recommended to update it to 2.2.2.
![image](https://user-images.githubusercontent.com/97130533/211649145-11de65a4-0c37-4aee-9639-79e5be6a816e.png)

The package tsconfig-paths is dependant on json5 and is used in esling-plugin-import. Their latest 4.1.2 version updates their json5 dependency.
<img src="https://user-images.githubusercontent.com/97130533/211647335-a0e60bf3-08cd-4ce6-b715-f9ad229b5c36.png"/>

Thanks,
-Edward

**Comment by edwardlee-msft** [comment]
I can see that the vulnerability fix was backported to json5 v1.0.2. Closing issue as tsconfig-paths uses 1.0.2

**Comment by ljharb** [comment]
In addition, this isn't a valid vulnerability for this plugin in the first place.

This is a duplicate of #2625; a duplicate of #2628; a duplicate of #2626; a duplicate of #2627; a duplicate of #2631; a duplicate of #2632; a duplicate of #2634; a duplicate of #2635; a duplicate of #2636; a duplicate of #2637; a duplicate of #2639; a duplicate of #2642; a duplicate of #2643.
