### ISSUE TITLE
eslint-plugin-import  >=1.11.1 depends on vulnerable versions of debug

### ISSUE THREAD

**Issue by pkuczynski** [import-js/eslint-plugin-import#2658]
Npm audit started to complain about 2 low severity vulnerabilities in `debug<3.1.0`. I checked and unfortunately `debug@4` [drops support for Node 4 and 5](https://github.com/debug-js/debug/releases/tag/4.0.0). @ljharb I know your view on such a matter, but maybe we can do something about it?

**Comment by ljharb** [comment]
Both of them are invalid vulnerabilities for this package - there's nothing to be done unless debug can backport the fixes to v2.

Duplicate of #2667.

**Comment by ljharb** [comment]
although, actually, it's debug v4, not v3, that dropped support for node 4, so maybe we can do something about it.

**Comment by air2** [comment]
@ljharb When can we expect a release containing this sort of fix?

**Comment by ljharb** [comment]
v2.27.0 is released.
