### ISSUE TITLE
Typescript - Definition for rule `import/no-empty-named-blocks` was not found

### ISSUE THREAD

**Issue by DasOhmoff** [import-js/eslint-plugin-import#2661]
Hey 👋 , thank you for this nice plugin.

I am trying to use the `import/no-empty-named-blocks` rule, but it does not seem to be working. I receive the following error in every file:
```
  1:1  error    Definition for rule 'import/no-empty-named-blocks' was not found
```
All other rules seem to be working fine.

I am using typescript, so I also installed [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser) and [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript), as stated in the documentation.

How can I make this work?
Thank you for your help :)

**Comment by ljharb** [comment]
That's because the rule isn't released yet. Like everywhere on github, you need to check the docs for the appropriate tagged release, NOT master/main.

**Comment by DasOhmoff** [comment]
Ah ok I see. Thanks
