### ISSUE TITLE
Error: Cannot find module 'array.prototype.flatmap' from 2.27.0

### ISSUE THREAD

**Issue by zloirock** [import-js/eslint-plugin-import#2663]
It's in dev dependencies but used in library code.

**Comment by cristobal** [comment]
Came here for the same reason, using `xo` and after the latest release it's complaining about missing dependency on `array.prototype.flatmap` from the `eslint-plugin-import/lib/rules/export.js` file.

Here's on of the change https://github.com/import-js/eslint-plugin-import/compare/v2.26.0...v2.27.0
![Screenshot 2023-01-12 at 01 05 35](https://user-images.githubusercontent.com/155505/211944464-bf79e4bd-5e33-4746-aac8-2be1c4846684.png)

Seems it has been included as prod dependency in several of the rules now.

**Comment by ljharb** [comment]
Thanks, will be fixed soon.

**Comment by shazron** [comment]
Thanks Jordan, this is one of the fears that I have for my own published modules, that's why I have an eslint rule enabled `node/no-unpublished-require` 😅

**Comment by ljharb** [comment]
v2.27.1 is released.
