### ISSUE TITLE
`import/no-empty-named-blocks` incorrectly auto-fixes non-import code

### ISSUE THREAD

**Issue by EvHaus** [import-js/eslint-plugin-import#2666]
The `import/no-empty-named-blocks` rule seems to have a bug where it affects regular objects.

The following code:

```js
module.exports = {
	rules: {
		'keyword-spacing': ['error', {overrides: {}}],
	}
};
```

Gets auto-fixed to:

```js
module.exports = {
	rules: {
		'keyword-spacing': ['error', {overrides: }],
	}
};
```

Note the invalid broken syntax in the `overrides` key. I think the rule should ignore any `module.export` definitions and only impact `import` statements.

CC @guilhermelimak

**Comment by ljharb** [comment]
oof, that is a huge bug, thanks for catching it. I agree it should only cover static import statements (not dynamic import either)

**Comment by ljharb** [comment]
v2.27.3 is released.
