### ISSUE TITLE
Include security patch

### ISSUE THREAD

**Issue by dipunm** [import-js/eslint-plugin-import#2670]
https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md#412---2023-01-02

This project relies on tsconfig-paths and this dependency should be updated to address a security vulnerability.

Issue: [Prototype Pollution in JSON5 via Parse Method](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)

**Comment by ljharb** [comment]
No, it shouldn’t, for a number of reasons:
1. it's a breaking change, see #2447 
1. it's unnecessary, json5 1.0.2 fixes the issue already - all everyone needs to do is update their lockfiles.
1. it's not actually a valid vulnerability for this package, so you should just ignore it.

This is a duplicate of #2625; a duplicate of #2628; a duplicate of #2626; a duplicate of #2627; a duplicate of #2631; a duplicate of #2632; a duplicate of #2634; a duplicate of #2635; a duplicate of #2636; a duplicate of #2637; a duplicate of #2639; a duplicate of #2642; a duplicate of #2643; a duplicate of #2649; a duplicate of #2655; a duplicate of #2660.
