### ISSUE TITLE
[import/no-unused-modules] Add an option to ignore typescript types

### ISSUE THREAD

**Issue by demedos** [import-js/eslint-plugin-import#2694]
Hi, when using typescript it might be useful to add an option to ignore exported but unused types (including interfaces and enumerators) since it is common to export a component along with its props and let the consumer create derivative types for example.

This is something that has been implemented in [ts-unused-exports](https://github.com/pzavolinsky/ts-unused-exports) via the `allowUnusedEnums` and `allowUnusedTypes` options.

Looking through the code I found out that typescript types are being handled already, see [src/rules/no-unused-modules.js#L89](https://github.com/import-js/eslint-plugin-import/blob/main/src/rules/no-unused-modules.js#L89).

**Comment by ljharb** [comment]
Is this something that `@typescript-eslint/plugin` might already cover?

**Comment by demedos** [comment]
Nope, there's nothing such as unused exports

**Comment by ciiqr** [comment]
Might be a bit more effort than just ignoring types entirely, but it would be cool if this could mark types referenced from used exports as used (ie. in the component/props example, the props type could be marked as used if the component itself is used). Might still want an option to enable this, though it seems like it would allow us to preserve some of the safety of this rule.

**Comment by silverwind** [comment]
I think adding a `allowUnusedTypeExports` to `no-unused-modules` which defaults to `false` should be able to solve it, at least for me.

Which things shall not trigger it? Just `export type` and `export interface`, or is there more?
