### ISSUE TITLE
`no-extraneous-dependencies` - `includeTypes` option does not work when `type` keyword is applied to the whole line

### ISSUE THREAD

**Issue by DetachHead** [import-js/eslint-plugin-import#2718]
```ts
import type { Foo } from 'foo' // no error
```
```ts
import { type Foo } from 'foo' // error
```

**Comment by DetachHead** [comment]
all that commit changed was adding a test, but i can't seem to reproduce the issue anymore, no idea why

**Comment by ljharb** [comment]
@DetachHead yes, the test was passing, which means there's nothing to fix.

**Comment by awdyson** [comment]
In a monorepo setup, you may need to specify `packageDir` for inline types.
```ts
const rootDir = __dirname;
// ...
['warn', { includeTypes: false, packageDir: [rootDir, '.'] }]
```
Oddly enough, `import type { ... } from 'whatever';` notation works fine without `packageDir`.

**Comment by awdyson** [comment]
In a monorepo setup, you may need to include `packageDir`, specifically for inline-types.

```ts
const rootDir = __dirname;
// ...
'import/no-extraneous-dependencies': ['warn', { includeTypes: false, packageDir: [rootDir, '.'] }]
```

For me, without `packageDir` set...
```
import { type Bar } from '@foo/bar'; // error 😞 
import type { Bar } from '@foo/bar'; // no error
```
