### ISSUE TITLE
Support symlinks with `packageDir` option for `import/no-extraneous-dependencies`

### ISSUE THREAD

**Issue by Aghassi** [import-js/eslint-plugin-import#2731]
https://github.com/import-js/eslint-plugin-import/blob/5680a1f8d41cd19f9c60d999a6fadf10994a0a64/utils/pkgUp.js#LL41C41-L41C54

The utils logic that supports whether or not a package.json exists does not check if one is symlinked. Can there be a check added after this check that uses https://nodejs.org/api/fs.html#fs_fs_lstat_path_callback to validate if a package.json exists?

This use case is specifically for interop with https://github.com/aspect-build/rules_js/ which will symlink package.json files to the area it runs eslint from.

CC @gregmagolan

**Comment by ljharb** [comment]
Can you elaborate on what specifically isn't working right now? The ideal would be a PR with a failing test case :-)

**Comment by Aghassi** [comment]
Yeah I'll try and whip one up. Basically my current use case is this:

```javascript
module.exports = {
  env: {
    node: true,
  },
  extends: ['@company/eslint-config'],
  rules: {
    'import/no-extraneous-dependencies': [
      'error',
      {
        devDependencies: true,
        // This ensures we check the root of the monorepo in addition to our local packages
        packageDir: [path.resolve(__dirname, '../'), __dirname],
      },
    ],
  },
}
```

This worked for us with `rules_nodejs` because the ruleset copied files over.

Now when trying to migrate to rules_js to be our test runner the error I get with the above is

```sh
  0:1  error  The package.json file could not be found  import/no-extraneous-dependencies

✖ 1 problem (1 error, 0 warnings)
```

Best I can tell is that the logic which finds the `package.json` is not find it. I checked the bazel runfiles and the files are there. If I disable this, then the test passes. The package is part of a pnpm workspace so I need to expose multiple package.json also.

**Comment by ljharb** [comment]
I'm confused - why would you need to check the root from a subpackage? Typically each subpackage checks itself, and the root checks itself as well.

**Comment by Aghassi** [comment]
The reason I need to look up the tree is because if the config is also checking developer tools, those are usually at the root config so we keep one version and flatten the dependency graph. It doesn't make sense to have things like `eslint` or `webpack` declared in every subpackage. Shared tooling is hoisted to the top. In the case of this config, it's for an internal eslint plugin so it relies on some of these root level dependencies. If you don't give the rule a place to find them, it will complain about undeclared dependencies. Also applies to test code if you don't have something like `expect` in your package.json but it's at the root of the repo

**Comment by Aghassi** [comment]
I guess the alternative is if something expects a package downstream to provide deps it should declare things as `devDependencies` and `peerDeps` in which case I wouldn't need to specify multiple package.json roots right?

**Comment by ljharb** [comment]
right - i understand the bazel model where you have a single package.json at the root. but, that also means you have a single eslint config at the root.

In this case, I see the eslint plugin is setting config defaults - and settting `packageDir` to an array of "the root" and then "the current dir" would make sense - but `__dirname` there is the directory of *the plugin*, and won't magically become the directory of individual subpackages. Are you expecting that the plugin's declared dependencies would be valid imports for everything else in the monorepo?

**Comment by Aghassi** [comment]
Yeah unfortunately we don't have a root config _yet_, that's a very large lift we are still pushing towards.

Yeah the model we have is that we use `syncpack` to align our dependencies so all our eslint dependencies are the same version across the repo no matter where they are declared

**Comment by ljharb** [comment]
I'm not familiar with that tool - what i meant was, if you put the plugin's directory in packageDir, and it depends on X, but nothing else in the monorepo needs it, then the eslint rule will allow anything to import X *as if* they declared it, which kind of shreds the premise of bazel :-p

**Comment by Aghassi** [comment]
True, I see your point. In this case though the eslintrc is only used by this plugin dir and not by the broader repo. That isolates the trickledown you are describing. 

I think the route I'm gonna take is to have the plugin specify what it needs via `peerDependencies` and `devDependencies` and then remove this `packageDir` field so that the rule only looks in the plugin's dir and nowhere else. This skips the symlink check it seems too? Not sure why.

**Comment by ljharb** [comment]
That seems reasonable. node resolves symlinks by default I think, but perhaps this plugin doesn't.

**Comment by Aghassi** [comment]
Cool. thanks for being so quick to respond! I'll close this issue for now
