### ISSUE TITLE
import/no-unused-modules disables VS Code error & warning highlights

### ISSUE THREAD

**Issue by a-lukianenko** [import-js/eslint-plugin-import#2734]
Hi! 👋 

I'm trying to use `import/no-unused-modules` as part of Next.js project. Here is what happens:

- `Next.js 12.3.4`
- `eslint-plugin-import 2.26.0`

ESLint config snippet
```js
 'import/no-unused-modules': [
            'error',
            {
                unusedExports: true,
                ignoreExports: [
                    '**/__mocks__/*',
                    '**/__stories__/*',
                    '**/__tests__/*',
                    '**/*.d.ts',
                    'config/**/*',
                    'lib/**/*',
                    'routes/**/*',
                ],
          },
  ],
```

**Before enabling `import/no-unused-modules`**:
| File with highlights from `VSCode` 👍  | ESLint output 👌  |
| ---- | ----- |
| <img width="872" alt="Screenshot 2023-03-14 at 11 43 20" src="https://user-images.githubusercontent.com/46814181/224944709-9b8f4432-d711-4c24-b85a-5f2d6775fc79.png"> |  <img width="1045" alt="Screenshot 2023-03-14 at 11 34 29" src="https://user-images.githubusercontent.com/46814181/224944844-dbf17f3d-6d2f-47f4-86c0-c1a18c21565a.png"> |

**After enabling `import/no-unused-modules`**:
| File has no highlights from `VSCode` 👎  | ESLint output still 👌  |
| ---- | ----- |
| <img width="871" alt="image" src="https://user-images.githubusercontent.com/46814181/224946155-9de5eb7d-cb28-4836-aba6-7493d0a0334b.png"> |  <img width="1042" alt="image" src="https://user-images.githubusercontent.com/46814181/224946569-4d366626-64b3-4665-a257-6fdc09119107.png"> |

**Comment by ljharb** [comment]
That's very strange. I'd suspect it's an issue with vscode-eslint, since the CLI is the source of truth, but if there's anything I can tweak in the plugin to fix this I'll be happy to.

**Comment by a-lukianenko** [comment]
Hi Jordan! 👋 

Thanks for a quick reply. I've just opened an Issue with [VSCode ESLint](https://github.com/microsoft/vscode-eslint/issues/1622#issue-1624844234). Let's see if the maintainers can help 🙏 . 

I will share updates if any here too.

**Comment by a-lukianenko** [comment]
As described in this [comment](https://github.com/microsoft/vscode-eslint/issues/1622#issuecomment-1469846383): setting `eslint.workingDirectories` in VSCode Workspace settings has helped! 🎉 

Closing this issue! ✅
