### ISSUE TITLE
Vulnerability found on latest version of eslint-plugin-import (2.27.5)

### ISSUE THREAD

**Issue by sn06work** [import-js/eslint-plugin-import#2742]
There is vulnerability found on latest version of eslint-plugin-import (2.27.5) due to minimist. 
<img width="559" alt="Screenshot 2023-03-20 at 11 46 13 AM" src="https://user-images.githubusercontent.com/128142423/226261615-6117c820-3e75-406a-b836-c28932862ae3.png">

**Comment by ljharb** [comment]
This isn't an actual vulnerability, and tsconfig-paths depends on json5 with `^`, and json5 has a v1 and a v2 both that don't have the vulnerability anyways.
