### ISSUE TITLE
import/order Doesn't work general minimatch rules for pattern in pathGroups

### ISSUE THREAD

**Issue by IlliaHohniak-Hexa** [import-js/eslint-plugin-import#2759]
I have a few similar imports like
```
components/Button
./components
./components/Alert
```
And I want to group them by pattern in one pathGroup. 
But nothing works
```
{./, ../}components(/**, /*)
{./, ../}components/*
{./, ../}components*(/**, /*)
```

Could you help with that?

**Comment by ljharb** [comment]
The first one is a package, the second two are relative imports.

**Comment by IlliaHohniak-Hexa** [comment]
@ljharb Yeah, thank you. Just want to know how to write a pattern to combine them. (Or at least, second two)

**Comment by ljharb** [comment]
If you're using some kind of hack (like WebStorm settings) to introduce an alias, then you have to configure this plugin to understand how to resolve that alias.

The best practice here is to use a babel transform, and https://www.npmjs.com/package/eslint-import-resolver-babel-module to handle aliases.
