### ISSUE TITLE
[Question] How to get access to a nightly build ?

### ISSUE THREAD

**Issue by alann-sapone** [import-js/eslint-plugin-import#2762]
Hi there !

I've been trying to use this great library and fell upon a few bugs. I saw in the changelog that most of them were already fixed, but there is no release yet. I'm wondering : Is there a planned released ? Or else, what is the process to build and deploy this lib so I can already use theses corrections ?

Thank you a lot for this amazing lib ! :)

**Comment by ljharb** [comment]
There’s no way to use unreleased changes. A release is planned but there’s no schedule for releases.
