### ISSUE TITLE
Resolve error: typescript with invalid interface loaded as resolver

### ISSUE THREAD

**Issue by dugip** [import-js/eslint-plugin-import#2768]
I have a monorepo setup which includes a eslint-config package, which uses eslint-plugin-import. This periodically gives me grief with the first `import` word being highlighted as red on my editor, with the message:

> Resolve error: typescript with invalid interface loaded as resolver

I've had this error before and I always dug into changing the plugin's settings, making it disappear, only for it to appear again after I run yarn or deleting node_modules folders across the repos.

This is what my configuration looks like:

```
module.exports = {
  extends: ['turbo', 'plugin:import/typescript', 'react-app', 'prettier'],
  plugins: ['prettier'],
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: true,
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
  rules: {
    'import/order': [
      'error',
      {
        'newlines-between': 'never',
        pathGroups: [
          {
            pattern: '@/**',
            group: 'internal',
            position: 'after',
          },
        ],
      },
    ],
};
```

At this point I'm starting to believe this is a bug in the plugin, but hopefully, you can advise on how to proceed.

**Comment by ljharb** [comment]
You should be extending `plugin:import/config/typescript` instead of specifying the typescript resolver yourself. If you do that, does it work?

**Comment by dugip** [comment]
@ljharb I have had the before, when I configured the settings based on the docs. I had the same problem.

**Comment by ljharb** [comment]
Does it happen on the command line, or only in your editor? Editors often have to be quit and reopened whenever anything in node_modules changes.

**Comment by dugip** [comment]
It happens in the command line, when I run eslint

**Comment by clementprevot** [comment]
Hi!

I also stumble into this issue and haven't been able to solve it.
I have a reproduction repo : https://github.com/snowball-tech/glacier/tree/repro-2768 (make sure to use the `repro-2768` branch).
This repo is using Yarn 3 PnP mode and is a monorepo.

If you in you terminal in `packages/utils` and run `yarn lint`, you will see a lot of

> Resolve error: typescript with invalid interface loaded as resolver

Here is a screenshot of the output I have on my side

![image](https://github.com/import-js/eslint-plugin-import/assets/6450505/9990d0b9-a07e-451b-b007-85e79d0b6342)

As soon as I remove the `typescript` setting of the resolver, this error disappears but then I cannot enjoy the proper resolution of `paths` set in a tsconfig.json file.

Could you help me on that 🙏🏻

**Comment by ljharb** [comment]
@clementprevot problems with PnP mode are expected since it breaks the node resolution algorithm, and the node or typescript resolvers may not support it. What happens if you disable PnP?

**Comment by clementprevot** [comment]
To be honest I haven't tried disable PnP because it's so nice and works pretty well.
This is the only thing I didn't managed to get to work so I can definitely live without

**Comment by PFanz** [comment]
I found that the issue was caused by the missing installation of eslint-import-resolver-typescript.

**Comment by nnmax** [comment]
> I found that the issue was caused by the missing installation of eslint-import-resolver-typescript.

Installing eslint-import-resolver-typescript solved my problem.

**Comment by SpiritQAQ** [comment]
> I found that the issue was caused by the missing installation of eslint-import-resolver-typescript.

Thanks!!!!
