### ISSUE TITLE
import/no-empty-named-blocks is not fixed with `--fix`

### ISSUE THREAD

**Issue by vdegenne** [import-js/eslint-plugin-import#2774]
The documentation says `no-empty-named-blocks` rule, i quote "is automatically fixable by the --fix CLI option".  
But using 

```bash
npx eslint --fix test.js
```
on
```javascript
// test.js
import {} from 'module';
```
proves it is wrong.

It just complains about
```
/home/fedora/gits/temp/test-eslint/main.js
  1:1  warning  Unexpected empty named import block  import/no-empty-named-blocks

✖ 1 problem (0 errors, 1 warning)
```

**Comment by ljharb** [comment]
The docs don’t capture the nuance, which is that some things are autofixed and the others are handled with suggestions.

**Comment by vdegenne** [comment]
@ljharb Ah ok. Do you happen to know if there is a way to tell eslint to autofix that, or is this plugin not implementing a directive for it?

**Comment by ljharb** [comment]
It's intentionally not doing so, because it's impossible to know if it's safe or not - in your example, eslint can't know if `module` has side effects or not. The suggestions, though, let you manually pick "delete it" or "leave it as a side-effecting import".
