### ISSUE TITLE
[import/order] Regression in 2.27.5

### ISSUE THREAD

**Issue by DaveTryon** [import-js/eslint-plugin-import#2775]
The `order` rule in release 2.27.5 behaves differently than it did in 2.26.0. Specifically, if a file name has a sibling directory that starts with the same name, the files used to be listed _before_ the directory. The `order` rule now wants to sort the files _after_ the directory. As a reference, `Prettier`'s behavior is consistent with 2.26.0. 

To repro, add the following test case in [tests/src/rules/order.js](https://github.com/import-js/eslint-plugin-import/blob/main/tests/src/rules/order.js):
```
    // Option alphabetize: {order: 'asc'} and check for files that overlap a folder name
    test({
      code: `
        import a from "foo/bar-blah";
        import b from "foo/bar-other";
        import c from "foo/bar/blah";
      `,
      options: [{ alphabetize: { order: 'asc' } }],
    }),
```
2.26.0 sets the order to a, b, c. 2.27.5 wants the order to be c, a, b. The regression was introduced with #2396.

**Comment by VincentMolinie** [comment]
I got the same issue 👍 
```javascript
// 2.27.5
import { isArray } from '@ember/array';
import { inject as service } from '@ember/service';
import { dasherize } from '@ember/string';
import JSONSerializer from '@ember-data/serializer/json';
import JSONAPISerializer from '@ember-data/serializer/json-api';

// 2.26.0
import JSONSerializer from '@ember-data/serializer/json';
import JSONAPISerializer from '@ember-data/serializer/json-api';
import { isArray } from '@ember/array';
import { inject as service } from '@ember/service';
import { dasherize } from '@ember/string';
```

**Comment by Mrtenz** [comment]
Running into this as well with relative imports:

```ts
// 2.27.5
import date from './date';
import { rootRealmGlobal } from '../globalObject';

// 2.26.0
import { rootRealmGlobal } from '../globalObject';
import date from './date';
```
