### ISSUE TITLE
How to make `eslint-plugin-import` correctly recognize path aliases and analyze the validity of alias paths?

### ISSUE THREAD

**Issue by daiwanxing** [import-js/eslint-plugin-import#2780]
![image](https://github.com/import-js/eslint-plugin-import/assets/37327614/624a42af-c1c8-44c1-b90c-eed873b4c6f7)

As shown in the image above, it seems that ESLint cannot resolve paths with aliases（It's not ts project）. I have found a solution.

```js
"import/no-unresolved": ["off", { ignore: ["^@/", "node_modules"] }],
```
After configuring this rule, the errors are now gone. However, this rule only ignores the parsing of path aliases starting with `@`. I want to configure it to analyze whether this path alias is valid.

Here is the code to configure the `import/*` rule:

```js
    settings: {
        "import/ignore": ["node_modules"],
        "import/extensions": [".js", ".jsx", ".es6"],
        "import/resolver": {
            node: {
                extensions: [".js", ".jsx"],
            },
        },
    },
```

**Comment by ljharb** [comment]
Where do the aliases come from? If it's webpack, you need to also use the webpack resolver.

**Comment by daiwanxing** [comment]
> Where do the aliases come from? If it's webpack, you need to also use the webpack resolver.

I am using Vite to configure aliases. I would like to know how to make ESLint recognize these file paths as valid and prevent it from reporting errors for them.

**Comment by daiwanxing** [comment]
Thanks for your suggestion. I know how to solve it now.

**Comment by ljharb** [comment]
If you find a vite eslint import resolver I'd love to know about it.

**Comment by vaynevayne** [comment]
means that can't use it in vite ?

**Comment by musjj** [comment]
@ljharb 
There's this: https://github.com/pzmosquito/eslint-import-resolver-vite

**Comment by ljharb** [comment]
Wonderful, https://www.npmjs.com/package/eslint-import-resolver-vite is the solution then.
