### ISSUE TITLE
Definition for rule 'import/newline-after-import' was not found.eslint(import/newline-after-import)

### ISSUE THREAD

**Issue by wtjandra96** [import-js/eslint-plugin-import#2781]
Hi, I encountered a problem when trying to use this rule. As far as I'm aware I think it should be included in the base eslint package.

**Comment by ljharb** [comment]
You’ll have to elaborate, because it’s definitely been available for a long time. Do you have “import” in your plugins array?

**Comment by wtjandra96** [comment]
Duh you're right, thanks so much!
