### ISSUE TITLE
Update tsconfig-paths dependency version

### ISSUE THREAD

**Issue by vladimir-palocko-myob** [import-js/eslint-plugin-import#2782]
Would it be possible to update the `tsconfig-paths` dependency version to link the latest? The reason is that the current version links a very old version of `json5` that has a known vulnerability. They have fixed the dependency, however, `eslint-plugin-import` is still linking `"tsconfig-paths": "^3.14.2"`  while the latest is 4.2.0.

**Comment by ljharb** [comment]
There’s no need for that, tsconfig-paths v3 depends on a fixed version of json5, and the vulnerability doesn’t apply to our usage anyways. Just update your transitive deps.

As for v4, see #2447.
