### ISSUE TITLE
High Vulnerability found

### ISSUE THREAD

**Issue by navyaharish** [import-js/eslint-plugin-import#2783]
The version of tsconfig-paths has a vulnerability because of json5.

>  High          │ Prototype Pollution in JSON5 via Parse Method

**Comment by navyaharish** [comment]
can we upgrade the version of tsconfig-paths?

**Comment by ljharb** [comment]
It’s not a vulnerability in the first place; json5 v1 has a fix anyways, so you just need to update your transitive deps; and no, we can’t upgrade to v4 of tsconfig-paths (#2447)

Duplicate of #2782.
