### ISSUE TITLE
Can this plugin order symbols within the same import statement?

### ISSUE THREAD

**Issue by aryzing** [import-js/eslint-plugin-import#2785]
When importing several items from the same module, can this plugin order the items alphabetically, similar to [`importOrderSpecifiers`](https://github.com/trivago/prettier-plugin-sort-imports#importordersortspecifiers)?

```js
import {a, c, b} from "foo"; // input

import {a, b, c} from "foo"; // --fix
```

Seems the options only allow for the statements themselves to be ordered, but no the symbols?

**Comment by ljharb** [comment]
The bindings indeed can’t be ordered; that’s handled by eslint’s core import sorting rule.

**Comment by aryzing** [comment]
Found [the rule](https://eslint.org/docs/latest/rules/sort-imports), thanks!

**Comment by aryzing** [comment]
Leaving the results of my experience trying to achieve a deterministic ordering with semantic grouping of import statements should they be of use to anyone looking at this plugin.

This plugin has the `import/order` rule with a `--fix` to order import statements by their source and allows for custom grouping, although it does not order import statement specifiers.

The specifiers can be ordered with [`sort-imports`](https://eslint.org/docs/latest/rules/sort-imports), although it only recognizes [four fixed import groups](https://eslint.org/docs/latest/rules/sort-imports#membersyntaxsortorder) incompatible with `import/order` and is unable to fix the order of import statements. While `sort-imports` can be used to achieve a determinstic result, the four groups are based on structure and not semantics.

The only was I was able to achieve a deterministic ordering with semantic grouping of import statements and their specifiers is with Prettier and [`prettier-plugin-sort-imports`](https://github.com/trivago/prettier-plugin-sort-imports)

- Sorts import statements by source
- Sorts specifiers
- Has customizable group definitios

My `.prettierrc.yaml` looks like,

```yaml
plugins: ["@trivago/prettier-plugin-sort-imports"]
importOrder: [/* my custom groups */]
importOrderSeparation: true
importOrderSortSpecifiers: true
```
