### ISSUE TITLE
[FR] No newline between imports

### ISSUE THREAD

**Issue by wenfangdu** [import-js/eslint-plugin-import#2787]
Is there a rule to make the below conversion? If not, please consider adding it.

```js
import 'a'
import 'b'

import 'c'

import 'd'
```

⬇

```js
import 'a'
import 'b'
import 'c'
import 'd'
```

**Comment by ljharb** [comment]
Can you not do this with the `order` rule and `newlines-between` set to `never`?

**Comment by wenfangdu** [comment]
@ljharb Not really, with `/* eslint import/order: ["error", {"newlines-between": "never"}] */`, the second part threw an error, the first part was not affected:
![image](https://github.com/import-js/eslint-plugin-import/assets/28700378/3b119d7a-1a53-49e8-adb3-2be850f74b4e)

**Comment by wenfangdu** [comment]
@ljharb With:
```json
{
  "import/order": [
    "error",
    {
      "newlines-between": "never",
      "warnOnUnassignedImports": true
    }
  ]
}
```
The following code throws:
![image](https://github.com/import-js/eslint-plugin-import/assets/28700378/e7a44ca0-5d3f-4ec9-8f44-a9dd196bd56a)
![image](https://github.com/import-js/eslint-plugin-import/assets/28700378/ae5daacb-0627-4575-9506-d32141a9754c)
But I want to put styles first, is there a way to turn this error off?

**Comment by hyperupcall** [comment]
@wenfangdu If you want your styles first, then you need to use [`pathGroups`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#pathgroups-array-of-objects) and create a pattern that matches `*.{css,scss}` files. You also need to set `distinctGroup` to `false`.

**Comment by wenfangdu** [comment]
@hyperupcall Thanks, `"distinctGroup": false` is actually not needed in this case, since whether the group is distinct or not, there're still no newlines in between.

Also, the putting styles first discussion is continued here: https://github.com/import-js/eslint-plugin-import/issues/2788.
