### ISSUE TITLE
[Question]: import/export 

### ISSUE THREAD

**Issue by liuseen-l** [import-js/eslint-plugin-import#2798]
question:
How to configure in .eslintrc.cjs  to achieve the following effects 
```ts
//  the x is interface, expect get error
import { x } from 'module'
```
after eslint --fix
```ts
import type { x } from 'module'
```

**Comment by ljharb** [comment]
You'd use the https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/consistent-type-specifier-style.md rule for this.
