### ISSUE TITLE
Please fix semver security issue.

### ISSUE THREAD

**Issue by makeupyourmind** [import-js/eslint-plugin-import#2803]
The npm audit report says `eslint-plugin-import` package has a vulnerability:

![image](https://github.com/import-js/eslint-plugin-import/assets/46902917/a296fb7f-ec43-419a-8ad7-ff7aafc0de81)

Here is a security issue - https://security.snyk.io/package/npm/semver/6.3.0.

Please bump the `semver` version.

The version of the `eslint-plugin-import` package that I am using is `2.27.5`. 
Thanks in advance.

**Comment by ljharb** [comment]
Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).

We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

**Comment by makeupyourmind** [comment]
> Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).
> 
> We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

Sounds sad, but thanks for the answer anyway.

**Comment by fernandopioli** [comment]
Same case here. It's breaking the CI even it's being a dev dependencie. o/

**Comment by christhofer** [comment]
How about reopening this issue until the backport fixed on Semver completes?
This can avoid further duplicate issues.

Babel & Microsoft team tries to fix Semver v5/6, I see that @ljharb has commented there as well, but seems the Semver team still has no plan to backport the fix.
[npm/node-semver/#564](https://github.com/npm/node-semver/pull/564#issue-1757995222)
[npm/node-semver/#576](https://github.com/npm/node-semver/issues/576#issue-1775200975)

**Comment by ljharb** [comment]
People file duplicate issues for this kind of thing whether there's one open or not, in my experience, and regardless, no issue should ever *be* filed for this sort of thing. A major upgrade isn't reasonable to request, and if the package backports the fix, nothing needs to be done here.
