### ISSUE TITLE
Update semver version

### ISSUE THREAD

**Issue by Badisi** [import-js/eslint-plugin-import#2805]
Npm's report recommend to update `semver` dependency version.

> Versions of the package semver before 7.5.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.

Source: [github.com/advisories/GHSA-c2qf-rxjj-qqgw](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)

**Comment by Badisi** [comment]
Sorry for the duplicates.

If by engine you mean `node >= 4`, don't you think it's time to drop it too ?
Or at least maintain a legacy and latest version of your library ?

**Comment by ljharb** [comment]
Nope, it'll likely never be time to do so.
