### ISSUE TITLE
Can I disable no-unused-modules for Next.js pages?

### ISSUE THREAD

**Issue by sinuheshinbr** [import-js/eslint-plugin-import#2811]
I'm trying to configure this plugin in a Next.js project, but I'm also erroring: export default Page inside pages directory where it is supposed to be this way. Is it possible to configure it specifically to work in a Next.js project?

**Comment by ljharb** [comment]
I'm sure it is, but I don't know what specific config would be appropriate. You can use `overrides` in your root eslint config to target specific files/globs with different config than everything else - I'd look there.
