### ISSUE TITLE
webpack resourceQuery not resolved

### ISSUE THREAD

**Issue by terfy-wei** [import-js/eslint-plugin-import#2819]
import code:
`import bugUrl from './images/bug.svg?url';`

error:
`Unable to resolve path to module './images/bug.svg?url'`

**Comment by ljharb** [comment]
This may be related to #1739, but if it's for webpack, then I'd expect the webpack resolver to handle it. What's your eslint and webpack configs?

**Comment by terfy-wei** [comment]
> [这可能与#1739](https://github.com/import-js/eslint-plugin-import/issues/1739)有关，但如果它是针对 webpack 的，那么我希望 webpack 解析器能够处理它。你的 eslint 和 webpack 配置是什么？

ok，it is help me，ths

**Comment by ljharb** [comment]
ok, i'll close it, but happy to reopen it if needed.
