### ISSUE TITLE
[import/order] Sort by nearest parent

### ISSUE THREAD

**Issue by JakeTompkins** [import-js/eslint-plugin-import#2827]
I've noticed in my project that alphabetize "asc" arranges parent directory imports in what I would consider a descending order due to the `.` character being evaluated as less than letter characters, resulting in an order like this:

import A from "../../../a"
import B from "../../b"
import C from "../c"

whereas this makes more sense:

import C from ".../c"
import B from "../../b"
import A from "../../../a"

I recognize that changing something like this is potentially problematic for some people, but if there's interest I would be more than happy to put up a PR to allow us to opt into sorting by nearest parent.

Here's a ts-playground with an approximation of the current and proposed behavior: [link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgQygCwIIwLwwEQDpcD0+RhC2AUKJLIigEKY7HEBGF5AZgK5jBQCW4GKAC2iAE4BTAMpRx-MAHMIACgQAuGNHlKANDBbrtCxQEoYAb3IwbMfhxhqYAHgPmrtzzClQu4sDAAtACM1rYAvjCSADYQknYOTgB8bpZhXt6Svv4woZ7h6ZnZAQAM5AWcPHyCARAg4lCS4gBiVWqaxnoGRnIm+mCSCFLQAApDkmBQzfzi0IwcCLGS7oVUcwgAIjNjDRCMCLgQcNH8UCrYBNimq+BzLFviO1B7WCyHx6fnl9eeN9QwmxmABlJAA3GL7XAiJDAZAqAgAHVwSIRBAIZgA-LhohNFCgYBiMTAyp41rB7sCwRDXlCYXDEcjkWjMdjcfjCcS-nN+BBpAgRJIHiDwdF9kKqaKMFKDOKReRCjjYMNGGVCvZHANxqNxpNprNYAAyA0wACEPL5AtlMRWGRs6rUVtFrgp4mF1rStq8Pj8ARChXyUSWHs9tm9OTytoKAZicWDGQ49UcirsKoA3CnXABZJDIKEKB3bIbPVlKFD6F1PCAlvHIUzp-gAagbNpDNmVWFEEhkvSUqkBjyLEAA2vwALrlh6Vkej67+2324Yt1ueFhSBAAaznGSjkcKFU8YYCw3K8rWIBx2JAinOAGE-FJJjAAPLiAAmTU02H0Q9oaH0v7oUdDnqM41HLcwMBSOoGiaVpeDAtxTGuM8L2iK9zgAOUkAB3Z83w-HBv1-VB-xzQDgIaFQwJYCCoJA2C2gQct9DkLhliQoA)

**Comment by ljharb** [comment]
Why does that make more sense?

Imports are usually ordered so that third-party packages are at the top - the farthest ones away - and relative files in the same directory, the closest ones, are at the bottom. Thus, the top order makes the most sense to me.

**Comment by tylerlaprade** [comment]
FWIW, `ruff` gives the option to go in either direction since it's largely an aesthetic difference.

**Comment by ljharb** [comment]
I'm not opposed to an option, but I definitely think the current behavior makes the most sense and fail to see a logical argument for the other.

**Comment by tylerlaprade** [comment]
The honest answer is because our human brains prefer to see pyramids than upside-down pyramids 🤷‍♂️

**Comment by ljharb** [comment]
If that were true people would be asking for an ordering option where everything's based on line length :-p
