### ISSUE TITLE
[import/consistent-type-specifier-style] (prefer-inline) Leaves an extra (double) space

### ISSUE THREAD

**Issue by benkrejci** [import-js/eslint-plugin-import#2833]
## Config
```json
"import/consistent-type-specifier-style": ["error", "prefer-inline"]
```

### Input

```ts
import type { TypeOne } from "types";
```

### Output

```ts
import  { type TypeOne } from "types";
//     ^ extra space here
```

## Possible cause

I don't know anything about custom eslint rules, but I managed to fix this locally by modifying [src/rules/consistent-type-specifier-style.js#L89-L94](https://github.com/import-js/eslint-plugin-import/blob/main/src/rules/consistent-type-specifier-style.js#L89-L94)
**From:**
```js
              const kindToken = sourceCode.getFirstToken(node, { skip: 1 });

              return [].concat(
                kindToken ? fixer.remove(kindToken) : [],
                node.specifiers.map((specifier) => fixer.insertTextBefore(specifier, `${node.importKind} `)),
              );
```
**To:**
```js
              const importToken = sourceCode.getFirstToken(node);
              const kindToken = sourceCode.getTokenAfter(importToken);

              return [].concat(
                kindToken
                  ? fixer.removeRange([importToken.range[1], kindToken.range[1]])
                  : [],
                node.specifiers.map((specifier) => fixer.insertTextBefore(specifier, `${node.importKind} `)),
              );
```

I would have expected eslint to take care of the space (so this could be a bug in eslint), but I'm not sure if it should. Does this make sense to anyone?

**Comment by ljharb** [comment]
I would assume another rule takes care of it - perhaps one in core instead of in this plugin. Certainly we could remove the space, but we also have to account for comments and whatnot - it could also be `import/**/type/**/{ Type One }`, for example.

**Comment by benkrejci** [comment]
Ok, I was able to get my configuration to work by adding [no-multi-spaces](https://eslint.org/docs/latest/rules/no-multi-spaces) (from core). I find it unexpected though that this rule, when used alone, introduces irregular spacing.

What I expect is for it to produce an output which is at least no worse than the input style-wise (I don't think anyone wants 2 spaces next to each other).

Maybe something like this, which takes comments into account:
```js
const kindToken = sourceCode.getFirstToken(node, {
  filter: (token) =>
    token.type === 'Identifier' && token.value !== 'import'
});
const prevToken = sourceCode.getTokenBefore(kindToken, {
  includeComments: true
});
return [].concat(
  kindToken
    ? sourceCode.isSpaceBetween(prevToken, kindToken)
      ? fixer.removeRange([prevToken.range[1], kindToken.range[1]])
      : fixer.remove(kindToken)
    : [],
  node.specifiers.map((specifier) => fixer.insertTextBefore(specifier, `${node.importKind} `)),
);
```

Tested and works with the following cases:

## No comments
```ts
import type { TypeOne } from "types";
```
Fixed to:
```ts
import { type TypeOne} from "types";
```

## Comment with spaces
```ts
import /* a comment */ type { TypeOne } from "types";
```
Fixed to:
```ts
import /* a comment */ { TypeOne } from "types";
```

## Comment without spaces
```ts
import/* a comment */type { TypeOne } from "types";
```
Fixed to:
```ts
import/* a comment */ { TypeOne } from "types";
```
👆 This one is not ideal, but to be fair, is a rather contrived example, and I think does ok given the input.
