### ISSUE TITLE
dep item resolve@^1.22.3 is a bug version and should not be used

### ISSUE THREAD

**Issue by EAGzzyCSL** [import-js/eslint-plugin-import#2846]
> see issue https://github.com/browserify/resolve/issues/297

eslint-plugin-import declared `resolve@^1.22.3` in dependencies（ commit: https://github.com/import-js/eslint-plugin-import/commit/261ee3aa7666edb0131e08db3d3d3428b013df42 ） will cause project which depend on eslint-plugin-import installed    `resolve@1.22.3` rather than 1.22.2 and occur error when build with Webpack or other bundle tools. 

<img width="1206" alt="image" src="https://github.com/import-js/eslint-plugin-import/assets/6220109/2763b14e-08bb-4af8-88ee-e00209fdae2e">

**Comment by ljharb** [comment]
It's not buggy, to be clear, it's just that it breaks bundlers.

v1.22.4 will be published soon, which will address the problem without any change needed here.

**Comment by ljharb** [comment]
v1.22.4 is published.
