### ISSUE TITLE
[import/no-unresolved] issue

### ISSUE THREAD

**Issue by OlivierZal** [import-js/eslint-plugin-import#2849]
I've recently migrated my `.eslintrc` to the new `eslint.config.js` eslint flat config:

```javascript
import js from '@eslint/js'
import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import prettierConfig from 'eslint-config-prettier'
import importPlugin from 'eslint-plugin-import'
import globals from 'globals'

export default [
  {
    ignores: ['.homeybuild/'],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      globals: {
        ...globals.browser,
        ...globals.es2024,
        ...globals.node,
      },
      sourceType: 'module',
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    plugins: {
      import: importPlugin,
    },
    rules: importPlugin.configs.recommended.rules,
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: './tsconfig.json',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs['eslint-recommended'].overrides[0].rules,
      ...tsPlugin.configs['strict-type-checked'].rules,
      ...tsPlugin.configs['stylistic-type-checked'].rules,
      ...importPlugin.configs.typescript.rules,
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          varsIgnorePattern: 'onHomeyReady',
        },
      ],
    },
    settings: {
      ...importPlugin.configs.typescript.settings,
      'import/resolver': {
        ...importPlugin.configs.typescript.settings['import/resolver'],
        typescript: {
          alwaysTryTypes: true,
        },
      },
    },
  },
  prettierConfig,
]
```

and I'm wondering why I'm getting the following error **only for `@typescript-eslint/*` imports**:

```
  2:22  error  Unable to resolve path to module '@typescript-eslint/parser'         import/no-unresolved
  3:22  error  Unable to resolve path to module '@typescript-eslint/eslint-plugin'  import/no-unresolved
```

although they are installed and work well since `@typescript-eslint` errors are correctly raised when the linter is run.

Thanks for your help!

**Comment by ljharb** [comment]
Presumably you didn't get these issues prior to the flat config migration, and presumably both of those packages are listed in package.json and also present directly inside `node_modules`, and these errors are being reported on the eslint config itself?

I'm not familiar with `@eslint/js`; what's in its recommended config?

It seems like there's no `import/resolver` settings at all for non-TS files, which the eslint config is - perhaps that's the issue?

**Comment by OlivierZal** [comment]
You’re right @ljharb:
- it worked before migration
- they are listed in the `package.json`
- errors are raised when running `npx eslint .`

Regarding your other comments:
- `@eslint/js` provides the new official `eslint:recommended` from `eslint` (https://www.npmjs.com/package/@eslint/js)
- indeed I rely only on `importPlugin.configs.recommended` : that’s a lead for investigation, I’ll check on my side and update you.

**Comment by OlivierZal** [comment]
Move parser and settings at the "all files" level solved the issue. Thanks!
