### ISSUE TITLE
Configuration for rule "import/no-duplicates" is invalid: Value {"prefer-inline":true} should NOT have additional properties

### ISSUE THREAD

**Issue by filipjakov** [import-js/eslint-plugin-import#2863]
problem in both: "eslint-plugin-import": "2.27.5" & "eslint-plugin-import": "2.28.1" versions

Trying to add support for typescript's new flag [`verbatimModuleSyntax`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#--verbatimmodulesyntax) 

Since the codebase is big, the idea is to add warning rules for imports and as soon as the developer touches a file, it will --fix its content based on the following rules:

```js
'@typescript-eslint/consistent-type-exports': 'warn',
'@typescript-eslint/consistent-type-imports': 'warn',
'@typescript-eslint/no-import-type-side-effects': 'warn',
'import/no-duplicates': ['error', { 'prefer-inline': true }],
```

(The above rules are recommended in https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

The first 3 work as expected, but `import/no-duplicates` yields:

> 	Configuration for rule "import/no-duplicates" is invalid:
	Value {"prefer-inline":true} should NOT have additional properties.

Since `prefer-inline` is recommended as per [this](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md#inline-type-imports), what am I doing wrong?

**Comment by ljharb** [comment]
Are you absolutely certain you have v2.28 of the import plugin? what does `npm explain eslint-plugin-import`

**Comment by filipjakov** [comment]
I was relying on the `import` provided by `eslint-config-next@"13.3.0"` which was `eslint-plugin-import@2.26.0` 😅 

It seems like they have it as ` "eslint-plugin-import": "^2.26.0",` in their package.json even on LTS.

Thanks, sorry for the trouble 🙏

**Comment by ljharb** [comment]
`^2.26.0` is a semver range that includes the latest v2 version, so that should be just fine, and you just need to update your lockfile.
