### ISSUE TITLE
Default option of 'import/consistent-type-specifier-style' is 'prefer-inline' but it doesn't work as Doc's description 

### ISSUE THREAD

**Issue by shangodseu** [import-js/eslint-plugin-import#2864]
Description:
Problem in: "import/consistent-type-specifier-style" default option. My version is: 2.28.1
As Doc's description, By default the rule will use the ` prefer-inline` option.

Example:
code `import React, { type ComponentProps } from 'react';`

Works in: `'import/consistent-type-specifier-style': ['error', 'prefer-inline']`
But fails in: `'import/consistent-type-specifier-style': 'error'`

As [Doc's](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/consistent-type-specifier-style.md#options) description, By default the rule will use the ` prefer-inline` option, what am I doing wrong?

**Comment by ljharb** [comment]
What version of TypeScript and the TS resolver do you have installed?

**Comment by shangodseu** [comment]
Hi @ljharb , my typescript version is  "typescript": "5.1.6" and resolver-typescript version is "eslint-import-resolver-typescript": "3.5.5",

**Comment by ljharb** [comment]
Can you try updating to v3.6.0 of the resolver, and v5.2.2 of TS?
