### ISSUE TITLE
no-extraneous-dependencies triggers when importing svelte

### ISSUE THREAD

**Issue by shadow-identity** [import-js/eslint-plugin-import#2879]
Hi, 

I have this svelte component: 
```html
<script lang="ts">
    import { beforeUpdate } from 'svelte'
    ...
</script>
```

Svelte is described in devDependencies since it is needed just for the build and doesn't exist in runtime.
I have `eslint-plugin-import 2.27.5 `and `svelte-eslint-parser: 0.32.2`

When running eslint, I have this error: 
`   2:5   error  'svelte' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies`

I think this is a false reaction, since Svelte shouldn't be described in dependencies.

**Comment by ljharb** [comment]
Why shouldn't it? Assuming this file is a production file, then `beforeUpdate` is needed at runtime, so svelte is also.

**Comment by shadow-identity** [comment]
Svelte is a compiler, it compiles source and dependencies and adds required imports on the build step. It does not exist in production should not add itself into build. Moving `svelte` into `dependencies` increases build size with no reason.

**Comment by ljharb** [comment]
Why would it increase the build size if it's unused? Merely being in "dependencies" shouldn't cause anything to be automatically included in any build.

**Comment by shadow-identity** [comment]
Seems you're right, despite it doesn't make technical sense to move `svelte` it into `dependencies` for any reason other than to make eslint-plugin-import work, it also doesn't affect the build size and performance. I think I can close this issue, thanks for answers and sorry for your time.

**Comment by ljharb** [comment]
It makes sense because everything you reference in a production file should be in runtime deps, whether it ends up in the build output or not.

**Comment by shadow-identity** [comment]
There is no `svelte` package in production build of a svelte app. `.svelte` component is fantasy code, it exists only in a source file, then it is being compiled to JS. Svelte doesn't ship itself with a build.

**Comment by ljharb** [comment]
Right - but “with the build” isn’t how runtime and dev deps are divided, it’s more conceptual than that.
