### ISSUE TITLE
Rule `import/no-cycle` not working in a minimal repo

### ISSUE THREAD

**Issue by aapzu** [import-js/eslint-plugin-import#2895]
I cannot get the rule `import/no-cycle` to recognize any circular imports in my projects. I have created [this](https://github.com/aapzu/import-no-cycle-not-working-example) minimal repo to show the issue (CodeSandbox [here](https://codesandbox.io/p/github/aapzu/import-no-cycle-not-working-example)), but here are the main files:

```
// .eslintrc.js
const path = require('path');

const tsconfigPath = path.resolve(__dirname, './tsconfig.json');

module.exports = {
  plugins: ['import'],
  rules: {
    'import/no-cycle': ['error', { maxDepth: 10 }],
    'import/no-mutable-exports': 'error',
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: tsconfigPath,
  },
  settings: {
    'import/resolver': {
      typescript: {
        project: tsconfigPath,
      },
      node: true,
    },
  },
};

// tsconfig.json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2022"
  }
}

// foo.ts
import bar from './bar';

bar();

export default (): string | undefined => undefined;

// bar.ts
import foo from './foo';

foo();

export default (): string | undefined => undefined;

// this is here to indicate that `import/no-mutable-exports` is working
export let mutable = 1;
```
but still when I run eslint, I only get the `import/no-mutable-exports` error:
```
➜  workspace git:(main) ✗ pnpm eslint --ext .ts .

/project/home/aapzu/workspace/bar.ts
  8:8  error  Exporting mutable 'let' binding, use 'const' instead  import/no-mutable-exports

✖ 1 problem (1 error, 0 warnings)
```

What could be the reason for this?

**Comment by alxpsr** [comment]
Same question

**Comment by alxpsr** [comment]
@aapzu  So, seems i figured it out. You should add options as follows:

```
"extends": [
        "plugin:import/typescript"
],
```

After this i got an error `Dependency cycle`. Quite non-obvious. Isn't? Maybe it will be better if you describe this fact in docs. But maybe i skipped something important.

**Comment by ljharb** [comment]
Indeed if you're using TS, you need TS settings - see https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#typescript
