### ISSUE TITLE
TS broke after updating to 2.29.0

### ISSUE THREAD

**Issue by daniluk4000** [import-js/eslint-plugin-import#2902]
Configuration didn't change, all I did is updated to 2.29. Getting errors import/namespace: Resolve error: typescript with invalid interface loaded as resolver.

![image](https://github.com/import-js/eslint-plugin-import/assets/10450717/a113fa63-ce99-4e8e-b503-a636ab0af1ef)

**Comment by JounQin** [comment]
Please provide a runnable reproduction.

**Comment by daniluk4000** [comment]
![image](https://github.com/import-js/eslint-plugin-import/assets/10450717/00364695-df5b-45b9-af9f-5fbfa25fb7cf)

Bug is caused by this setting in `@nuxtjs/eslint-config-typescript` (my version is 12.1.0, cc @danielroe)

I have tried setting this in absolute empty repo and plugin indeed broke. @ljharb is this an invalid config now? If yes, then I will report a bug in Nuxt and close this issue.

**Comment by daniluk4000** [comment]
Repro repo: https://github.com/daniluk4000/eslint-import-bug

**Comment by JounQin** [comment]
A `typescript` key means you're trying to use `eslint-import-resolver-typescript` right? Did you install it specifically? Otherwise it will try to load `typescript` package as resolved which is obviously invalid.

**Comment by JounQin** [comment]
> Repro repo: https://github.com/daniluk4000/eslint-import-bug

According to the reproduction, you didn't install the correct resolver.

**Comment by daniluk4000** [comment]
Adding `eslint-import-resolver-typescript` to repro did solve the problem, but as I can see in specific Nuxt package it is installed, and error still occurs.

I will futher investigate, and either update reproduction and ask you to reopen this, or create bug in Nuxt Eslint. Thanks for the help.

**Comment by JounQin** [comment]
Is `eslint-import-resolver-typescript` installed at the root level of `node_modules`?

**Comment by daniluk4000** [comment]
> Is `eslint-import-resolver-typescript` installed at the root level of `node_modules`?

Yep.
![image](https://github.com/import-js/eslint-plugin-import/assets/10450717/b051d772-d614-4a18-8c88-7f9ab9cb4d4e)

And again, this didn't happen before 2.29.

**Comment by daniluk4000** [comment]
Screenshot mentioned above I took from monorepo setup, node_modules is on different level than eslint. That never was a problem tho...

**Comment by daniluk4000** [comment]
Hmm. Could this break monorepo setup?

![image](https://github.com/import-js/eslint-plugin-import/assets/10450717/5c2de9a2-6799-4b3f-b35a-adf60cf62e5e)

I will update repro later with monorepo and top-level node_modules instead. This could be it.

**Comment by ljharb** [comment]
I'll reopen until I can look into it further.

**Comment by daniluk4000** [comment]
> I'll reopen until I can look into it further.

I was just about to answer. It works fine with monorepos.

Also, for some reason problem has disappeared, I've done nothing but updated deps again. Have no idea what happened. Sorry for that.

**Comment by ljharb** [comment]
OK, in that case I'll close it for now; please lmk if it reoccurs.
