### ISSUE TITLE
semver pkg - Fix ReDoS Vulnerability 

### ISSUE THREAD

**Issue by martinez-hugo** [import-js/eslint-plugin-import#2906]
semver package have a ReDoS vulnerability 

you have more info here https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

This vulnerability is fixed on version 7.5.2 
Do you think that you can patch this vulnerability by update your semver dep ?

**Comment by ljharb** [comment]
a) it's not actually a vulnerability in general; b) we're not using that code path, so it's a false positive; c) we depend on semver v6 with `^` so you can just update your lockfiles.

Please don't just go spam file these issues all over the place until you've updated all your deps in your own lockfile?
