### ISSUE TITLE
`transitive` option for `import/no-nodejs-modules` (disallow imports that import node modules)

### ISSUE THREAD

**Issue by vassudanagunta** [import-js/eslint-plugin-import#2914]
`import/no-nodejs-modules` correctly prevents imports such as `import 'fs'`. But it misses things like `import fs-extra`, which imports `graceful-fs`, which imports node `fs`.

I'm guessing it might be too expensive to do this, given the sheer number of transitive imports that would have to be checked. On the other hand, `esbuild` handles processing the entire import tree very efficiently, though it is written in Go.

Is this possible? If not, any ideas for alternatives other than running in a browser and looking for runtime errors?  But even that isn't reliable if a polyfill gets involved.

**Comment by ljharb** [comment]
Yes, I think that'd be far too expensive. Separately, using a non-JS tool is a nonstarter.

This seems like the sort of thing you'd enforce in your bundler, to me.

**Comment by vassudanagunta** [comment]
I figured. Thanks.
