### ISSUE TITLE
import/no-unassigned-import causes `couldn't find a configuration file`

### ISSUE THREAD

**Issue by Issayev** [import-js/eslint-plugin-import#2932]
# ESLint couldn't find a configuration file
Eslint version: 8.55.0
eslint-plugin-import version: 2.29.0

## Error descrription
I put config file in separate folder (not to the root) and found a problem with `import/no-unassigned-import` rule when tried to use eslint with provided `--config` cli option. Disabling the rule removes error.  Also If the same config file is in the root folder, eslint works correctly. The error occurs only with `unusedExports: true` rule option. 

## Eslint output
![screenshot](https://github.com/import-js/eslint-plugin-import/assets/32362017/b63f7f30-3ee0-4b55-a607-709370422947)

## Error reproduction
[stackblitz](https://stackblitz.com/edit/node-rdcgwe?file=README.md)

## Similar issues
https://github.com/eslint/eslint/issues/16787

**Comment by ljharb** [comment]
The way that rule works, doesn't support a nonstandard config location. If you add an `.eslintrc` with `{ "root": true, "extends": "configs/.eslintrc.json" }` to the root, then everything will work without `--config`, including this rule.

**Comment by Issayev** [comment]
I've understood, thank you. Still, possibility to use non-standart name or location of config would be good

**Comment by zanminkian** [comment]
I face the same problem on `no-unused-modules` if I specify `--config`. Is there any possible to fix it?

**Comment by ljharb** [comment]
@zanminkian with eslintrc i don't think it's possible.

with flat config it may be, but the rule doesn't yet support flat config, so it's unclear.
