### ISSUE TITLE
`import/no-cycle` not working with `jsx` and `tsx` files

### ISSUE THREAD

**Issue by ronaldruzicka** [import-js/eslint-plugin-import#2933]
I recently found out, that `import/no-cycle` rule doesn't work in `.jsx` and `.tsx` files.

When I have two modules `a.ts` and `b.ts` that import each other. I get and error:
![Screenshot 2023-12-04 at 08 00 44](https://github.com/import-js/eslint-plugin-import/assets/20684387/16ba2bb9-9409-4e41-b645-b70efed8a46f)

![Screenshot 2023-12-04 at 08 01 09](https://github.com/import-js/eslint-plugin-import/assets/20684387/ad79cff7-dba4-4225-9f22-7e37eff5134f)

![Screenshot 2023-12-04 at 08 02 05](https://github.com/import-js/eslint-plugin-import/assets/20684387/4578ba18-846f-46ad-9249-3f0f38c42c37)

But when I use `.tsx` extension, the error is gone:
![Screenshot 2023-12-04 at 08 00 25](https://github.com/import-js/eslint-plugin-import/assets/20684387/2920d5bf-35cd-49b3-8dea-e0230e5f932b)

![Screenshot 2023-12-04 at 08 00 30](https://github.com/import-js/eslint-plugin-import/assets/20684387/1957cd0f-a0c4-4d48-b090-26be44b93a3e)

![Screenshot 2023-12-04 at 08 01 35](https://github.com/import-js/eslint-plugin-import/assets/20684387/9d3462d1-907b-4b65-a675-2a895ab773a2)

My `.eslintrc` file:
```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'airbnb-typescript/base',
    'plugin:prettier/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: [
    '@typescript-eslint',
    'typescript-sort-keys',
    'sort-destructure-keys',
    'import',
    'prettier',
  ],
  rules: {
    'import/extensions': ['error', { json: 'always', ts: 'never', tsx: 'never' }],
    'import/no-cycle': ['warn', { ignoreExternal: true }],
    'import/no-duplicates': 'error',
  },
};
```
I think it has something to do with `import/extensions` rule, because if I turn that rule off and import those files with the extension as `import { b } from './b.tsx';` I get an error. But I don't have to do it with `.ts` files, so there is still something weird about it.

Can anyone help?

**Comment by ljharb** [comment]
You have to specify the extensions setting, which you don't seem to be doing. See the readme.

**Comment by ronaldruzicka** [comment]
I tried it before, but it looked like it didn't work, but now it works properly. Probably it was just VS Code plugin that didn't show the error then.

Thanks!
