### ISSUE TITLE
missing guard case in `getParserPath` with flat config format

### ISSUE THREAD

**Issue by error-four-o-four** [import-js/eslint-plugin-import#2943]
Hey there,

I've run into an issue with the new flat config format: [repro](https://stackblitz.com/edit/stackblitz-starters-mh1kav?file=eslint.config.js)

Eslint outputs the error: `Parse errors in imported module './test': parserPath or languageOptions.parser is required! (undefined:undefined)` which originates from the function `getParserPath` of the 'eslint-module-utils' package: [source](https://github.com/import-js/eslint-plugin-import/blob/ee5fadeffff68f2300bed7f67a310496cb969d61/utils/parse.js#L135)

The function returns `context.parserPath` as a fallback (when the values of `import/parsers` are invalid). But as far as I can tell `context.parserPath` is not defined with the new flat config format, right?

**Comment by ljharb** [comment]
We don’t yet support the new flat config format - see #2873.
