### ISSUE TITLE
`import/no-import-module-exports`'s `exception` option root path ?

### ISSUE THREAD

**Issue by DrakaSAN** [import-js/eslint-plugin-import#2947]
I have a project with multiple points of entries (`index.ts` and `lambda.ts`, both on project's root), and am getting errors from the 'import/no-import-module-exports' rule

As described in the documentation, I tried to add:

```
'import/no-import-module-exports': ['error', { exceptions: ['lambda.ts']}],
```

to exclude that file and only that file from the rule.

The exception is however ignored, as it looks like I need to add `**/*` to catch the file in the glob.

I guess this is due to the glob starting from another place than the project's root, but it doesn't looks like it is documented ?

**Comment by ljharb** [comment]
Is this on the command line, or in an IDE?

Either way, the command needs to be run from the project root (like all commands in all projects), which also means that your editor needs to be opened from the project root.

**Comment by DrakaSAN** [comment]
Sorry for the late response, I didn't got the notification in time

This is in an IDE (VSCode with `dbaeumer.vscode-eslint` plugin), so this may actually be a problem on that front instead of your plugin itself

**Comment by ljharb** [comment]
Can you verify if it happens on the command line? If so, then we can fix it.

**Comment by DrakaSAN** [comment]
Cannot reproduce from command-line, so it looks like if there is an issue, it is on the plugin side
