### ISSUE TITLE
What is the difference vs eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by valerii15298** [import-js/eslint-plugin-import#2968]
here is also a quite popular plugin: https://www.npmjs.com/package/eslint-plugin-simple-import-sort

It is so hard to choose tooling in js ecosystem.
I wanna choose some plugins to sort imports automatically because the default eslint sort-imports plugin does not autofix imports for me.
So I found two of the most popular plugins: this and https://www.npmjs.com/package/eslint-plugin-simple-import-sort. And cannot understand what is the difference and what is better to use.
Would be very useful to add a comparison section for people to understand the difference...
Issue on another project: https://github.com/lydell/eslint-plugin-simple-import-sort/issues/161

**Comment by valerii15298** [comment]
Already found explanation!
https://github.com/lydell/eslint-plugin-simple-import-sort?tab=readme-ov-file#not-for-everyone
Closing this. Hope other people can find this to read the docs in that particular to understand the difference.

**Comment by lydell** [comment]
See also: https://github.com/lydell/eslint-plugin-simple-import-sort#how-is-this-rule-different-from-importorder
