### ISSUE TITLE
eslint(import/namespace): error 'BrowserTracing' not found in imported namespace 'Sentry'

### ISSUE THREAD

**Issue by binajmen** [import-js/eslint-plugin-import#2969]
I encountered an ESLint error stating that 'BrowserTracing' and 'Replay' were not found in the 'Sentry' namespace when using @sentry/remix.

The discussion suggests this might be related to how the Sentry import is resolved. See @lforst's comment in https://github.com/getsentry/sentry-javascript/issues/9728#issuecomment-1961198430 for reference:
> I think this is a bug in `eslint-plugin-import` that our SDK just happens to run into. Would you mind raising an issue there?
> 
> I don't feel the need to fix this in the SDK because Typescript itself and other eslint plugins are able to resolve the exports just fine 🤔

**Comment by ljharb** [comment]
https://unpkg.com/browse/@sentry/remix@7.102.1/package.json provides a `main`, but that points to https://unpkg.com/browse/@sentry/remix@7.102.1/cjs/index.server.js, which indeed lacks a `BrowserTracing` property and also lacks a `Replay` property.

iow, this seems like a bug in the CJS build of the package, not an issue with eslint-plugin-import (assuming it's present in the ESM build)

**Comment by lforst** [comment]
@ljharb Thanks for clarifying the behaviour of the plugin. As for the Sentry SDK, our source of truth is TS type-definitions. We have conditional exports in our package which cannot be represented by purely looking at the main field so I guess this is simply an incompatibility with `eslint-plugin-import`.

**Comment by ljharb** [comment]
If you're using the TS definitions, then you should be using the TS import resolver, which I think would work here.
