### ISSUE TITLE
Possibly confusing error message due to bias in package manager

### ISSUE THREAD

**Issue by handeyeco** [import-js/eslint-plugin-import#2972]
Hello 👋 Thanks for maintaining this project.

While working on our code ([source](https://github.com/Khan/perseus)), one of my peers encountered this error message:

> 'package-name' should be listed in the project's dependencies. **Run 'npm i -S package-name' to add it**
> 
> ([source](https://github.com/import-js/eslint-plugin-import/blob/df751e0d004aacc34f975477163fb221485a85f6/src/rules/no-extraneous-dependencies.js#L123))

However when they ran the suggested fix, they ran into a series of confusing issues - because we use `yarn`!

With the rise of `yarn` and now `pnpm`, I wonder if it'd be beneficial to either:

- Remove the `npm` suggestion so as to not confuse users
- Allow this to be configurable, maybe with a set of options:
  - `npm`
  - `yarn`
  - `pnpm`
  - exclude suggestion

I'd be glad to work on a PR if either of these suggestions would be accepted.

**Comment by ljharb** [comment]
This isn't a "bias" - npm is the de facto standard, and anyone using an alternative package manager always needs to "just know" how to translate npm commands to their package manager of choice.

yarn already has a suggested way of avoiding this problem, which is to use corepack.
