### ISSUE TITLE
Unable to resolve tsconfig.json.

### ISSUE THREAD

**Issue by shiyangzhaoa** [import-js/eslint-plugin-import#2975]
I have a monorepo project, and its structure looks like this:
```md
project
├── packages
│  ├── packageA
│  └── packageB
└── index.mjs
```
`project/packages/packageA/index.ts`:
```ts
// tsconfig alias
import app from '@/app';

// do something
// ...
```

`project/index.mjs`:
```js
import { ESLint } from 'eslint';

const eslint = new ESLint({
    cwd: '/workspace/project/packages',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
});

const result = await eslint.lintFiles('/workspace/project/packages/packageA/index.ts');

console.log('result---', result);
```

Run `index.mjs` in root directory path:
```shell
node /workspace/project/index.mjs
```

And ESLint will give an error message like this:
<img width="635" alt="image" src="https://github.com/import-js/eslint-plugin-import/assets/19943129/7e8dbeda-52fe-4107-9363-f9ae5382948d">

If I run `index.mjs` in the `packageA` path instead of the root directory, there is no problem:
```shell
cd /workspace/project/packages/packageA
node /workspace/project/index.mjs
```

I tried adding `tsconfigRootDir` to be able to find the `tsconfig.json` file:
```js
new ESLint({
    cwd: '/workspace/project/packages',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
    overrideConfig: {
      parserOptions: {
        tsconfigRootDir: '/workspace/project/packages/packageA'
      },
    },
  })
```
But it doesn't seem to work...

Here is some debugging information:
<img width="710" alt="image" src="https://github.com/import-js/eslint-plugin-import/assets/19943129/12ef9dbf-ad85-472e-b65e-e8f65779f533">

**Comment by JounQin** [comment]
Please read https://github.com/import-js/eslint-import-resolver-typescript's document carefully and raise issue to correct repository, and also with property online reproduction.
