### ISSUE TITLE
Unable to Access API Endpoint

### ISSUE THREAD

**Issue by jimmy34323** [import-js/eslint-plugin-import#2979]
I am currently working on integrating my application with the GitHub API to retrieve user information. However, I am encountering an issue where I am unable to access the API endpoint. I have followed the documentation and ensured that my authentication is set up correctly, but I am still receiving a 403 Forbidden error[.](https://getcapcut.in/) I have tried different endpoints and methods, but the issue persists. Any guidance or assistance on resolving this issue would be greatly appreciated.

**Comment by JounQin** [comment]
Why is this related to this eslint plugin??
