### ISSUE TITLE
`no-extraneous-dependencies` requeres restarting eslint server in vscode when adding new dependencies

### ISSUE THREAD

**Issue by DetachHead** [import-js/eslint-plugin-import#2999]
to reproduce:
1. install [the eslint vscode extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
2. add an import for a dependency that's not in your `package.json`
3. once the `no-extraneous-dependencies` error appears, add the dependency to your `package.json`

the error will stay there until you press `F1` and run the `ESLint: Restart ESLint Server` task

**Comment by ljharb** [comment]
You have to restart the eslint server (or all of vscode) whenever any dependencies change, this isn't unique to this plugin.

It's an inherent issue with the eslint vscode extension, because eslint rules aren't designed to be long-running.
