### ISSUE TITLE
[spam]

### ISSUE THREAD

**Issue by MigraalPL** [import-js/eslint-plugin-import#3000]
This is the log https://paste.md-5.net/umefinifop.md a have a problem i wanted to make a new world for the lobby to teleport
with the star but then i reloaded the serwer and the plugin dindt work

**Comment by MigraalPL** [comment]
Bro what spam?

**Comment by MigraalPL** [comment]
Nice support man no spam

**Comment by MigraalPL** [comment]
Very good support :)

**Comment by ljharb** [comment]
@MigraalPL i have no idea what deluxehub is, and your link has minecraft output, none of which is relevant to this repo.

**Comment by ljharb** [comment]
https://github.com/nodejs/help/issues/4369 is spam also. file an issue on minecraft, not node.
