### ISSUE TITLE
Status of upgrading to eslint v9?

### ISSUE THREAD

**Issue by StarManTheGamer** [import-js/eslint-plugin-import#3022]
Hi, I use your plugin originally when I was on v8 but I'm wishing to upgrade to v9 and I noticed that your plugin is not supported. Is there a plan for this dependency to be upgraded to v9? Just curious. Thanks.

**Comment by steffen-4s1** [comment]
See #2948

**Comment by ljharb** [comment]
Duplicate of #2948.
