### ISSUE TITLE
Config to match vscode import sorting default

### ISSUE THREAD

**Issue by chtpl** [import-js/eslint-plugin-import#3037]
What would a config look like that just mimics the default import order VS Code creates on the `Organize Imports` action?

**Comment by ljharb** [comment]
No idea. How does it order things?

**Comment by chtpl** [comment]
I didn't find a good documentation on that

Howevery, through experimenting I found this one works for a nx monorepo where the nx projects are named "abc"

```
"import/order": [
        "error",
        {
        "alphabetize": {
            "order": "asc",
            "caseInsensitive": true
        },
        "groups": [["builtin", "external"], "parent", "sibling", "index"],
        "pathGroups": [
            {
            "pattern": "@abc/**",
            "group": "builtin",
            "position": "before"
            }
        ],
        "newlines-between": "never"
        }
    ]
```

note that `"newlines-between": "never"` is not necessary, that's just my personal preference
