### ISSUE TITLE
Support for eslint v9 alternative

### ISSUE THREAD

**Issue by bluepeter** [import-js/eslint-plugin-import#3041]
For those beating their heads against the wall with this project and eslint v9, there's [a fork](https://github.com/un-ts/eslint-plugin-import-x) that now works with eslint 9: https://github.com/un-ts/eslint-plugin-import-x/issues/121#issuecomment-2311143084

**Comment by ljharb** [comment]
Please don't spam with competing projects, that's in very poor taste.

We'll support eslint 9 when we do, and until then, you shouldn't use eslint 9 if you want to use this project.
