### ISSUE TITLE
Missing `^9` eslint peer dependency

### ISSUE THREAD

**Issue by jpzwarte** [import-js/eslint-plugin-import#3056]
So with the latest release, the plugin now supports flat configs (which afaik are >= eslint 9 only). But the eslint peer dependency does not include `^9` yet?

This results in the following log line when running yarn: 

```
➤ YN0060: │ eslint is listed by your project with version 9.10.0 (pe2100), which doesn't satisfy what eslint-plugin-import and other dependencies request (^8.57.0).
```

Is this intentional or an oversight?

**Comment by mr-short** [comment]
https://github.com/import-js/eslint-plugin-import/pull/2996

**Comment by ljharb** [comment]
Very intentional - you can’t use this plugin with eslint 9 until we support it. Flat configs were released in eslint 8.

Duplicate of #2948.
