### ISSUE TITLE
🐞: [import/newline-after-import] Cannot recoginize the last require when use import and require in the same file

### ISSUE THREAD

**Issue by justYu2001** [import-js/eslint-plugin-import#3059]
# Example
```typescript
import moment from "moment";
import utils from "@/utils" // ESLint say I should have a newline after this line
const dataJson = require("./data.json");

// code...
```

# My ESLint Setting
```json
{
  "import/order":[
    "error",
    {
      "newlines-between":"never",
      "alphabetize":{
        "order":"asc",
        "caseInsensitive":true
      }
    }
  ],
  "import/newline-after-import":"error"
}
```

# Package version

- ESLint: 6.8.0
- eslint-plugin-import: 2.30.0

# Screenshot

<img width="894" alt="截圖 2024-09-11 下午5 26 55" src="https://github.com/user-attachments/assets/4d41609f-f74e-4d45-a042-f082c4bc84e0">

<img width="898" alt="截圖 2024-09-11 下午5 28 10" src="https://github.com/user-attachments/assets/f87bf798-4c23-4ec5-9f83-e7b39acfd2d5">

**Comment by ljharb** [comment]
You can't `require` and `import` in the same file.

**Comment by ljharb** [comment]
Also, eslint 6 is *very* out of date; you should be on eslint 8.

**Comment by justYu2001** [comment]
Yeah, you are right. I should replace `require()` with `import`. Thanks for your help. 👍
