### ISSUE TITLE
Add new resolver to wiki

### ISSUE THREAD

**Issue by romanlex** [import-js/eslint-plugin-import#3103]
Hello
Can you add new resolver to wiki page https://github.com/import-js/eslint-plugin-import/wiki/Resolvers

### @helljs/eslint-import-resolver-x
- [npm](https://www.npmjs.com/package/@helljs/eslint-import-resolver-x)
- [github](https://github.com/helljs/eslint-import-resolver-x)

This is fork of [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript) but much faster and more efficient. You can save time on project linting by (~30-40%)

for example `eslint-import-resolver-x` makes 10 MILLION fewer statx sys calls on codebase with 100 000 LOC 

![Image](https://github.com/user-attachments/assets/852d38c1-2d4b-4d40-bde9-2b61b9f10de3)

**Comment by ljharb** [comment]
Done, but you may want to consider making a PR to the upstream to improve its performance :-)

**Comment by romanlex** [comment]
Thank you.

My resolver should work the same with us or ts and also does not have typescript or javascript in the naming.

I'm thinking about further optimizations that will reduce the time spent on resolving to a minimum, I have no desire to try to reincarnate a package that everyone has forgotten.

**Comment by romanlex** [comment]
Thank you.

My resolver should work the same with us or ts and also does not have typescript or javascript in the naming.

I'm thinking about further optimizations that will reduce the time spent on resolving to a minimum, I have no desire to try to reincarnate a package that everyone has forgotten.
