### ISSUE TITLE
createSandbox not found in 'sinon'

### ISSUE THREAD

**Issue by mykola-mokhnach** [import-js/eslint-plugin-import#3132]
Eslint with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) complains about the above import, even though it's valid and defined in the corresponding sinon typescript manifest.

Steps to reproduce:
1. Checkout PR https://github.com/appium/appium/pull/20856
2. Run `npm i`
3. Run `npm run lint`

Actual result:
Multiple `createSandbox not found in 'sinon'  import/named` warnings. These warnings are generated for the following import statements: `import {createSandbox} from 'sinon';`

Expected results:
No warning for the above (valid) import.

Plugin version: 2.31.0
Eslint version: 9.17.0
Sinon version: 19.0.2

**Comment by ljharb** [comment]
That's because sinon exports [the result of a function call](https://unpkg.com/sinon@19.0.2/lib/sinon.js), so there's no way to statically determine what its exports are. You'll probably want to add it to `import/ignore`.

**Comment by mykola-mokhnach** [comment]
Thank you @ljharb for a quick response. Is there a possibility to only ignore this particular case? Because I'd like to keep this rule for other imports as it makes general sense and may help to reduce the amount of possible failures.

**Comment by mykola-mokhnach** [comment]
Or maybe you could advice how I can change that import statement to make the linter happy?

**Comment by ljharb** [comment]
you can put `// eslint-disable-next-line import/named` on the line before that particular import - or you could `import sinon from 'sinon'; const { createSandbox } = sinon;`.

**Comment by mykola-mokhnach** [comment]
Thanks, I've applied the first approach.
